### ISSUE TITLE
Destinations cleanup not complete

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/formcreator#261] opened 2016-09-20 13:22 UTC
version 0.85-1.2.3 & 0.90-1.3.4
Delete a destination from a form -> tables glpi_FC_targettickets & glpi_FC_targettickets_actors are not cleaned (records are still in the tables).

Please, check every object, part of a form, is cleaned when deleted.

**Comment by blerohellec** [comment] 2016-09-23 19:38
En fait, à la suppression définitive d'un formulaire, rien n'est purgé des tables sauf la table principale (glpi_plugin_FC_forms) !!
Du ménage s'impose

**Comment by btry** [comment] 2016-09-27 19:51
Hi

Can you validate the following patch ?
https://github.com/btry/formcreator/tree/261_destinations_cleanup

Direct download : https://github.com/btry/formcreator/archive/261_destinations_cleanup.zip

The changes do the following : 
- delete a section deletes associates questions
- delete a target deletes taret tickets and tarettickets_actors
- delete a form deletes associated sections, targets and formvalidators (also triggers the above mentioned deletions)

**Comment by blerohellec** [comment] 2016-09-28 21:36
did you include corrections of #260 ?

**Comment by btry** [comment] 2016-09-29 11:44
No : I wish to validate each bug individually; the branch fir this one does not contains the fix for #260. Anyway I just merged it in master, and if this issue is solved then I'll merge it too

**Comment by blerohellec** [comment] 2016-09-29 19:39
Here is what I get when I choose Assistance > Forms.
Please correct before getting ahead with the subject of this issue. Thx
![screenshot from 2016-09-29 21 33 39](https://cloud.githubusercontent.com/assets/9383475/18969351/1fe2035e-868d-11e6-87c9-eee06709bb1b.png)

**Comment by btry** [comment] 2016-09-30 05:16
Hi

I guess you used the master branch of my fork. It currently contains a new presentation and a new feature which will be merged in the official code very soon (probably today or next week).

These big changes are broken by your browser's cache. Simply hit F5 or Ctrl+F5 to refresh.

By the way, I would really appreciate your tests on this new development. I also hope you'll like it.

**Comment by btry** [comment] 2016-09-30 13:40
hi

New features have been added to the plugin (master branch on this repository). You will see a new presentation for forms, simiar to your screenshot. To arrange the mess caused by the browser's cache, you'll need to refresh it with F5 or Ctrl+F5.

![image](https://cloud.githubusercontent.com/assets/14139801/18993556/1099f7d4-8724-11e6-8826-05b2830c1fc7.png)

**Comment by btry** [comment] 2016-09-30 15:11
Added the fix in master

**Comment by blerohellec** [comment] 2016-10-02 16:56
Just tested the master. It's OK
Just notice that when a destination or a question is deleted, the counter in the tab is not updated (it's not -1)

**Comment by btry** [comment] 2016-10-02 19:33
Hi

I fixed this small issue : the whole page needs a refresh, not just the tab content.

**Comment by btry** [comment] 2016-10-12 13:49
hi

The issue is fixed. Clossing.

**Closed by btry** 2016-10-12 13:49 UTC
Labels: bug, need feedback
