### ISSUE TITLE
Formcrator does not generate ticket when clicking send with super-admin profile.

### ISSUE THREAD

**Issue by alexpfarias** [pluginsGLPI/formcreator#3272] opened 2023-05-04 18:49 UTC
After updating from GLPI 9.5 to GLPI 10.0.7 with FORm Creator 2.13.5, the forms do not generate a ticket when clicking on the send button. Generates the form in response to the form but does not create a ticket. When using another profile such as User or admin, it generates the ticker normally.

I have already reinstalled the Plugin, created new forms, even a new Super-admin profile the behavior is the same.

**Comment by btry** [comment] 2023-05-04 18:53
Hi

Did you check php-errors.log and sql-errors.log ? Maybe there is something useful to find what is happening.

**Comment by btry** [comment] 2023-08-19 19:40
Hi

Having no feedback, I assume the issue is solved, and I close it.

**Closed by btry** 2023-08-19 19:40 UTC
