### ISSUE TITLE
attached files missing on the created ticket

### ISSUE THREAD

**Issue by mcgs-94** [pluginsGLPI/formcreator#1702] opened 2020-03-12 10:19 UTC
**Describe the bug**

I created a form with a text area type question. After filling up the form, it automatically creates a ticket but whenever there are attached files on the ticket, the attached files doesn't appear on it. The files are uploaded in "documents" though. Can you pls help me solve this issue? Thank you in advance.

**To Reproduce**
1. Create a form with a text area.
2. Set the form so it targets to create automatically a ticket
3. Fill up the form and attach a file on it
4.See the error

**Expected behavior**

The file should be attached on the ticket and it should appear on the follow-ups.

GLPI: v9.4.5
Plugin\Forms: v2.9.1

**Comment by btry** [comment] 2020-03-12 10:23
Hi

A fix is in progress.

**Comment by mcgs-94** [comment] 2020-03-12 10:34
Hi,

Thank you for your fast response! Please kindly keep me informed whenever the fix is completed.

Thank you for your work.

Best regards,

**Comment by btry** [comment] 2020-03-17 14:57
issue #1073 is linked to this issue. The fix in dev should solve both.

**Comment by phamorais** [comment] 2020-04-22 12:40
@btry 


I have the same problem.

To get around the error, however it is not a definitive solution, I made the code snippet that called the Attachment field inside html.class. It worked for me as a palliative measure, but I will wait for a definitive solution from the community.

**Changed file:** html.class

**Comment by btry** [comment] 2020-04-22 17:43
Hi

I'm working on a définitive solution. This a patch for GLPI 9.5. It is nearly ready, waiting for more approbations.

However the fix will not be integrated in GLPI 9.4 due to this risk of regressions.

The fix in Form creator depends on it then I'll resume the fix plugin side later.

Please be patient.

**Comment by phamorais** [comment] 2020-04-22 20:51
@btry 

Thank you for the cordiality as always.

Include the code here, to help people who can't wait until version 9.5 (my case). However, making it clear that it is not a definitive solution.

**Comment by MCGS94** [comment] 2020-05-20 07:21
Hello,

If i update my glpi to 9.5 will the forms that i've already created be deleted?

**Comment by btry** [comment] 2020-05-20 12:10
Hi

 @MCGS94 your question is off topic. Please ask on the community forum for such question ( https://forum.glpi-project.org  ). Reserve issues on github for bugs or feature requests.

**Comment by btry** [comment] 2020-05-25 15:01
Hi @phamorais 

The PR for GLPI 9.5 was merged, but we choosed to *NOT* backport it to GLPI 9.4 because this is a quite sensitive change. A lot of tests and review were done, but regression risk still exists, according to some reviewers; and the backport is not trivial because if code move between GLPI 9.4 and GLPI 9.5 which affects the fix.

I did some changes in the plugin to reduce the issues with textareas and file uploads, but some problems will still occur, especially if there are several textareas in a single form.

**Comment by philippeplatiau** [comment] 2020-07-08 16:55
Hello,

For info, I have the issue with Formcreator 2.10.0 and GLPI 9.5 

I have a form, with 3 "questions": 

1) Subject : text field 
2) Description : textarea field
3) Attachments : "file" field

I tested a PPTX file, and also a TXT file. 

The file is uploaded in the "_tmp" folder but not  "moved" to the folder "PPTX" (and not in the "TXT" field) in  "files" 
The file is still in "_tmp" folder... 

When I open the ticket, the "form answer" says : no attached document

Adding a document in the ticket itself works, with the same profile "self-service"... But not via the form. 

I don't know if it's linked, but there is a SQL error : 

[2020-07-08 16:45:14] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 305
  *** MySQL query error:
  SQL: SELECT `id`, `name`, `plugin_formcreator_categories_id` AS `parent`, `level`, (SELECT COUNT(*) AS count FROM `glpi_plugin_formcreator_forms` WHERE `is_active` = '1' AND `is_deleted` = '0' AND `glpi_plugin_formcreator_forms`.`plugin_formcreator_categories_id` = glpi_plugin_formcreator_categories.id AND `language` IN ('en_GB', '', '0', NULL) AND (`access_rights` != '2' OR `id` IN (SELECT `plugin_formcreator_forms_id` FROM `glpi_plugin_formcreator_forms_profiles` WHERE `profiles_id` = '1')) AND ()) + (SELECT COUNT(*) AS count FROM (SELECT `glpi_knowbaseitems`.*, `glpi_knowbaseitemcategories`.`completename` AS `category`, COUNT(`glpi_knowbaseitems_users`.`id`) + COUNT(`glpi_groups_knowbaseitems`.`id`) + COUNT(`glpi_knowbaseitems_profiles`.`id`) + COUNT(`glpi_entities_knowbaseitems`.`id`) AS `visibility_count` FROM `glpi_knowbaseitems` LEFT JOIN `glpi_knowbaseitems_users` ON (`glpi_knowbaseitems_users`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_groups_knowbaseitems` ON (`glpi_groups_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_knowbaseitems_profiles` ON (`glpi_knowbaseitems_profiles`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_entities_knowbaseitems` ON (`glpi_entities_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) LEFT JOIN `glpi_knowbaseitemcategories` ON (`glpi_knowbaseitemcategories`.`id` = `glpi_knowbaseitems`.`knowbaseitemcategories_id`) WHERE (`glpi_knowbaseitems`.`users_id` = '6' OR `glpi_knowbaseitems_users`.`users_id` = '6' OR (`glpi_groups_knowbaseitems`.`groups_id` IN ('-1') AND (`glpi_groups_knowbaseitems`.`entities_id` < '0' OR (`glpi_groups_knowbaseitems`.`entities_id` IN ('0', '1', '2', '3', '4', '5', '6', '7')))) OR (`glpi_knowbaseitems_profiles`.`profiles_id` = '1' AND (`glpi_knowbaseitems_profiles`.`entities_id` < '0' OR ((`glpi_knowbaseitems_profiles`.`entities_id` IN ('0', '1', '2', '3', '4', '5', '6', '7'))))) OR (`glpi_entities_knowbaseitems`.`entities_id` IN ('0', '1', '2', '3', '4', '5', '6', '7'))) AND (`glpi_knowbaseitems`.`is_faq` = '1') AND `glpi_knowbaseitems`.`is_faq` = '1' GROUP BY `glpi_knowbaseitems`.`id`, `glpi_knowbaseitemcategories`.`completename`) as faqs WHERE (faqs.knowbaseitemcategories_id = glpi_plugin_formcreator_categories.knowbaseitemcategories_id) AND (`faqs`.`knowbaseitemcategories_id` != '0')) as items_count FROM `glpi_plugin_formcreator_categories` ORDER BY `level` DESC, `name` DESC
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) + (SELECT COUNT(*) AS count FROM (SELECT `glpi_knowbaseitems`.*, `glpi_kno...' at line 1
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:856                          DBmysqlIterator->execute()
  plugins/formcreator/inc/category.class.php:146     DBmysql->request()
  plugins/formcreator/ajax/homepage_wizard.php:56    PluginFormcreatorCategory::getCategoryTree()
  plugins/formcreator/ajax/homepage_wizard.php:39    plugin_formcreator_showWizardCategories()
  {"user":"6@glpitest"}



Regards,

Philippe

**Comment by philippeplatiau** [comment] 2020-07-09 05:04
Additional info: 

So, upload files from the form doesn't work. 
From the ticket "followups" section, it's ok 

I tested it with Self-Service, Admin, SuperAdmin profiles. Same results : no attached documents

**Comment by philippeplatiau** [comment] 2020-07-09 05:13
I found a workaround 

In the inc/fields/filefield.class.php : 

I changed : 

if (PLUGIN_FORMCREATOR_TEXTAREA_FIX && version_compare(GLPI_VERSION, '9.5.0-dev') < 0) {

by 

if (PLUGIN_FORMCREATOR_TEXTAREA_FIX && version_compare(GLPI_VERSION, '9.5.0-dev') **>** 0) {


The "<" into ">" 

Regards,

Philippe

**Comment by btry** [comment] 2020-07-30 13:24
Hi

Is the problem solved with the latest version 2.10.1 ?

**Comment by phamorais** [comment] 2020-07-30 13:49
@btry 
Works fine to me em 2.10 and 2.10.1

**Closed** 2020-07-30 14:28 UTC
Labels: bug
