### ISSUE TITLE
Translantion keys missing 

### ISSUE THREAD

**Issue by hotdesc** [pluginsGLPI/formcreator#872] opened 2017-12-29 18:58 UTC
In pt-BR locale doesn't have some keys

examples:
```
#: inc/form.class.php:122
msgid "Homepage"
msgstr ""

#: inc/form.class.php:130
msgid "Access"
msgstr ""
```

**Comment by hotdesc** [comment] 2017-12-29 19:01
And pot file is outdated and dont have all keys

**Comment by btry** [comment] 2017-12-29 19:08
Hi

You should use Transifex to localize the plugin. 

You may also use the features provided by Robo.li and the php script **RoboFile.php** to update the pot file.

clone the project with GIT. 
Ensure you're on the develop branch.
run **composer install**
run **vendor/bin/robo locales:extract**
use the updated POT file to create your new language

Once translated, submit a pull request with your new language file.

**Comment by btry** [comment] 2017-12-29 19:13
I updated the locales right now. I hope this will help you.

**Comment by hotdesc** [comment] 2018-01-02 13:04
I cant translate all strings on transifex
I sent as a suggestion the ones I could not translate

**Comment by btry** [comment] 2018-01-02 13:11
Hi

I'm currently preparing the next release, then your contribution will be included. Thank you very much.

If you cannot translate some strings, you may leave them empty, in the hope you find a solution later, or someone else contribute. As long as 70% of the languge is translated, the language will be used. Not translated strings will remain in english. 

Thank you again.

**Comment by hotdesc** [comment] 2018-01-02 13:57
The save button is locked for some translations.
That's why I can not translate everything.

I've sent suggestions in these cases.

**Comment by hotdesc** [comment] 2018-01-02 13:57
Transifex is updated with new keys?

**Comment by btry** [comment] 2018-01-02 14:18
The locales should be updated with the fix for #873 . I think this will help you.

**Comment by hotdesc** [comment] 2018-01-02 19:11
> clone the project with GIT.
> Ensure you're on the develop branch.
> run composer install
> run vendor/bin/robo locales:extract
> use the updated POT file to create your new language

I did this and the translation key does not appear

`$tab[] = [
         'id'                 => '9',
         'table'              => $this->getTable(),
         'field'              => 'access_rights',
         'name'               => __('Access'),
         'datatype'           => 'specific',
         'searchtype'         => [
            '0'                  => 'equals',
            '1'                  => 'notequals'
         ],
         'massiveaction'      => true
      ];`

**Access** key dont appear in glpi.pot file

**Comment by btry** [comment] 2018-01-02 19:20
When this is possible, the plugin reuses locales in GLPI itsenf, then __('Access') refers to a locale available in GLPI.

I'm checking, and it seems this string does not exists in GLPI 9.2. This is either a mistake in the plugin, either because the string disappeared in GLPI. I'll do a patch for this and hare here.

**Comment by btry** [comment] 2018-03-05 07:57
Hi @hotdesc 

Do you still have missing keys with version 2.6.2 ? I wish to close this issue.

**Comment by btry** [comment] 2018-03-26 12:12
Hi

Having no feedback, I guess the issue is solved. If not, please open a new ticket.

**Closed by btry** 2018-03-26 12:12 UTC
Labels: bug, need feedback, question
