### ISSUE TITLE
Bug Total Ticket

### ISSUE THREAD

**Issue by daniloramos** [pluginsGLPI/formcreator#2059] opened 2020-12-22 16:28 UTC
Hi,
At the top the user has the totals of tickets, processing, pending, validating and closed.

But those totals are wrong, it doesn't match the totals of a superadmin or support user.

To reproduce the problem you must log in with the user and add the ticket numbers in the upper corner.

Then access the system and filter the same user with the same status as everyone.

Support Screen Filter (231 results)
![image](https://user-images.githubusercontent.com/38350224/102910456-5abc4c80-4459-11eb-9c65-b9984f396a67.png)

User Screen Totals (196 results)
![image](https://user-images.githubusercontent.com/38350224/102910578-8f300880-4459-11eb-896c-fd4d2677891e.png)

Formcreator version: 2.10.4

**Comment by daniloramos** [comment] 2020-12-22 16:45
I went to check the pending tickets and the totals don't match.

the user's screen has 5 and the support screen has 7

**Comment by btry** [comment] 2020-12-23 08:19
Hi

When you're in the service catalog of the plugin you're restricted to tickets or form answers related to you. When you're in helpdesk with super admin account, this restriction does not applies. Therefore it does not make sense to compare the counters of the service catalog with the size of the (apparently) similar list in the helpdesk.

If you still think that some rows are missing or some rows should not display, then check how the user if the service catalog is involved with the faulty ticket. Is he a requester, observer or assigned ?

**Comment by daniloramos** [comment] 2020-12-28 15:48
HI,

You may not have understood the prints I sent.

The requesting user's screen with number of pending tickets different from the helpdesk screen with the number of pending tickets from the same requesting user.

the number must be the same, it cannot be different.


he is not an observer!

All pending tickets the user is the requester. The only thing is that there are more than one applicant on some tickets.

**Comment by btry** [comment] 2020-12-28 20:06
Hi
Let's focus on the 2 last screenshots, where you show a comaprison between the service catalog and the helpdesk.

In the helpdesk I see 2 tickets more than the service catalog, with IDs 15046 and 20121.

Let's focus on one of them first : 20121.

Please show the matching row in glpi_plugin_formcreator_issues and a screenshot of the main tab of the ticket 20121.

I want to see if there is an inconsistency. I need to see all users involved in the ticket. As it appears that you have privacy matters, you may want to replace the names of users and groups by their itemtype and ID.

**Comment by daniloramos** [comment] 2020-12-30 13:23
HI.

![image](https://user-images.githubusercontent.com/38350224/103352152-2b729480-4a84-11eb-9e8d-59e37a7909ef.png)


One line

**Comment by daniloramos** [comment] 2020-12-30 13:30
![image](https://user-images.githubusercontent.com/38350224/103353994-2237f680-4a89-11eb-8a44-89f3d1c7dec2.png)

one line
![image](https://user-images.githubusercontent.com/38350224/103353959-00d70a80-4a89-11eb-87a0-4bb8cdfd9051.png)

id 38 bruno
![image](https://user-images.githubusercontent.com/38350224/103354108-6deaa000-4a89-11eb-9cec-5cf6e9f34d70.png)

**Comment by btry** [comment] 2020-12-31 13:31
Hi

While investigating on your issue I found a bug which impacts the counters. Please apply the following patch

https://github.com/pluginsGLPI/formcreator/commit/b7cad38c229f87c8cadf3a5ddddedc0d15e6dd70

I expect that the counters in the service catalog will be slightly lower.

**Comment by btry** [comment] 2021-01-12 13:50
Hi

In the next version of Formcreator a new restriction will be added on  the search engine. It will no longer be possible to select a user requester different than "yourself" (the currently connected user). This change is needed  because GLPI itself has this restriction.

It should affect the handling of this issue.

**Comment by btry** [comment] 2021-01-20 15:16
Hi

I fixed some bugs in the autoamtic action SyncIssues of the plugin. See my latest posts in #1948. You'll find a sql query to see if you have missing rows in the table  glpi_plugin_formcreator_issues. If the query returns some rows, I can provide a query to rebuild them. Also, consider to disable the automatic action. It will be disabled in the next version.

**Comment by btry** [comment] 2021-01-22 12:53
Hi 

I think this issue is (at least partial) duplicate of #1948, which was closed right now.

There is a fix here for 2.10.4 : https://github.com/pluginsGLPI/formcreator/pull/2087 

Once applied, you need to force run the automatic action SyncIssues. It should repopulate the issues table. If not, you may find SQL queries to add only missing rows, near the end of the thread.

I would appreciate you test the latest revision of support/2.11.0 and feedback, as several fixes are added. This should be a better basis now than 2.10.4 to followup your issue.

**Comment by btry** [comment] 2021-01-28 14:20
Hi 

As I don't get any answer, I close this ticket.

**Closed by btry** 2021-01-28 14:20 UTC
Labels: bug, need feedback
