### ISSUE TITLE
bug sql on update plugin

### ISSUE THREAD

**Issue by prob6** [pluginsGLPI/formcreator#330] opened 2016-11-02 07:59 UTC
Bonjour,
je viens de tenter une mise a jour du plugin sur une 9.1 et je me heurte à des erreurs SQL sur la CAST de champ dans une requêtes SQL sur un UNION :
Illegal mix of collations for operation 'UNION'
La requête concernée semble être celle  qui est écrite dans le fichier inc/issue.class.php ligne 32
$query = "CREATE OR REPLACE VIEW `glpi_plugin_formcreator_issues` AS

                   SELECT DISTINCT
                          CONCAT(1,`fanswer`.`id`)      AS `id`,
                          `fanswer`.`id`                AS `original_id`,
                          'PluginFormcreatorFormanswer' AS `sub_itemtype`,
                          `f`.`name`                    AS `name`,
                          `fanswer`.`status`            AS `status`,
                          `fanswer`.`request_date`      AS `date_creation`,
                          `fanswer`.`request_date`      AS `date_mod`,
                          `fanswer`.`entities_id`       AS `entities_id`,
                          `fanswer`.`is_recursive`      AS `is_recursive`,
                          `fanswer`.`requester_id`      AS `requester_id`,
                          `fanswer`.`validator_id`      AS `validator_id`,
                          `fanswer`.`comment`           AS `comment`
                   FROM `glpi_plugin_formcreator_formanswers` AS `fanswer`
                   JOIN `glpi_plugin_formcreator_forms` AS `f`
                      ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
                   LEFT JOIN `glpi_items_tickets` AS `itic`
                      ON `itic`.`items_id` = `fanswer`.`id`
                      AND `itic`.`itemtype` = 'PluginFormcreatorFormanswer'

                   UNION

                   SELECT DISTINCT
                          CONCAT(2,`tic`.`id`)          AS `id`,
                          `tic`.`id`                    AS `original_id`,
                          'Ticket'                      AS `sub_itemtype`,
                          `tic`.`name`                  AS `name`,
                          `tic`.`status`                AS `status`,
                          `tic`.`date`                  AS `date_creation`,
                          `tic`.`date_mod`              AS `date_mod`,
                          `tic`.`entities_id`           AS `entities_id`,
                          0                             AS `is_recursive`,
                          `tic`.`users_id_recipient`    AS `requester_id`,
                          ''                            AS `validator_id`,
                          `tic`.`content`               AS `comment`
                   FROM `glpi_tickets` AS `tic`
                   LEFT JOIN `glpi_items_tickets` AS `itic`
                      ON `itic`.`tickets_id` = `tic`.`id`
                      AND `itic`.`itemtype` = 'PluginFormcreatorFormanswer'
                   WHERE ISNULL(`itic`.`items_id`)
                     AND `tic`.`is_deleted` = 0";

J'ai essayé de forcer le format de certains champs mais pour l'instant je n'ai pas trouvé quel champ coince.

**Comment by btry** [comment] 2016-11-02 09:00
Bonjour

Je pense qu'il faudrait vérifier la structure de toutes les tables concernées par la requete.

Avec un outil de manipulation de Mysql / MariaDB, reportez ici le résultat des requêtes suivantes : 
show create table glpi_plugin_formcreator_forms;
show create table glpi_plugin_formcreator_formanswers;
show create table glpi_items_tickets;
show create table glpi_tickets;

**Comment by philgprobesys** [comment] 2016-11-02 16:40
**show create table glpi_plugin_formcreator_forms**
CREATE TABLE `glpi_plugin_formcreator_forms` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `entities_id` int(11) NOT NULL DEFAULT '0',
 `is_recursive` tinyint(1) NOT NULL DEFAULT '0',
 `access_rights` tinyint(1) NOT NULL DEFAULT '1',
 `requesttype` int(11) NOT NULL DEFAULT '400013',
 `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
 `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
 `content` longtext COLLATE utf8_unicode_ci,
 `plugin_formcreator_categories_id` tinyint(3) unsigned NOT NULL,
 `is_active` tinyint(1) NOT NULL DEFAULT '0',
 `language` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
 `helpdesk_home` tinyint(1) NOT NULL DEFAULT '0',
 `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
 `validation_required` tinyint(1) NOT NULL DEFAULT '0',
 `usage_count` int(11) NOT NULL DEFAULT '0',
 `is_default` tinyint(1) NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`),
 FULLTEXT KEY `Search` (`name`,`description`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**show create table glpi_plugin_formcreator_formanswers**
CREATE TABLE `glpi_plugin_formcreator_formanswers` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
 `entities_id` int(11) NOT NULL DEFAULT '0',
 `is_recursive` tinyint(1) NOT NULL DEFAULT '0',
 `plugin_formcreator_forms_id` int(11) NOT NULL,
 `requester_id` int(11) DEFAULT NULL,
 `validator_id` int(11) DEFAULT NULL,
 `request_date` datetime NOT NULL,
 `status` enum('waiting','refused','accepted') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'waiting',
 `comment` text COLLATE utf8_unicode_ci,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**show create table glpi_items_tickets**
CREATE TABLE `glpi_items_tickets` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `itemtype` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
 `items_id` int(11) NOT NULL DEFAULT '0',
 `tickets_id` int(11) NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`),
 UNIQUE KEY `unicity` (`itemtype`,`items_id`,`tickets_id`),
 KEY `tickets_id` (`tickets_id`)
) ENGINE=MyISAM AUTO_INCREMENT=312345 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**show create table glpi_tickets**
CREATE TABLE `glpi_tickets` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `entities_id` int(11) NOT NULL DEFAULT '0',
 `name` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
 `date` datetime DEFAULT NULL,
 `closedate` datetime DEFAULT NULL,
 `solvedate` datetime DEFAULT NULL,
 `date_mod` datetime DEFAULT NULL,
 `users_id_lastupdater` int(11) NOT NULL DEFAULT '0',
 `status` int(11) NOT NULL DEFAULT '1',
 `users_id_recipient` int(11) NOT NULL DEFAULT '0',
 `requesttypes_id` int(11) NOT NULL DEFAULT '0',
 `content` longtext CHARACTER SET utf8,
 `urgency` int(11) NOT NULL DEFAULT '1',
 `impact` int(11) NOT NULL DEFAULT '1',
 `priority` int(11) NOT NULL DEFAULT '1',
 `itilcategories_id` int(11) NOT NULL DEFAULT '0',
 `type` int(11) NOT NULL DEFAULT '1',
 `solutiontypes_id` int(11) NOT NULL DEFAULT '0',
 `solution` longtext COLLATE utf8_unicode_ci,
 `global_validation` int(11) NOT NULL DEFAULT '1',
 `slts_ttr_id` int(11) NOT NULL DEFAULT '0',
 `slts_tto_id` int(11) NOT NULL DEFAULT '0',
 `ttr_slalevels_id` int(11) NOT NULL DEFAULT '0',
 `due_date` datetime DEFAULT NULL,
 `time_to_own` datetime DEFAULT NULL,
 `begin_waiting_date` datetime DEFAULT NULL,
 `sla_waiting_duration` int(11) NOT NULL DEFAULT '0',
 `waiting_duration` int(11) NOT NULL DEFAULT '0',
 `close_delay_stat` int(11) NOT NULL DEFAULT '0',
 `solve_delay_stat` int(11) NOT NULL DEFAULT '0',
 `takeintoaccount_delay_stat` int(11) NOT NULL DEFAULT '0',
 `actiontime` int(11) NOT NULL DEFAULT '0',
 `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
 `locations_id` int(11) NOT NULL DEFAULT '0',
 `validation_percent` int(11) NOT NULL DEFAULT '0',
 `date_creation` datetime DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `date` (`date`),
 KEY `closedate` (`closedate`),
 KEY `status` (`status`),
 KEY `priority` (`priority`),
 KEY `request_type` (`requesttypes_id`),
 KEY `date_mod` (`date_mod`),
 KEY `entities_id` (`entities_id`),
 KEY `users_id_recipient` (`users_id_recipient`),
 KEY `solvedate` (`solvedate`),
 KEY `urgency` (`urgency`),
 KEY `impact` (`impact`),
 KEY `global_validation` (`global_validation`),
 KEY `slalevels_id` (`ttr_slalevels_id`),
 KEY `due_date` (`due_date`),
 KEY `users_id_lastupdater` (`users_id_lastupdater`),
 KEY `type` (`type`),
 KEY `solutiontypes_id` (`solutiontypes_id`),
 KEY `itilcategories_id` (`itilcategories_id`),
 KEY `is_deleted` (`is_deleted`),
 KEY `name` (`name`),
 KEY `locations_id` (`locations_id`),
 KEY `date_creation` (`date_creation`),
 KEY `slts_tto_id` (`slts_tto_id`),
 KEY `time_to_own` (`time_to_own`)
) ENGINE=InnoDB AUTO_INCREMENT=358889 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**Comment by btry** [comment] 2016-11-21 16:17
Je pensais trouver une incohérence entre des CHARSET et des COLLATE mais ça me semble bon.

Si vous reproduisez sur une BDD de test, pouvez-vous essayer de définir une vue avec la requête suivante (j'ai retiré **validator_id** des deux côtés de l'UNION) ?

Je soupçonne la chaine vide dans la seconde partie d'être à la source su problème.

```
               SELECT DISTINCT
                      CONCAT(1,`fanswer`.`id`)      AS `id`,
                      `fanswer`.`id`                AS `original_id`,
                      'PluginFormcreatorFormanswer' AS `sub_itemtype`,
                      `f`.`name`                    AS `name`,
                      `fanswer`.`status`            AS `status`,
                      `fanswer`.`request_date`      AS `date_creation`,
                      `fanswer`.`request_date`      AS `date_mod`,
                      `fanswer`.`entities_id`       AS `entities_id`,
                      `fanswer`.`is_recursive`      AS `is_recursive`,
                      `fanswer`.`requester_id`      AS `requester_id`,
                      `fanswer`.`comment`           AS `comment`
               FROM `glpi_plugin_formcreator_formanswers` AS `fanswer`
               JOIN `glpi_plugin_formcreator_forms` AS `f`
                  ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`items_id` = `fanswer`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormanswer'

               UNION

               SELECT DISTINCT
                      CONCAT(2,`tic`.`id`)          AS `id`,
                      `tic`.`id`                    AS `original_id`,
                      'Ticket'                      AS `sub_itemtype`,
                      `tic`.`name`                  AS `name`,
                      `tic`.`status`                AS `status`,
                      `tic`.`date`                  AS `date_creation`,
                      `tic`.`date_mod`              AS `date_mod`,
                      `tic`.`entities_id`           AS `entities_id`,
                      0                             AS `is_recursive`,
                      `tic`.`users_id_recipient`    AS `requester_id`,
                      `tic`.`content`               AS `comment`
               FROM `glpi_tickets` AS `tic`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`tickets_id` = `tic`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormanswer'
               WHERE ISNULL(`itic`.`items_id`)
                 AND `tic`.`is_deleted` = 0;
```

**Comment by btry** [comment] 2017-04-03 16:07
#498 is duplicate of this issue, solved solved as a consequence of schema change in version 2.4.1

**Closed by btry** 2017-04-03 16:07 UTC
Labels: bug
