### ISSUE TITLE
Edit Ticket font

### ISSUE THREAD

**Issue by Semprus** [pluginsGLPI/formcreator#1101] opened 2018-09-07 08:38 UTC
Hello,

I would like to know if it is possible to change the text font of the ticket which is generated from forms.

I tried to use the HTML balises but it's not working.

Thanks

**Comment by btry** [comment] 2018-09-07 09:06
Hi

You can only customize the size of the text. rich text mode of GLPI does not allows you to choose a font.

I don't plan to provide this feature because GLPI itself does not offers it in its rich text areas, and the plugin must generate tickets in a way as close as possible GLPI does itself.

Also, GLPI uses a HTML cleanup library for reliability and security reasons (HTMLawed). Thus, even if I want to implement the feature I may fail (needs to be confirmed).

I think this requires a lot of work and tests for something which does not adds a real value to the plugin.

Consider using colors, bold, italic and predefined styles instead.

I leave the issue open to read your comments. Maybe you could explain why you need this feature ?

**Comment by btry** [comment] 2018-09-07 09:41
Then check if rich text mode is enabled in GLPI. If not, you can enable it and Formcreator will show rich text areas.

If I remember correctly, glpi warns you if you try disable rich text mode. Try to enable then disable this mode in a testing environment to confirm this.

**Comment by Semprus** [comment] 2018-09-07 10:03
Ok I just activated the option "rich text" and it's working sorry I just not know this option.

Thank you for your help

**Comment by btry** [comment] 2018-09-09 17:40
Ok, then I close the issue, thanks for your feedback.

**Closed by btry** 2018-09-09 17:40 UTC
Labels: question
