### ISSUE TITLE
Le compteur dans la barre du Haut affiche N/A 

### ISSUE THREAD

**Issue by DooBio** [pluginsGLPI/formcreator#2410] opened 2021-09-20 12:23 UTC
**Describe the bug**
Suite à la dernière mise jour de FormCreator en version 2.12.2 La barre du haut pour les utilisateurs affiche toujours N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/32511461/134001104-d40f4997-c1ee-4c2d-9cb9-36700c9b999d.png)

** Fichier de Log **
[sql-errors.log](https://github.com/pluginsGLPI/formcreator/files/7195632/sql-errors.log)

**Desktop and GLPI **
 - OS: Windows 10 
 - Browser Chrome 
 - Version 93.0.4577.82
 - GLPI version : 9.5.6

**Comment by leonardolins2021** [comment] 2021-09-21 21:56
same problem.

**Comment by btry** [comment] 2021-09-22 06:36
Hi

@leonardolins2021, please check sql-errors.log to see if you have errors like those shared by @DooBio . If yes, then this is the same problem. If not, this is only the same symptom (and you may have a different root cause).

@DooBio your problem comes from an attempt to query an non-existing column in DB (it existed up to 2.11).

Please check that you have only one copy of Formcreator in the folders plugins and marketplace. If you have Formcreator on both directories, delete the copy which is **not** version 2.12.2. 

I'm waiting for your feedback about that.

**Comment by btry** [comment] 2022-01-29 15:22
Hi

Having no feedback, I close this issue.

**Closed by btry** 2022-01-29 15:22 UTC
Labels: need feedback
