### ISSUE TITLE
Problem with mail notification

### ISSUE THREAD

**Issue by proprux** [pluginsGLPI/formcreator#833] opened 2017-11-30 13:39 UTC
Hello

We have a problem with email notifications related to entered forms. Indeed during the validation of the form, the notifications are sent with the tags and not the contents of this one.
Here is an example of what we receive.

![glpi-pb-notif](https://user-images.githubusercontent.com/14869045/33433502-1c9453ba-d5dc-11e7-8611-1c39d003c778.png)

We are in version 9.2 for GLPI and 2.6.0 for the formcreator plugin

Thanks for your help

**Comment by btry** [comment] 2017-12-01 06:49
Hi

Can you export your form and share it here ?

**Comment by proprux** [comment] 2017-12-01 07:39
Hello,

here the content of export file

`{"forms":[{"name":"jerome","content":"","is_active":1,"is_recursive":0,"language":"fr_FR","validation_required":1,"is_default":0,"uuid":"b70635d6-6dfcc468-5a1fc3fdbda959.79238215","access_rights":2,"requesttype":9,"description":"","helpdesk_home":1,"is_deleted":0,"_plugin_formcreator_category":"&nbsp;","_sections":[{"uuid":"b70635d6-6dfcc468-5a0956eccc68f1.78854584","name":"Section 1","order":1,"_questions":[{"uuid":"b70635d6-6dfcc468-5a09570856b230.38683899","name":"Question 1","description":"","order":1,"fieldtype":"radios","required":1,"show_empty":0,"default_values":"Oui","values":"Oui\r\nNon","range_min":"","range_max":"","regex":"","show_rule":"always","_conditions":[]},{"uuid":"b70635d6-6dfcc468-5a09570cf3d059.36203130","name":"Question 2","description":"","order":2,"fieldtype":"checkboxes","required":0,"show_empty":0,"default_values":"Non","values":"Oui\r\nNon","range_min":"","range_max":"","regex":"","show_rule":"always","_conditions":[]},{"uuid":"b70635d6-6dfcc468-5a20276d33c989.88671696","name":"choix 1","description":"","order":3,"fieldtype":"select","required":1,"show_empty":1,"default_values":"","values":"item 1\r\nitem 2\r\nitem3","range_min":"","range_max":"","regex":"","show_rule":"always","_conditions":[]}]},{"uuid":"b70635d6-6dfcc468-5a095724edc774.96170244","name":"Section 2","order":2,"_questions":[{"uuid":"b70635d6-6dfcc468-5a095727d47e33.97168313","name":"Question 3","description":"","order":1,"fieldtype":"checkboxes","required":0,"show_empty":0,"default_values":"Non","values":"Oui\r\nNon","range_min":"","range_max":"","regex":"","show_rule":"always","_conditions":[]},{"uuid":"b70635d6-6dfcc468-5a09572b0693e8.68614796","name":"Question 4","description":"","order":2,"fieldtype":"checkboxes","required":0,"show_empty":0,"default_values":"Non","values":"Oui\r\nNon","range_min":"","range_max":"","regex":"","show_rule":"always","_conditions":[]},{"uuid":"b70635d6-6dfcc468-5a09575236d608.63643738","name":"Question 5","description":"","order":3,"fieldtype":"radios","required":0,"show_empty":0,"default_values":"Oui","values":"Oui\r\nNon","range_min":"","range_max":"","regex":"","show_rule":"always","_conditions":[]},{"uuid":"b70635d6-6dfcc468-5a1fcb4d409025.35300337","name":"procedure","description":"&lt;p&gt;procedure&lt;/p&gt;","order":4,"fieldtype":"description","required":0,"show_empty":0,"default_values":"","values":"Computer","range_min":"","range_max":"","regex":"","show_rule":"always","_conditions":[]}]}],"_validators":[{"itemtype":"User","uuid":"b70635d6-6dfcc468-5a1fc3fdbd0d03.46748759","_item":"mail@home.com"}],"_targets":[{"uuid":"b70635d6-6dfcc468-5a1fe1ec97da94.58668860","name":"test","urgency":1,"priority":1,"type":2,"itilcategories_id":0,"itemtype":"PluginFormcreatorTargetTicket","_data":{"name":"test","comment":"<p>Bonjour</p>\r\n<p>Vous trouverez ci-dessous les données du fomulaire saisi:</p>\r\n<table style=\"height: 33px;\" width=\"301\">\r\n<tbody>\r\n<tr>\r\n<td style=\"width: 291px;\"> </td>\r\n</tr>\r\n<tr>\r\n<td style=\"width: 291px; text-align: center;\">##FULLFORM##</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p> </p>\r\n<p>Cordialement.</p>\r\n<p>--</p>\r\n<p>Form : jerome</p>","due_date_rule":"","due_date_question":0,"due_date_value":-30,"due_date_period":"minute","urgency_rule":"none","urgency_question":0,"validation_followup":1,"destination_entity":"current","destination_entity_value":null,"tag_type":"none","tag_questions":"","tag_specifics":"","category_rule":"none","category_question":0,"uuid":"b70635d6-6dfcc468-5a1fe1ec983437.00788242","location_rule":"none","location_question":0,"_ticket_relations":[],"_actors":[{"uuid":"b70635d6-6dfcc468-5a0956df4f25b9.12961993","actor_role":"requester","actor_type":"creator","actor_value":null,"use_notification":1},{"uuid":"b70635d6-6dfcc468-5a0956df4f5233.88262281","actor_role":"observer","actor_type":"validator","actor_value":null,"use_notification":1},{"uuid":"b70635d6-6dfcc468-5a1fc3bde660b5.23464726","actor_role":"assigned","actor_type":"validator","actor_value":0,"use_notification":1}]}}],"_profiles":[{"uuid":null,"_profile":"Infrastructure"}]}]}`

thanks for your help

**Comment by proprux** [comment] 2017-12-07 10:01
Hi,

Do you have any idea ?

thanks for your help

**Comment by btry** [comment] 2017-12-07 10:02
Hi

Please be patient, I did not had time to run your form yet.

**Comment by proprux** [comment] 2017-12-07 10:39
ok thanks again

**Comment by btry** [comment] 2017-12-11 16:58
Hi

I don't reproduce. I tried the release 2.6.0 and the develop branch.

Can you check sql-errors.log and php-errors.log ?

Also there are a lot of fixes in the develop branch, it might be interesting that you give it a try.

**Comment by btry** [comment] 2017-12-26 13:49
Hi

No feedback ? I'm also wondering the content if the ticket generated by the form. If the notification contains tags instead of their value , then I expect the ticket also contains tags.

**Comment by Ez3kield** [comment] 2018-02-12 13:11
Hi, 

I've the same issue in the release 2.6.2 with GLPI 9.2.1.
The description of the generated ticket contains the form but the notification only the tags name.

**Comment by btry** [comment] 2018-02-12 13:16
Hi

Please check sql-errros.log. Maybe there is an issue with an unescaped single quote.

**Comment by Ez3kield** [comment] 2018-02-12 14:44
This isn't the case, I have no error in the log.

**Comment by btry** [comment] 2018-04-25 14:28
Hi

Your backtrace shows an escaping problem, but it seems it occured when you duplicated a form. Is the failing form duplicated from an other ?

**Comment by fabjal** [comment] 2018-04-25 14:30
Yes, it is a duplicated form. However, the problem is present on all forms notifications, not just this one.

**Comment by btry** [comment] 2019-05-10 13:20
Hi

Due to refactor in versions 2.7 and later, the issue is obsoleted, and likely solved (no new similar issue reported).

Closing

**Closed by btry** 2019-05-10 13:20 UTC
Labels: bug
