### ISSUE TITLE
 Formcreator: Error using "question answer"

### ISSUE THREAD

**Issue by mrcssilvasouza** [pluginsGLPI/formcreator#1738] opened 2020-04-25 01:01 UTC
The form does not allow you to use the "question answer" randomly. Accept only the first option, whatever the field: category, urgency, ...

![image](https://user-images.githubusercontent.com/30185683/80267410-22b8fb80-8677-11ea-9ad2-9fd94a9fab28.png)

**Comment by mrcssilvasouza** [comment] 2020-04-28 19:10
Other drop-down lists appear as an option for category, however when saving the form, it is applied to categories in the ticket category list.

**Comment by btry** [comment] 2020-04-29 06:22
Hi 

 Can you test the branch support/2.9.0 ?

**Comment by mrcssilvasouza** [comment] 2020-04-30 23:16
I'm using version 2.9.1

**Comment by btry** [comment] 2020-05-12 13:17
Hi

I think this is fixed in the branch support2.9.0 (I remember 2 problems on this view). You may want to try it. It was bumped to 2.9.3-dev because I prepared the release 2.9.2 today. It will be published soon.

**Comment by btry** [comment] 2020-07-30 13:20
Hi

Having no feedback I assume the problem is solved.

**Closed by btry** 2020-07-30 13:20 UTC
Labels: bug
