### ISSUE TITLE
Unable to display multiple files in same field

### ISSUE THREAD

**Issue by Synairgis** [pluginsGLPI/formcreator#1049] opened 2018-07-19 15:39 UTC
**Describe the bug**
If I create a file input in a given form and upload two files in it then save the form, I only see the first file that is actually uploaded.

**To Reproduce**
1. Create a form with a "file" input
2. Upload two files using the input
3. Save the form
4. Go and see it in the "form answer" section. You'll only see one file associated with the input.

**Expected behavior**
I would expect the input to display all the files that were uploaded with the question. Instead, I only have one.

**Additional context**
The problem here lies with the fact that the plugin expects to have one "answer" per question. However, in this case, the two files constitute two "answers" so the plugin doesn't really know what to do with this.

**Comment by btry** [comment] 2018-08-01 14:30
Hi

This is the currently expected behavior. I will review and merge a contribution to remove this limitation in the version 2.7.0 (because i consider this is more a feature than a bug).

**Comment by btry** [comment] 2019-05-10 12:49
Hi

Feature implemented in 2.7.0. Closing.

**Closed by btry** 2019-05-10 12:49 UTC
Labels: feature
