### ISSUE TITLE
Impossible to modify the name of a destination

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/formcreator#262] opened 2016-09-23 14:51 UTC
v 0.85-1.2.3 & 0.90.1.3.4
Try to modify the name of a destination (first field when edit a destination)
Modification is not registered ! (no sql, nor php errors)
Workaround : modify glpi_plugin_FC_targets.name in db

**Comment by btry** [comment] 2016-09-25 20:23
Hi 

It seems this is a duplicate of #200 and your plugin is not up to date. 

With the latest master branch I don't reproduce again.

**Comment by blerohellec** [comment] 2016-09-26 08:47
indeed, it's a duplicate of #200 and the pb is solved with master branch

**Closed** 2016-09-26 08:59 UTC
