### ISSUE TITLE
2.13.0-alpha.2 - Installation Error

### ISSUE THREAD

**Issue by roshanroche** [pluginsGLPI/formcreator#2514] opened 2021-12-23 12:45 UTC
Hi,

While trying to install 2.13.0-alpha.2 im getting the following error.

i am trying on a upgraded database on glpi. ( from 9.5 to 10 Beta )

![image](https://user-images.githubusercontent.com/22425503/147242215-f74dc482-e31d-4c58-831b-c8bf18ed6790.png)

**Comment by btry** [comment] 2021-12-23 12:47
Hi

Is Formcreator already installed, and which version ?

**Comment by roshanroche** [comment] 2021-12-23 12:49
Hi

2.10.2

i uninstalled it now im getting the following error

Upgrade glpi_plugin_formcreator_answers (0 seconds)

Table 'gshelpdesk10.glpi_plugin_formcreator_answers' doesn't exist

Please, check migration log

**Comment by btry** [comment] 2021-12-23 13:01
> Table 'gshelpdesk10.glpi_plugin_formcreator_answers' doesn't exist

Let me describe a possible scenario for this error:
- you have a previous installation of Formcreator 2.10, with its tables in DB
- you upgraedd the plugin to 2.13 in the filesystem
- you failed to upgrade
- you uninstall the plugin using CLI or GLPI UI
- at least one table existing in version 2.10 does no longer exists in 2.13, then this table is not deleted
- you try to proceed the installation of 2.13 (creation of tables in DB)
- the plugin finds at least one table and instead of a fresh install, it attempts an upgrade
- changing the schema if a table which is missing cause an installation failure.

If I'm right, then 
- delete all tables with name beginning with **glpi_plugin_formcreator_**
- run SELECT * FROM glpi_configs WHERE context='formcreator';
- if you find a row delete it

finally try again to run the installation

It is planned to drop the upgrade code from versions lower than 2.5.0 soon (code ready to merge). Despite this change does not targets to avoid issues like yours, I believe this may help.

**Comment by btry** [comment] 2022-06-08 09:08
Hi

Having no fedback, then I assume the problem is solved. Closing.

**Closed by btry** 2022-06-08 09:08 UTC
