### ISSUE TITLE
SQLP errors Message --> Error: You have an error in your SQL syntax; 

### ISSUE THREAD

**Issue by FRANCOIS50** [pluginsGLPI/formcreator#984] opened 2018-05-04 08:08 UTC
HI,
 I receive regularly the following messages in the sql-errors.log file:

 *** MySQL query error:
 SQL: UPDATE glpi_plugin_formcreator_issues
 SET comment = '<p><span style=\"font-size: small; font-family: sans-serif;\">Bonjour,</span> <br /> <br /><span style=\"font-size: small; font-family: sans-serif;\">Merci de me dÃ©bloquer l\'accÃ¨s au dossiers Y:\\Commun' WHERE id ='6530'
 Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '6530'' at line 2
 Backtrace :
 inc/commondbtm.class.php:433
 inc/commondbtm.class.php:1231 CommonDBTM->updateInDB()
 plugins/formcreator/hook.php:279 CommonDBTM->update()
 inc/plugin.class.php:1259 plugin_formcreator_hook_update_ticket()
 inc/commondbtm.class.php:1233 Plugin::doHook()
 front/ticket.form.php:77 CommonDBTM->update()
_____________________________________________________________________________________________________________

My config: GLPI 9.2.2 / Fusioninventory: 9.2+1.1 / PHP 7.0 / MySQL server 5.7.21-0ubuntu0.16.04.1 - (Ubuntu)
 could you check this problem? Please

**Comment by btry** [comment] 2018-05-04 08:13
Seems there is a escaping problem. That's unfortunate you report it only today; I release the version 2.6.3 this week.

I'll try to reproduce. I may need to ask you some questions, then stay tuned please.

**Comment by FRANCOIS50** [comment] 2018-05-05 12:18
I installed the GLPI 9.2.3 an it's solve the problem. Thanks for your help

**Comment by btry** [comment] 2018-10-16 11:09
Hi,

@vemi2709 do you have a a single quote in the query ? Check the logs and consider sharing the entry matching the issue.

**Comment by btry** [comment] 2018-10-16 11:09
Version 2.6.5 is on its way this is an opportunity to have a quick release with the fix.

**Comment by vemi2709** [comment] 2018-10-16 11:11
Hi, here is the entry in the log:

  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_formcreator_issues` SET `comment` = '&lt;div class=\"WordSection1\"&gt;&lt;p class=\"MsoNormal\"&gt;&lt;span lang=\"FI\"&gt;Hei!&lt;/span&gt;&lt;/p&gt;&lt;p 
class=\"MsoNormal\"&gt;&lt;span lang=\"FI\"&gt;Outlookin kalenterin kautta ei voi varata huoneita.&lt;/span&gt;&lt;/p&gt;&lt;p class=\' WHERE `id` = '36585'
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '36585'' at line 1
  Backtrace :
  inc/dbmysql.class.php:1029                         
  inc/commondbtm.class.php:578                       DBmysql->update()
  inc/commondbtm.class.php:1374                      CommonDBTM->updateInDB()
  plugins/formcreator/hook.php:311                   CommonDBTM->update()
  inc/plugin.class.php:1271                          plugin_formcreator_hook_update_ticket()
  inc/commondbtm.class.php:1376                      Plugin::doHook()
  front/ticket.form.php:73                           CommonDBTM->update()

**Comment by btry** [comment] 2018-10-16 12:37
I don't reproduce the issue. The bug seems related to an escaping problem, but the code is correct and escapes the single quotes (the lines of code are lost modified in september 2017, then before the version 2.6.4 release).

I also notice that the value inserted in the DB is incomplete and seems truncated. Can you cheeck in php-errors.log if you have a warning about a value being truncated to 254 characters ? (the message contains the word **exceeds**)

**Comment by btry** [comment] 2018-10-16 13:27
OK, then you are impacted by a bug I found yesterday. Here is the fix: https://github.com/pluginsGLPI/formcreator/commit/5e2d7e2a45997127c96d8b250d7f0f3a30d7a1a1

It is merged and will be included in 2.6.5.

**Comment by vemi2709** [comment] 2018-10-17 03:53
Thanx, I'll give it a go.

**Comment by vemi2709** [comment] 2018-10-22 06:52
It looks like there has not been any further errors in the log (except those generated by Dashboard-plugin, we've had those for a long time). So the fix seems to work. Great 8). Thanx :)

**Comment by btry** [comment] 2018-10-22 06:57
Hi, thank you for your feed back. I can close this issue.

**Closed by btry** 2018-10-22 06:57 UTC
Labels: bug
