### ISSUE TITLE
Forms no longer appear on the homepage

### ISSUE THREAD

**Issue by tlaugier** [pluginsGLPI/formcreator#2953] opened 2022-09-01 12:00 UTC
We are currently migrating our forms to a new GLPI 10 instance and we realized that forms no longer appear on the homepage of self service users, even though the option is still available in the form settings and active for our forms.
Is this the expected behavior with GLPI 10 ?

- GLPI version : 10.0.2
- Form Creator version : 2.13.0

![homepage-v9 5](https://user-images.githubusercontent.com/25508325/187908456-a6770122-dfdc-4e5f-b538-913649a7e704.png)
![homepage-v10](https://user-images.githubusercontent.com/25508325/187908450-ae2f454d-bac1-4cd0-9d78-19ce5fe2147d.png)
![form-settings](https://user-images.githubusercontent.com/25508325/187908454-5990e82a-3717-4b6c-946a-d0337d4f62bc.png)

**Comment by btry** [comment] 2022-09-01 12:29
Hi

> even though the option is still available in the form settings and active for our forms.

The option is the one you highlighted in the 3rd screenshot ?

I notice that the self service interface is not using the service catalog. Check in the entity, tab Forms the setting **Helpdesk mode**

![image](https://user-images.githubusercontent.com/14139801/187913902-4c459591-fdca-4e27-9ba3-0ddca34c4bf2.png)

**Comment by tlaugier** [comment] 2022-09-01 12:39
> The option is the one you highlighted in the 3rd screenshot ?
Yes

I switched the helpdesk mode to "Service catalog extended" and indeed the forms appear on the homepage, but this modifies a lot more of the layout than we would want.
Is there a way we could have the forms on the homepage but be able to keep the "GLPI's helpdesk" mode ?
I just checked on our current 9.5 instance and this is the mode we are in (GLPI's helpdesk).

**Comment by btry** [comment] 2022-09-01 12:49
On this screenshot I see you're using the simplified interface. What if you click the "Forms" menu entry on the left ?


![image](https://user-images.githubusercontent.com/14139801/187917584-53165c10-7e9b-47b4-97f2-8a60284e5817.png)

**Comment by btry** [comment] 2022-09-01 12:53
I'm comparing a GLPI 9.5 and a GLPI 10. I found the difference; I need to check how it was implemented.

**Comment by btry** [comment] 2022-09-02 07:21
Hi

Please test the fix above.

**Comment by tlaugier** [comment] 2022-09-02 08:45
Hi,
How should I proceed to test the fix ? Do I need to replace the current plugin with the git repo and pull down the fix manually ?

**Comment by btry** [comment] 2022-09-02 09:11
Hi

Here is a build with the latest bugfixes and the patch for this issue. Run it on a testing environment only.

[glpi_formcreator_2.13.0-dev.zip](https://github.com/pluginsGLPI/formcreator/files/9476633/glpi_formcreator_2.13.0-dev.zip)

**Comment by tlaugier** [comment] 2022-09-02 09:24
Thanks I'll try to test this today

**Comment by tlaugier** [comment] 2022-09-02 12:27
I've installed the new version but I do not see any change on the homepage for the self-service profile.
Here are the steps I took :

- Go to Configuration > Plugins and uninstall Form Creator
- On the server, remove the formcreator directory from the plugins directory
- Unzip the new version in the plugins directory
- Go to Configuration > Plugins, install Form Creator and enable it
- Create a test form with the "Direct access on homepage" option to Yes

**Comment by btry** [comment] 2022-09-02 12:28
Do you have a copy of Formcreator in the marketplace/ directory ?

**Comment by tlaugier** [comment] 2022-09-02 12:38
No, should I ?

**Comment by btry** [comment] 2022-09-02 12:43
No, you should not. I see frequently cases where a patch does nothing because of a duplicate of the plugin. 

Configure your test form to "all languages"  ensure you set the good access type and check you're trying to virw it from the good entity.

**Comment by tlaugier** [comment] 2022-09-02 12:47
Languages and access type are ok, I can access the form directly via the url or via the Forms menu on the left of the screen, but I do not have a forms list directly on the homepage. The homepage is still identical to the first screenshot I posted.

**Comment by btry** [comment] 2022-09-02 13:05
If there is no form available for the hompage you should at least see an area which says "no form available".

Do you have it ?
![image](https://user-images.githubusercontent.com/14139801/188152129-023666d6-5329-489d-a9a4-49d77b825d46.png)

**Comment by tlaugier** [comment] 2022-09-02 13:09
Ok it's working (freaking browser cache...)
![image](https://user-images.githubusercontent.com/25508325/188152717-e5e6f37c-1f85-42a5-84e0-aad060f5df8e.png)

It does not really fit the new GLPI style but the information is here and that is the essential part !
Thanks @btry

**Comment by btry** [comment] 2022-09-02 13:32
Yes, the design is still the old one. I don't have enough time to go further; and from what I checked I think an improvement in GLPI  is required to have a better visual consistency. Actually I restored the feature using a legacy place provided by GLPI for retrocompatibility.

**Comment by btry** [comment] 2022-09-02 13:33
As the feature works, I merge the fix; I'll fix the UI later.

Thank you for your feedback.

**Closed by btry** 2022-09-02 13:33 UTC
Labels: bug, need feedback
