### ISSUE TITLE
Paste a screenshot in the rich text area

### ISSUE THREAD

**Issue by castorsenior** [pluginsGLPI/formcreator#1073] opened 2018-08-21 10:15 UTC
Hello, Is it possible to paste a screenshot or an image in the rich text area of Formcreator ? I'm trying to do this, but the image is broken when you open the ticket after having saved it : 
![image](https://user-images.githubusercontent.com/12443836/44395916-a2560500-a53b-11e8-821f-63b718de1b7f.png)
Thank you for your attention and your help

**Comment by klodnitsky** [comment] 2018-08-21 17:38
The same problem.

If I paste an image, then i get something like this:
![image](https://user-images.githubusercontent.com/7794575/44418743-e53acb80-a581-11e8-880c-2ee421f62501.png)

Or if using button add an image with a link, then:
![image](https://user-images.githubusercontent.com/7794575/44418838-2206c280-a582-11e8-8c9f-403989b5ae49.png)

**Comment by btry** [comment] 2018-08-22 08:30
Hi

Good point !

As far as I know noone tried this. I'll investigate for the release 2.7.0. I assume I'll reproduce easily.

**Comment by klodnitsky** [comment] 2019-01-17 06:00
Hi.

I'm trying to test this issue with 2.7.0.-beta3 version, and now it looks like:

1) Pasting screenshot - is ok
2) Inserting with link - is ok
3) using drag&drop - nok

Now this issue is only with images when we use drag&drop :)

**Comment by btry** [comment] 2019-01-17 09:18
Hi : no solution yet for drag-drop. There are technical constraints to solve at several places. It is unfortunately not possible to disable the support of drag and drop.

As the release of 2.7.0 is awaited for long, it is safer to postpone this issue for later.

**Comment by NeyRamon** [comment] 2019-02-28 00:19
any news on this topic?

**Comment by btry** [comment] 2019-02-28 08:10
Hi

No news for now. Please be patient.

**Comment by btry** [comment] 2020-07-31 07:15
Hi

The plugin now supports pasting images in the textarea of a question. Some related issues still exists when running Formcreator on GLPI 9.4; and should work fine with GLPI 9.5. I close this issue. 

If you still find problems with latest versions, please create a new ticket.

**Closed by btry** 2020-07-31 07:15 UTC
Labels: bug
