### ISSUE TITLE
Business rules for tickets do not launch when use formcreator

### ISSUE THREAD

**Issue by grcmec** [pluginsGLPI/formcreator#694] opened 2017-08-10 12:38 UTC
Hi.

I have create a new form, when a self service user cereate a new request ticktet ussing this form, the business rule new launch.

Actually we use the GLPI 9.1.6 with Form 2.5.2

The business rule basically read the description filled by the form, ussing the checkbox question in witch the user can select more than one option.

This is an example of the selección:

12) Datos a Certificar : **Modelo del vehículo**

With this information, the business rule launch the automatic asignation to the technician user, this depend of the selection of the self service user.

I am be sure that the business rules never start when the ticket request is created, when I modify or only save the tickted created, the business rule work without problem.

[export_formcreator_20170810_0737.zip](https://github.com/pluginsGLPI/formcreator/files/1214899/export_formcreator_20170810_0737.zip)

I appreciate you help.

**Comment by btry** [comment] 2017-08-10 12:58
Hi

It seems to duplicate #678, but I did not reproduced the issue. I'll try with your use case. Maybe it will help.

**Comment by grcmec** [comment] 2017-08-10 13:05
If you can see the error, I have published the server.

**Comment by btry** [comment] 2017-08-10 13:08
Stay tuned until I try your example and feedback. Likeny next week.

**Comment by grcmec** [comment] 2017-08-21 22:55
Did you have any news?

**Comment by btry** [comment] 2017-09-07 14:49
Hi

Not yet: I was too busy on other things for this plugin.

**Comment by btry** [comment] 2017-09-29 09:48
probably duplicate of #678

**Comment by grcmec** [comment] 2017-09-29 12:42
Hi

I would like to notify you that I finded the error, and now it was solved.

The error is related with space in the evaluation, when the GLPI Business Rule evaluate the description of the form, the space betwwen the words, introduce a unrecogniced character.

I change the evaluation word with a code, no the word and al lworks fine.

**Comment by btry** [comment] 2017-09-29 12:50
Hi

Thank you for your feedback. Can you show an example to reproduce and avoid the need to workaround ?

**Comment by btry** [comment] 2017-09-29 13:25
Oh ! nevermind, you already gave an example in your first message. Sorry.

**Comment by btry** [comment] 2017-09-29 14:07
I'll try to fix this for the release 2.6.0 as the bug is confirmed elsewhere and I expect to reproduce myself easily.

**Comment by btry** [comment] 2017-10-09 14:42
Hi

I downloaded your form, simplified it to fill only the field **Datos a Certificar**, and created a rule similar to yours to reproduce (GLPI 9.1.6 + Formcreator 2.5.2).

I don't reproduce your issue unless I'm using rich text mode for tickets. Do you confirm you're also using it ?

**Comment by btry** [comment] 2017-10-09 16:04
Hi

After extensive tests it seels the problem is already solved in 2.6.0 (branch develop as of today).

I found the issue is not spaces characters but accented characters. With 2.5.2 if you remove accented characters in the rendered ticket and rules the rules engine should work as you expected.

I would really appreciate your feedback to ensure I found the bug you're experiencing.

**Comment by btry** [comment] 2017-11-15 09:08
Hi 

No feedback; then I close. If the issue still ocurs, please open a new ticket

**Closed by btry** 2017-11-15 09:08 UTC
Labels: bug, duplicate, need feedback
