### ISSUE TITLE
Email notification request

### ISSUE THREAD

**Issue by gotanbl** [pluginsGLPI/formcreator#456] opened 2017-01-27 14:17 UTC
Hello, 
After user validate request from form, requester/administrator receive three mails from server.
First is that ticket is created, second update of ticket with user that the ticket is assigned and third mail for update for assigned item from answers with name of form.
Is possible that user/administrator receive one mail with all information?
Thanks

**Comment by btry** [comment] 2017-01-27 14:18
Hi

Please tell the version of GLPI and the plugin

**Comment by gotanbl** [comment] 2017-01-27 14:34
I have formcreator 0.90-1.4-beta7 with glpi 9.1.1.

**Comment by btry** [comment] 2017-01-27 14:36
The problem should disappear if you upgrade to GLPI 9.1.2.

by the way, FormCreator 0+90-1.4 is now FormCreator 2.4.0.

**Comment by gotanbl** [comment] 2017-01-30 09:53
I don't know where to download FormCreator 2.4.0. Is it release?
Is it master branch?
With 0.90-1.4-beta7 and glpi 9.1.2 administrator received 2 mails, one for new ticket and one for update with associate items with name of form. Requester and user who is assigned to ticket did not receive any mails (email follow up set to NO).

**Comment by btry** [comment] 2017-01-30 10:06
This is the master branch. 

Because a very old version of Formcreator was 1.8.1, we must ensure the current versions are greater. 0.90-1.4beta was renamed to 2.4.0 to fix this issue.

If you got issues with emails notifications, please open an other ticket.

**Comment by btry** [comment] 2017-01-30 10:11
If a user has email followup set to **NO** then the plugin should not send any notification to him.

**Comment by gotanbl** [comment] 2017-01-30 10:26
![screenshot at 2017-01-30 11-22-07](https://cloud.githubusercontent.com/assets/24296903/22419666/d6066e02-e6de-11e6-8671-cc007bab287a.png)
These are my settings in form!

**Comment by gotanbl** [comment] 2017-01-30 10:29
I installed master branch, and result is as above! 
Administrator received two emails, requester and user assigned to did not receive mails!
In form setting is Email follow up to YES, but in ticket is set to NO!

**Comment by btry** [comment] 2017-01-30 14:02
Hi

This fix should solve your problem. Can you validate it please ?
https://github.com/btry/formcreator/tree/feature/email_notification_review

Also, I guess this issue is a duplicate of #448.

**Comment by giroli** [comment] 2017-01-30 14:30
Work fine for me too. Glpi 9.1.2  and formcreator 2.4.0. Thank you :)
Warning : I lost my form during the upgrade.

**Comment by btry** [comment] 2017-01-30 14:34
You should not loose any form. Can you provide more details about that ?

**Comment by gotanbl** [comment] 2017-01-30 14:34
Yes, issue is duplicated!
I confirm that Email Followup now works as expected!
Can you confirm me that normal behavior is that requester and assign to user receive two emails, first with header "New ticket ..." and second with "Update of ticket..." during creation of ticket?

**Comment by gotanbl** [comment] 2017-01-30 14:34
I dont loose my form created before upgrade!

**Comment by btry** [comment] 2017-01-30 14:38
Then what did you mean with the following ?

> Warning : I lost my form during the upgrade.

**Comment by giroli** [comment] 2017-01-30 14:41
I had only one form. After updating GLPI 9.1.1/formcreator 0.90-1.3.4 to GLPI 9.1.2/Formcreator 2.4.0, no more form...
How can I help you with this?

**Comment by btry** [comment] 2017-01-30 14:52
Please describe how you installed the pached version. Maybe you uninstalled the plugin to reinstall with the patched version. I don't see an other scenario.

**Comment by giroli** [comment] 2017-01-30 14:58
Probably what I did

**Comment by btry** [comment] 2017-01-30 15:04
Ok, then this is not an upgrade issue; I can close.

Thank you for your feedbacks.

**Closed by btry** 2017-01-30 15:04 UTC
Labels: bug

**Comment by btry** [comment] 2017-01-30 15:25
About this question :

> Can you confirm me that normal behavior is that requester and assign to user receive two emails, first with header "New ticket ..." and second with "Update of ticket..." during creation of ticket?

I think this double notification is useless. In my tries to fix the email followup issues today I did not observed this This is something I attempted to avoid several month ago, and  I submitted a patch to GLPI for this, It is in GLPI 9.1.2 release.

**Comment by gotanbl** [comment] 2017-01-30 15:40
So,do you look at this?
Do you need more tweak to avoid this?
Thanks for follow up fix!

**Comment by btry** [comment] 2017-01-30 15:48
I'll check that while working on 2.5.0 : some work requires I check again some aspects of notifications.

2.4.0 must be released quickly, then fixes will be for 2.4.1 and 2.5.0.
