### ISSUE TITLE
Wont list objects Documents in field (GLPI Object) in Plugin Form

### ISSUE THREAD

**Issue by derry43** [pluginsGLPI/formcreator#1946] opened 2020-09-22 10:51 UTC
Plugin: formcreator, GLPI Version: 9.4.5, Plugin Version: 2.10.2

Summary: Question of type **GLPI object**, where the **GLPI object** is selected as **Documents** does not allow the selection of any documents (except in **Default values**).

I am trying to create a form for a document approval process and want to select the document which needs to be approved from within the form.

I created a question in the form as per image below and **Default values** fields does indeed correctly list the available documents.

![image](https://user-images.githubusercontent.com/47180698/93872797-99aafc80-fcc8-11ea-90ff-a49472c8b75c.png)

However form **Preview** (and actual form) does not list or allow the selection of any documents (even although the user/profile has access to and can browse the documents fine). The form **Preview** and actual form does allow selection of the document **Heading** but does not list any of the documents that sit under the selected 

![image](https://user-images.githubusercontent.com/47180698/93873171-28b81480-fcc9-11ea-8d8e-f250c1de8eea.png)

**Comment by derry43** [comment] 2020-10-06 14:07
I believe that this issue is related to the **`entity_restrict`** parameter as generated in the requests to **`getDropdownValue.php`** from **formcreator** forms when using a field of type **GLPI object**, where the **GLPI object** is selected as **Documents**

Using Firefox Web Developer tools to look at problem requests to **`getDropdownValue.php`** from the **formcreator** plugin, the Request payload is:

`itemtype=Document&display_emptychoice=1&emptylabel=-----&condition=2a92022b7268820dcbb80444900982bcfdd670b5&entity_restrict=1&permit_select_parent=0&page_limit=100&page=1`

and the corresponding "empty" Response payload is:

`{"results":[{"id":0,"text":"-----"}],"count":0}`

If I use the tools to edit and re-submit the request to **`getDropdownValue.php`** so that the **`entity_restrict`** parameter is 0 rather than 1 i.e. the parameter is **`entity_restrict=0`** and the Request payload is:

`itemtype=Document&display_emptychoice=1&emptylabel=-----&condition=2a92022b7268820dcbb80444900982bcfdd670b5&entity_restrict=0&permit_select_parent=0&page_limit=100&page=1`

then the corresponding Response payload is correct and looks like this:

`{"results":[{"id":0,"text":"-----"},{"text":"My Root Entity","children":[{"id":"21","text":"Diagram 1","title":"Diagram 1 - "},{"id":"27","text":"Document 1.docx","title":"Document 1.docx"},{"id":"28","text":"Document 2.pdf","title":"Document 2.pdf"}]}],"count":3}`

Not sure how or where the **`entity_restrict`** parameter is set within **formcreator** but if anyone can tell me how to fix, I am happy to try.

One further thing which I noticed was that the immediately preceding requests to **`dropdownRubDocument.php`** appear to have a possibly incorrect or malformed parameter/value for entity. The Request payload for the **`dropdownRubDocument.php`** request which immediately preceded the above **`getDropdownValue.php`** requests was:

`rubdoc=2&entity%5B%5D=0&rand=93261446&myname=formcreator_field_3`

where the entity parameter is defined as **`entity[]=0`**, whereas similar requests to  **`dropdownRubDocument.php`** from other areas of GLPI form the same parameter as **`entity=0`**. This did not appear to cause any issues with the request, but may cause issues further down the line.

**Comment by derry43** [comment] 2020-10-06 14:19
Actually it appears that it is the last piece of my previous comment that is the root cause of the issue.  The malformed entity parameter in the request to **`dropdownRubDocument.php`** is what defines the entity_restrict parameter for the subsequent request to **`getDropdownValue.php`**.

So the entity parameter passed as **`entity[]=0`** rather **`entity=0`** is what seems to cause the issue. This malformed parameter appears to set the entity_restrict parameter to **`entity_restrict=0`** for the subsequent request to **`getDropdownValue.php`**. 

Again, not sure how to fix, but believe this to be the root cause.

**Comment by derry43** [comment] 2020-10-06 17:19
Found where the **`entity`** parameter is set i.e. in the **`displayField()`** function of `formcreator/inc/fields/dropdownfield.class.php`.

As a test, I replaced the code:

```
           $dparams = ['name'     => $fieldName,
                        'value'    => $this->value,
                        'comments' => false,
                        'entity'   => $_SESSION['glpiactiveentities'],
                        'displaywith' => ['id'],
                        'rand'     => $rand];
```

with

```
            $dparams = ['name'     => $fieldName,
                        'value'    => $this->value,
                        'comments' => false,
                        'entity'   => 0,
                        'displaywith' => ['id'],
                        'rand'     => $rand];
```

and this did indeed generate the correct dropdown contents. Now I just need to understand why the session variable **`$_SESSION['glpiactiveentities']`** appears to be incorrect.

**Comment by btry** [comment] 2020-10-06 18:46
Hi

I'm not in front of the code right now. If I remember well the var glpiactive_entities is an array, and the parameter probably expects an integer.

Enable debug mode in GLPI and read the session cars in the bottom of any page. Use ctrl+F to find in the session a key containing the current entity ID. Probably glpiactive_entity (singular). This is maybe the solution.

However, I did not get any bug feedback with other itemtypes for this type of question. We need a double check to avoid a regression.

By the way, nice job !

**Comment by btry** [comment] 2020-10-07 07:48
Hi 

baased on your research, I created a fix. Can you test it ?

The fix uses the current entity of the user, instead àf 0 (which may not exist, and if it exists may disclose items out of the allowed scope for the user )

**Comment by derry43** [comment] 2020-10-07 08:38
Funnily enough I had just figured that change out earlier this morning and came up with the same solution. That works great thanks.

**Comment by btry** [comment] 2020-10-19 11:17
Reopened due to #1979

**Comment by btry** [comment] 2020-10-20 08:33
Hi

This issue is reopened : the fix causes a regression. I'l searching for an other solution. It appears that the problem is caused by a fix un GLPI, or because GLPI does not allows a set of entities to restrict the documents available un a dropdown.

glpi/ajax/dropdownRubDocument.php

![image](https://user-images.githubusercontent.com/14139801/96561318-b33b6600-12bf-11eb-89be-552dc03d8ccc.png)

**Comment by btry** [comment] 2020-10-20 12:43
@derry43 

Hi

The fix for this isse causes a regression. Could you cancel the parch (see commit https://github.com/pluginsGLPI/formcreator/commit/9f4b1addaaa39095a4a1ebcff5e64a579676bd20) and try the other attempt #1981 instead ?

**Comment by btry** [comment] 2020-10-26 09:47
Hi 

Having no feedback, I merged the new patch.

**Closed by btry** 2020-10-26 09:47 UTC
