### ISSUE TITLE
Can't search in a form description

### ISSUE THREAD

**Issue by usrqmor** [pluginsGLPI/formcreator#1593] opened 2019-12-27 09:39 UTC
Hello,

I'm trying to filter my ticket based on form. I've some informations in the description wich I would like to filter.

For exemple : I try to search in the description "Téléphone de bureau : oui" but the result are blank.

I see an issue about a bug with the search engine #1280  but my problem's still here.

I try on a GLPI 9.4.5 with formcreator 2.9.0 and GLPI 9.4.2 with formcreator 2.8.2, same issue on both.

Regards

**Comment by btry** [comment] 2019-12-27 10:23
Hi

I guess there is a problem with rich text mode and your search.

If you search for "bureau" only, do your search give the expected result ? (all tickets having this word) ?

**Comment by usrqmor** [comment] 2019-12-27 10:35
Hi @btry , 

Thanks for your help. I get the expected result when I search with "bureau".
I know there is an option to activate the rich text by default, but I don't remember where.

**Comment by btry** [comment] 2019-12-27 10:40
It does not exist anymore because this was a source of bugs. Starting from 9.4 at lease (I don't remember exactly the version) simple text mode was removed.

Then the problem is that the trinc you're searching for does not exists because of some HTML tag (I still guess).

Have a look in your DB.

I think this would be a good idea to strip HTML  tags in the search engine of GLPI.

**Comment by usrqmor** [comment] 2019-12-27 10:58
It's exactly like you say. The HTML tag are present in the content.
Can you help me to strip the HTML tag if it's possible ?

I see in the code from html.class.php a part that strip some HTML tags, but I don't know if it's file or another to modify.

Thanks

**Comment by btry** [comment] 2019-12-27 11:04
No : I can't work on that for now. If this is considered as a bug the fix will probably be a change in search.class.php and this is a veeeeery sensitive part of GLPI. Any change may break something elsewhere :)

I think you may workaround by including the HTML tags in your searched string.

I'll open an issue in GLPI repo in january (maybe before), and probably search the fix. 

If you try to workaround as described above, please share your result. This will be usefeul to determine if this is indeed a bug in GLPI or not.

**Comment by usrqmor** [comment] 2019-12-27 11:09
Thanks for the help ! 
I'll try to work with the HTML tags in my search filter and see what happened. 
I won't forget to share the result if it can help you.

From my first tests, I get this in my DB : 
> 17) Téléphone de bureau : &lt;/b&gt;Non&lt;/div&gt;&lt;div&gt;&lt;b&gt;

I get this on GLPI : 
> 17) Téléphone de bureau : </b>Non</div><div><b>

But there's no result so I must do more test.

**Comment by btry** [comment] 2019-12-27 15:31
the difference betwee nyour screenshots is normal.

HTML tags are encoded in the DB and decoded for display.

Then try to replace < and > with ```&lt;``` and ```&gt;``` respectively

**Comment by usrqmor** [comment] 2019-12-31 13:31
Hi btry,

I try to replace but it's doesn't change the result. I found something interesting, but I don't know if it can help you. 
I add the "Commentary" filter in my search. I select the commentary then open the code source of the selected part.
I copy "17) Téléphone de bureau : Non" from the code page in the search field and when I reload the search. I got the ticket from wich I copy the selected part.
![image](https://user-images.githubusercontent.com/17316903/71623044-18f81d80-2bda-11ea-8f70-91357186cf80.png)
But there's no other ticket in my result. So I don't know how the search is blocked.
![image](https://user-images.githubusercontent.com/17316903/71623057-290ffd00-2bda-11ea-94c4-ab8bb1e436bb.png)

**Comment by btry** [comment] 2020-01-06 12:46
Hi

You may enable  the debug mode in GLPI then view the list of sql queries of the page. Search in the page for "Téléphone de bureau". You should find easily the SQL query containing it. The query should be big.

Check the look of the remaining of the searched string. It may contain some useful clue to understand how the text is pasted in the field of the search engine.

**Comment by btry** [comment] 2020-01-15 10:15
Hi

Is your problem solved ? Can I close this issue ?

**Comment by usrqmor** [comment] 2020-01-15 10:47
Hi,
I'm sorry for the late reply. I retried and the result are troubling. I didn't get the same result as my previous post. 
I think I maybe do a false manipulation. I retry and I checked the SQL query and didn't see anything more than in my search. 
![image](https://user-images.githubusercontent.com/17316903/72427711-a451e100-378c-11ea-98de-cca3717afac8.png)
> (`glpi_tickets`.`content` LIKE '%recrutement%' )) AND (`glpi_tickets`.`content` LIKE '%Téléphone de bureau%' )

**Comment by usrqmor** [comment] 2020-01-15 10:54
Hi,
I'm sorry for the late reply; I retried but my result are different from my previous post. I did'nt get any result with the same search parameters and with the same method to to select the parameter.

I checked the SQL Query but it doesn't help me. It's the same thing as my search : 
![image](https://user-images.githubusercontent.com/17316903/72428099-5093c780-378d-11ea-8d99-b7b5066e9aca.png)
>(`glpi_tickets`.`content` LIKE '%recrutement%' )) AND (`glpi_tickets`.`content` LIKE '%Téléphone de bureau : Oui%' )

Try with the SQL description from a query on the DB. 
![image](https://user-images.githubusercontent.com/17316903/72428305-a8cac980-378d-11ea-8328-b467aaeebb1c.png)

> (`glpi_tickets`.`content` LIKE '%recrutement%' )) AND (`glpi_tickets`.`content` LIKE '%Téléphone de bureau : </strong>Oui</div><div><strong>%' )

**Comment by usrqmor** [comment] 2020-02-06 15:27
Hi @btry ,

I've found a solution for my problem. In the destination tab and in the ticket format, there's the part "Description" with the default ##FULLFORM##
![image](https://user-images.githubusercontent.com/17316903/73950840-e938e580-48fc-11ea-8fc6-3d7871929af9.png)

During some test about another subject, I discover that if you don't use ##FULLFORM## in the description but the ##question## and the ##answer##, there is no shaping for the text.
So when you use the search engine in the ticket, the filters work like I wanted.

You can close the issue if you don't need another feedback.

Thanks for your help !

**Closed** 2020-02-19 09:46 UTC
Labels: bug, need feedback
