### ISSUE TITLE
Export / Import form

### ISSUE THREAD

**Issue by dgsn** [pluginsGLPI/formcreator#1647] opened 2020-01-31 09:34 UTC
**Describe the bug**
Error on Function IMPORT

**To Reproduce**
1. Go to Import forms
2. Choose a file
3. Click "Envoyer"
4. erreur : UUID or ID is mandatory

**Screenshots**
![image](https://user-images.githubusercontent.com/13901274/73527923-2cceb380-4414-11ea-8884-2bc7ced00093.png)

**Desktop (please complete the following information):**
Windows Server 2012 R2 Standard Edition
Apache/2.4.16 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.1p PHP/5.6.11 (Apache/2.4.16 (Win32) mod_authnz_sspi/0.1.0
OpenSSL/1.0.1p PHP/5.6.11 Server at 
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
**Additional context**
GLPI 9.4.5
formcreator          Name: Form Creator                   Version: 2.9.1      State: Enabled

**Comment by benshoes** [comment] 2020-01-31 10:18
+1

**Comment by btry** [comment] 2020-01-31 10:42
Hi

Check the version of Formcreator ised to generate the export. Export / import across different version of the plugin is not supported (because of schema changes).

I need a example form to reproduce the issue. Could you check if the issue occurs when a question or a section contains a condition ?

**Comment by dgsn** [comment] 2020-01-31 10:58
Same version.
see attached file.
[export_formcreator_20200131_1016.zip](https://github.com/pluginsGLPI/formcreator/files/4138929/export_formcreator_20200131_1016.zip)

A lot of question contains conditions and any section.

**Comment by btry** [comment] 2020-03-17 10:04
Hi

I did some fixes recently in the branch support/2.9.0 related to this type of errors.

I think that at least some of them are fixed. Your feedback is appreciated.

**Comment by btry** [comment] 2020-08-20 09:55
Hi

Many improbemetns were done in the latest versions of Formcreator to fix export / impot issues. I close this ticket as it is obsolete. Feel free to open a new one if the issue still occurs with the latest version.

**Closed by btry** 2020-08-20 09:55 UTC
Labels: bug, need feedback
