### ISSUE TITLE
Formcreator with error in PHP 7.4

### ISSUE THREAD

**Issue by GabrielMeta** [pluginsGLPI/formcreator#2555] opened 2022-01-28 16:33 UTC
**Describe the bug**
We updated PHP to version 7.4 and Formcreator (version 2.12.4) started to crash when editing questions, targets, preview and access types.
We tried to downgrade PHP, but GLPI does not "accept" the downgrade and stops working.

**To Reproduce**
1. Go to Administration
2. Click on Forms
3. Open a Form
4. In left bar, click on questions, targets, preview or access types.
5. See error

**Expected behavior**
I was hoping to be able to create the form normally and edit it.

**Screenshots**
Error Form:
![image](https://user-images.githubusercontent.com/98606031/151585172-925a97a8-5202-4dd6-804a-29cff4eed231.png)

Error on downgrade PHP:
![image](https://user-images.githubusercontent.com/98606031/151585283-43c7ed71-7174-4ceb-8cd2-1a0f8e105676.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 9.5.6
- list of all plugins (available in GLPI > Setup > General > tab System > bottom of the page)
![image](https://user-images.githubusercontent.com/98606031/151584826-864258c8-c360-4f6e-b433-a02455812de5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser Microsoft Edge or Google Chrome
 - Edge Version 97.0.1072.76 and Google Chrome version 97.0.4692.99

**Comment by btry** [comment] 2022-01-28 21:25
Hi

Try to disable all plugins but Formcreator, and try again to acces questions tag of this form.

**Comment by GabrielMeta** [comment] 2022-01-31 13:07
Hi @btry,

Same Behavior.

Forms:
![image](https://user-images.githubusercontent.com/98606031/151798660-061d6770-84a1-49b0-ace9-f74e268d644b.png)

Plugins:
![image](https://user-images.githubusercontent.com/98606031/151798675-ff060fd8-922f-4ab6-aa60-2add69aedd84.png)

**Comment by btry** [comment] 2022-01-31 13:46
Hi

I believe there is an alteration in some file. The backtrace does not give any valuable  clue about the error.

How did you isntall the plugin ? from the marketplace of from the tar.bz archive provided here in the releases list ?

**Comment by GabrielMeta** [comment] 2022-01-31 16:47
![image](https://user-images.githubusercontent.com/98606031/151836091-bb183a0e-2cbc-48a8-b501-5000d704aac4.png)

This is "autoload.function.php" line 350 in my FTP.
![image](https://user-images.githubusercontent.com/98606031/151836223-250ffcc3-01e9-4c5c-a834-ce87bce3892b.png)

**Comment by btry** [comment] 2022-01-31 17:17
It is quite clear that the error is not in the line you pointed. However, the previous instruction included a file. I believe that this file contains something wrong, maybe impacting the interpretation of the autoload.function.php file. As Formcreator 2.12.4 is used in a lot of GLPI installations, if the source of your bug is in the official archive, it would trigger for sure on every instance of GLPI using it. I also used PHP 7.4 to check access questions of a form, without problem.

As I never saw such feedback, I think that something altered a file. Maybe inc/question.class.php.

I would suggest that you compute the MD5 hash of each file of the plugin in your instance, and compare their hash against a local copy of the plugin, locally. I would recommend to download again the archive to ensure your local copy is not corrupted.

You may also try to remove the plugin from GLPI and deploy it again from a re-downloaded archive.

Unfortunately, I can't help much as there is no evidence about the place to search, and I can't access your instance (professional support required).

**Comment by GabrielMeta** [comment] 2022-02-02 01:03
Hi @btry 

I performed the following test, as our GLPI was at version 9.5.6, I ended up updating to 9.5.7 in order to solve the problem, since all files would be rewritten.

I uninstalled and installed formcreator as well, but none of the actions solved the problem.

I'm afraid the problem is in the database, could you help me?

**Comment by btry** [comment] 2022-02-02 07:35
Hi

I don't think the problem is in the database. 

Create a fresh GLPI instance 9.5.7 + Formcreator 2.12.4, with an empty database.  Lets call this instance **test**, and the instance with your issue **prod**.

On the **test** instance, check if Formcreator works well. If yes, add all plugins you have on the **prod** instance. Check it still works. 

Once done, try to copy the DB from **prod** to **test**. Don't forget to copy the files in the files/ folder but son't copy files/_cache. See if it still works.

Also, have a look on the forum, maybe there is a topic for similar problem: https://forum.glpi-project.org/

**Comment by btry** [comment] 2022-02-15 13:48
Hi

Do you have feedback about your issue ?

**Comment by btry** [comment] 2022-02-16 07:38
Hi

Ok, great ! then I close this issue. 

Thank you for your feedback.

**Closed by btry** 2022-02-16 07:38 UTC
