### ISSUE TITLE
Dropdown selections not appearing in ticket

### ISSUE THREAD

**Issue by grego1981** [pluginsGLPI/formcreator#838] opened 2017-12-06 13:10 UTC
Hi, I have created a form which has 2 dropdown fields of type select. The fields appear with the right values when submitting the form but in the ticket created the selections are blank if the language is not english (I use Greek words).

I use GLPI 9.2 with 2.6.0 version of the plugin

Thank you 

Gregory

**Comment by btry** [comment] 2017-12-06 20:09
Hi

IS this issue a duplicate of #814 ? Do you have ccented chars in t he options of your select field ?

**Comment by grego1981** [comment] 2017-12-07 06:46
Maybe it is the same I cannot read French very well.. In greek it matters not if it accented or not it does it nevertheless but only on the dropdown fields. Maybe it has something to do with encoding?

**Comment by btry** [comment] 2017-12-07 08:16
Hi

Yes, encoding may be related to the issue.

Can you write here in greek the values of your field, and show how it is saved in your DB (phpMyAdmin, HeidiSQL, ...). 

I'll put your text in my instance to run and diagnose. It is possible the fix for #814 will also solve your issue.

**Comment by grego1981** [comment] 2017-12-15 08:10
Sorry for the delay, didn't catch the github email :(
Hello, below are some values in greek which are used in forms dropdown:

Αγορές
Αποθήκη - Ανοξείδωτου
Αποθήκη - Λευκοσιδήρου
Εισαγωγές - Εξαγωγές
Λογιστήριο
Μηχανογράφηση
Παραγωγή - Ανοξείδωτου
Παραγωγή - Λευκοσιδήρου
Πωλήσεις - Ανοξείδωτου
Πωλήσεις - Λευκοσιδήρου


Also can you tell me in short what is the fix in #814  because my french aren't so good as to understand...


Thank you and BR

Gregory

**Comment by grego1981** [comment] 2017-12-15 08:26
As far as I can see some greek fields are saved in this form:
&Alpha;**_ί_**&tau;&eta;&mu;&alpha;&delta;&eta;&mu;&iota;&omicron;&upsilon;&rho;&gamma;**_ί_**&alpha;&simaf; &chi;&rho;**_ή_**&sigma;&tau;&eta;
All cahracters except the one with the accent which appears in greek readable format. The actual word behind this value is "Α**_ί_**τημα Δημιουργ**_ί_**ας χρ**_ή_**στη"

**Comment by btry** [comment] 2017-12-15 08:41
here again, the work in the PR #840 may be a basis to solve this unreadable encoding. This PR affects answers for textarea fields, I'll consider extending its effect to select fields.

**Comment by grego1981** [comment] 2017-12-15 08:48
Do you want me to test with the latest develop branch to help and verify?

**Comment by btry** [comment] 2017-12-15 08:53
If you can, yes, this will be helpful. #840 was merged a few seconds ago, then you can directly test the develop branch.

**Comment by grego1981** [comment] 2017-12-15 09:11
Still same behaviour. No change at all.

**Comment by btry** [comment] 2017-12-15 09:13
Ok, I think I know how to fix this. Stay tuned to test the patch.

**Comment by grego1981** [comment] 2017-12-15 09:15
OK just did another test after saving the dropdown values again (delete them and write them again), now they appear correctly in the database and the form works! Hope it helps!

**Comment by btry** [comment] 2017-12-15 09:17
Indeed, this is helpful. Then one of the fixes in the development already updates the format.

Then I think you can update the format in DB by simply editing the field, not change anything and save.

If you can confirm, then I only need to add an upgrade procedure similar to the one done for textarea fields.

**Comment by grego1981** [comment] 2017-12-15 09:24
For the values in dropdowns it works as you mention but for all the other fields it doesn't Still new forms and questions are saved in the same human unreadable manner.

**Comment by btry** [comment] 2017-12-15 09:30
Then I suggest you open one issue per fieldtype, and prepare yourself to exchange about them. Greek and Russian users are very good to solve this kind of issue because they use non latin characters (making the encoding problems more easy to occur).

**Comment by grego1981** [comment] 2017-12-15 09:35
The problem is that it is not only in the fields I see it across all the tables... In general in all the formcreator tables that have name or description columns on that columns greek appear as html  entities.

**Comment by btry** [comment] 2017-12-15 09:42
if this is in tables forms, sections, questions, the issue is less annoying, because there are less bug reports (these data are mostly saved and displayed only, without complex use like fields and answers).

Anyway, I want to fix them too. If you want to open issues, open one issue per table (aka itemtype) describing each column in the DB contaning encoded values.

**Comment by grego1981** [comment] 2017-12-15 09:49
OK I'll start opening issues then! 

Thank you!

**Comment by btry** [comment] 2018-03-05 08:04
The status of this issue should be reviewed with the future version 2.7.0-dev.

**Comment by btry** [comment] 2018-12-31 15:53
Hi 

I close this issue, all html entities problems are solved. If the bug still occurs with version 2.7.0-beta.1 (develop branch) then open a new one.

**Closed by btry** 2018-12-31 15:53 UTC
Labels: bug
