### ISSUE TITLE
FC  2.12.4 and 2.12.5 : no watcher in target ticket

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2836] opened 2022-06-14 14:57 UTC
**Describe the bug**
no watcher is generated in target ticket.. seems random : (    no pattern found still

**To Reproduce**
![observer2](https://user-images.githubusercontent.com/78594318/173607091-6e208531-72bf-420f-8239-989cc39a5e8c.jpg)

if restriction par entite = formulaire,sometimes i can't have it listed in target ticket ... 
i had to switch to "restriction par entite = utilisateur" to be able to add the target in target ticket . but still, it doesn't work randomly, no watcher in the target ticket.... 
**Expected behavior**

**Screenshots**
![observer](https://user-images.githubusercontent.com/78594318/173607031-0d71dca8-006d-46e7-8376-d25c9b01ec57.jpg)

**GLPI / Plugins (please complete the following information):**
- GLPI version 9.5.7 alls our forms, 3 differents glpi instances same pb  :( 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by btry** [comment] 2022-06-15 13:10
Hi

Is it reproductible with GLPI 10 and version 2.13 ?

Also it may be useful to check the entity if the generated ticket, the entities of the added observers (profiles / entities authorizations). Maybe there are some checks in GLPI core when adding actors and your observers are filtered out because of a entity violation.

**Comment by btry** [comment] 2022-09-02 09:15
Hi

Having no feedback, and version 2.12.x reaching end of life, I close this issue. Feel free to open a new one if this still occurs with 2.13.0 or later.

**Closed by btry** 2022-09-02 09:15 UTC
Labels: need feedback
