### ISSUE TITLE
no rights while validating form

### ISSUE THREAD

**Issue by reinethernal** [pluginsGLPI/formcreator#1531] opened 2019-10-11 08:58 UTC
Trying to approve a form but receive such error. 
![photo_2019-10-11_11-38-45](https://user-images.githubusercontent.com/35932698/66638765-40b09880-ec1e-11e9-9f14-be4f4d1d77b4.jpg)
(yoou have no rights to validate this form)
From super-admin user have no such error.

**Comment by btry** [comment] 2019-10-11 09:02
Hi

This is probably a duplicate of #1480 

Cal you tell the versions of GLPI and the plugin ?

**Comment by reinethernal** [comment] 2019-10-11 09:12
GLPI is 9.4.4 and plugin 2.8.5.
Sure, i have the same proiblem. Sorry for creating new issue.

**Comment by btry** [comment] 2019-10-11 09:13
Do you have a test environment with GLPI 9.4.3 to check the bug still occurs with this older version of GLPI ?

**Comment by reinethernal** [comment] 2019-10-11 09:15
No, sorry. Only production)

**Comment by btry** [comment] 2019-10-15 13:19
Hi

Can you tell how the user is a validator for the form ? Is he added as a user or as a member of a validator group ?

**Comment by reinethernal** [comment] 2019-10-15 13:22
Hi
User added as a member of a validator group.

**Comment by reinethernal** [comment] 2019-10-15 13:28
One more moment. When i try to validate form, i receive such error:

![image](https://user-images.githubusercontent.com/35932698/66835750-c149fe80-ef68-11e9-81cf-c5155ba35e79.png)

**Comment by btry** [comment] 2019-10-15 13:36
OK; I'll try to reproduce that after fixing the possible duplicate.

**Comment by btry** [comment] 2019-10-17 07:18
Hi

Do this fix help ? https://github.com/pluginsGLPI/formcreator/pull/1541

**Comment by reinethernal** [comment] 2019-10-17 07:28
Nope, still the same error - you are not a validator of these answers.

**Comment by btry** [comment] 2019-10-17 09:29
Hi

The fix I submitted solved #1482. Then that issue and your isse are not the same.

I tried to reproduce your issue with Formcreator 2.8.5, without success. In the code, there is a method to check if a user has the right to validate a form answer. It is used to display or not the accept and refuse buttons and to ensure noone tries to workaround them. Then the red popup error should not occur.

I need more information to understand how this can happen on your instance. Can you build a test instance of GLPI with Formcreator and do the minimal (user, group and form creation) to reproduce, then describe how you did it ?

**Comment by reinethernal** [comment] 2019-10-17 09:49
I have 2.9 version of plugin installed.
Rights i have set up for user profiles: 
User has a little less rights than super-admin user

![image](https://user-images.githubusercontent.com/35932698/66997118-849e1480-f0da-11e9-8608-9e16f9fc9546.png)
in english-moderator (first level of support)

User with nearly same rights like self-service post a form, and wait for acceptance.
in english-user
![image](https://user-images.githubusercontent.com/35932698/66997241-c464fc00-f0da-11e9-979a-042411bcb4ce.png)

steps to reproduce:

1. from a user profile submit a form that need to be validated
2. from a moderator profile try to validate form
3. receive error "you are not the validator of these answers".

user with profile "moderator" exist in group with the same name assigned to validate forms.
![image](https://user-images.githubusercontent.com/35932698/66998229-8ff23f80-f0dc-11e9-821a-20c4c76b5ed3.png)

**Comment by btry** [comment] 2019-10-17 11:58
While searching for the validation issues reported, I did some code refactor in the validation checks. Could you update your copy of the plugin to the latest revision of the branch support/2.9.0 then check if the plugin behaves better or not ?

**Comment by reinethernal** [comment] 2019-10-17 12:43
Yes, it helped. But created two tickets for now...

**Comment by reinethernal** [comment] 2019-10-17 12:50
and user that approved is now a requester

**Comment by reinethernal** [comment] 2019-10-17 12:51
Should i create new issue for this?

**Comment by btry** [comment] 2019-10-17 13:05
> and user that approved is now a requester

This might happen if you have several target tickets in the form. Please check it.

> and user that approved is now a requester

There is an old issue about a mess between author and requester of a ticket. This problem is rather close. Can you create an other issue for that ? I'll link it to the other one.

**Comment by reinethernal** [comment] 2019-10-17 13:14
> This might happen if you have several target tickets in the form. Please check it.

Only one, but after update it had blank name

**Comment by reinethernal** [comment] 2019-10-17 13:16
Hmm... i have blank names at all targets in all forms

**Comment by btry** [comment] 2019-10-17 13:20
This is an other issue. If the initial problem of this issue is solved, we can close this one, and handle other issues in their own thread

**Comment by reinethernal** [comment] 2019-10-17 13:20
Ok, i'll post a new one) Thank you)

**Closed** 2019-10-17 13:49 UTC
Labels: bug
