### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#161] opened 2015-12-02 06:51 UTC
Hello, Since monday form creator last release installation after undefined time the session not logged out but stay just tools administration set up menu on glpi. Just log out and comes back to normal. Same for GLPI 0.85.2 and 0.90.1 

I found that in php-errors.log 

  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  inc\ticket.class.php:214                           
  inc\ticket.class.php:1965                          Ticket::canUpdate()
  inc\massiveaction.class.php:570                    Ticket->getSpecificMassiveActions()
  inc\search.class.php:1199                          MassiveAction::getAllMassiveActions()
  inc\search.class.php:92                            Search::displayDatas()
  inc\search.class.php:74                            Search::showList()
  front\ticket.php:52                                Search::show()

Tell me if you need more logs.

**Comment by neeftarah** [comment] 2015-12-08 10:29
Hi,

Thank you for your feedback.
This issue should have been fixed by this commit: 9fdef06

Can you test it and confirm me that the issue is solved ?

Best regards,
Jérémy

**Comment by neeftarah** [comment] 2015-12-17 12:00
Hi,

Can I close this issue? Is your problem resolved?

Best regards,
Jérémy

**Closed** 2015-12-18 08:19 UTC
Labels: bug

**Comment by satyan01** [comment] 2015-12-18 12:33
the issue is solved thx
