### ISSUE TITLE
filter on GLPI Object

### ISSUE THREAD

**Issue by hcimadomo** [pluginsGLPI/formcreator#1910] opened 2020-08-03 07:05 UTC
I need to have a filter for select only computer "en service". Same request for select "active" User.

My request to a new feature is to add filters as in filter search for computer.

Other solution : I see in github same request about computer (show only computers in service, show only active users, etc... So is it more simple to have this specific type ?

Best regards

**Comment by btry** [comment] 2020-08-03 07:51
hi

The best design would be to use the search engine of GLPI to restrict the items. If you consider to sponsor this feature, please contact us at contact@teclib.com .

**Comment by hcimadomo** [comment] 2020-08-03 09:11
hello,
I cant sponsor this.... Can you make a short explanation about how the list is defined in the execution of form ?
BR

**Comment by btry** [comment] 2020-08-03 09:37
The plugin mimics the restrictions in the ticket's form of GLPI in service catalog. It checks the rights "view all hardware", "view my hardware" and "view hardware of my groups".

To satisfy your need, the plugin shall use additional search criteria, like you can find in any list of GLPI. 

If you want to see in deep the implementation the code is in inc/fields/dropdownfield.class.php, method displayField().

**Comment by hcimadomo** [comment] 2021-05-03 12:34
> 
> 
> The plugin mimics the restrictions in the ticket's form of GLPI in service catalog. It checks the rights "view all hardware", "view my hardware" and "view hardware of my groups".
> 
> To satisfy your need, the plugin shall use additional search criteria, like you can find in any list of GLPI.
> 
> If you want to see in deep the implementation the code is in inc/fields/dropdownfield.class.php, method displayField().

Hello,
this method is not more in this class. Where is the code to analyse for implement a filter ?
Best regard

**Comment by btry** [comment] 2021-07-02 07:10
Duplicate of #1274

**Comment by btry** [comment] 2022-09-20 11:19
In progress: https://github.com/pluginsGLPI/formcreator/pull/2978

big up to the sponsor

**Comment by btry** [comment] 2023-04-21 13:29
Hi

The feature will be available in version 2.14.0

**Closed by btry** 2023-04-21 13:29 UTC
Labels: duplicate, feature
