### ISSUE TITLE
Plug-in update GLPI V10.0.0 RC1

### ISSUE THREAD

**Issue by grenona55** [pluginsGLPI/formcreator#2575] opened 2022-02-04 14:59 UTC
Try to update formcreator to latest version.
From GLPI Setup Plug-in, 

Update icon available, click on it
Display Completed in 0 second

But in the GLPI menu, Form choice is not display

In Plug-In still saying Update Avaible

I try to update manualy

Download latest GLPI v10 compatible version
Copy to /glpi/plugins folder

No change

OS: Ubuntu
GLPI: 10.0.0 RC1

**Comment by grenona55** [comment] 2022-02-04 15:05
error when click on UPDATE in GLPI Plug in GUI:



Task Completed. (0 seconds)
Unknown column 'is_dashboard_visible' in 'field list'

**Comment by btry** [comment] 2022-02-04 15:10
Hi

I have a doubt about the way you installed Formcreator. I'm suspecting you installed it from the marketplace. In such case, adding it in the plugins folder will not work. Plugins installed from the marketplace take precedence over a duplicate of the plugin in the plugins folder. Therefore if you download manually the plugin; please put it in the marketplace folder.

Also, when you enable a plugin with the toggle button (see screenshot below), the web page in your browser does not refresh. This prevents new menu items to show. Refresh the page with F5.
![image](https://user-images.githubusercontent.com/14139801/152552464-8678ed38-e71e-45f6-a3ea-42ed27893654.png)


Finally you probably had a previous 2.13.0-alpha release before upgradong th 2.13.0-alpha.3. The column **is_dashboard_visible** was added between thos Alpha releases, then there is nothing to upgrade. This is intentional as this is still a development / testing version.

To fix that, you should force an upgrade of the plugin from 2.12 to 2.13. Use the following command

php bin/console glpi:plugin:install -u glpi -p force-uprgade -f

The missing column should  be created in the BD.

**Comment by stdglpi** [comment] 2022-02-04 17:34
Hello @btry 

I had an error with the column is_dashboard_visible also.
I think I came from 2.13.0-alpha1 to 2.13.0-alpha3.

I follow your advices so I reinstalled all the alpha 1 & 2 I did the command : 

php bin/console glpi:plugin:install -u glpi -p force-uprgade -f

All was ok

I try to pass the last 2.13.0-alpha3 and pass the command again
![image](https://user-images.githubusercontent.com/63521311/152575923-7a6dd88b-d0f1-454e-b0d4-9ee5f26728de.png)

**Comment by grenona55** [comment] 2022-02-04 17:50
Do it and lot of error

***@***.***:/var/www/html/glpi# php bin/console glpi:plugin:install -u glpi -p force-uprgade -f
PHP User Warning (512): plugin_version_glpi-dashboard-1.0.2 method must be defined! in /var/www/html/glpi/src/Plugin.php at line 1564
PHP Warning:  plugin_version_glpi-dashboard-1.0.2 method must be defined! in /var/www/html/glpi/src/Plugin.php on line 1564
PHP User Warning (512): plugin_version_glpi-dashboard-1.0.2 method must be defined! in /var/www/html/glpi/src/Plugin.php at line 1564
PHP Warning:  plugin_version_glpi-dashboard-1.0.2 method must be defined! in /var/www/html/glpi/src/Plugin.php on line 1564
Which plugin(s) do you want to install (comma separated values)?
  [*                 ] All plugins
  [addressing        ] IP Adressing
  [badges            ] Badges
  [barcode           ] Barcode
  [behaviors         ] Behaviours
  [cmdb              ] CMDB
  [databases         ] Databases
  [datainjection     ] Data injection
  [escalade          ] Escalation
  [fields            ] Additional Fields
  [formcreator       ] Form Creator
  [genericobject     ] Objects management
  [geninventorynumber] Inventory number generation
  [glpiinventory     ] GLPI Inventory
  [itilcategorygroups] ItilCategory Groups
  [manageentities    ] Entities portal
  [mreporting        ] More Reporting
  [mydashboard       ] My Dashboard
  [news              ] Alerts
  [satisfaction      ] More satisfaction
  [tag               ] Tag Management
  [useditemsexport   ] Used items export
  [webresources      ] Web Resources
> formcreator
Processing plugin "formcreator"...
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_answers`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_answers`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_categories`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_categories`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_entityconfigs`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_entityconfigs`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_forms`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_forms`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_formanswers`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_formanswers`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_forms_profiles`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_forms_profiles`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_forms_validators`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_forms_validators`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_questions`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_questions`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_conditions`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_conditions`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_sections`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_sections`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targetchanges`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targetchanges`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targettickets`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targettickets`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targetproblems`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targetproblems`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targets_actors`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_targets_actors`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_issues`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_issues`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_items_targettickets`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_items_targettickets`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_questiondependencies`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_questiondependencies`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_questionregexes`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_questionregexes`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_questionranges`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_questionranges`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_forms_languages`.`id`. in /var/www/html/glpi/src/DBmysql.php at line 1980
PHP Warning:  Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_formcreator_forms_languages`.`id`. in /var/www/html/glpi/src/DBmysql.php on line 1980
SQL Error "1054": Unknown column 'is_dashboard_visible' in 'field list' in query "INSERT INTO glpi_plugin_formcreator_entityconfigs                   (id, replace_helpdesk, sort_order, is_kb_separated, is_search_visible, is_dashboard_visible, is_header_visible)                SELECT ent.id,                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 0, -2),                   IF(ent.id = 0, 1, -2),                   IF(ent.id = 0, 0, -2)                 FROM glpi_entities ent                 LEFT JOIN glpi_plugin_formcreator_entityconfigs conf                   ON ent.id = conf.id                 WHERE conf.id IS NULL"
***@***.***:/var/www/html/glpi#

**Comment by grenona55** [comment] 2022-02-04 20:31
Great support sir

Where is that folder (marketplace) to drop the formcreator file

Ubuntu version

**Comment by grenona55** [comment] 2022-02-04 20:42
I put the file now in marketplace,

I still view the update icon over FormCreator ?

No form option in the GLPI Menu also

**Comment by grenona55** [comment] 2022-02-04 20:50
Screenshot

***@***.***

After i click on update
***@***.***


From: Andre Grenon ***@***.***>
Sent: February 4, 2022 3:42 PM
To: pluginsGLPI/formcreator ***@***.***>; pluginsGLPI/formcreator ***@***.***>
Cc: Author ***@***.***>; Andre Grenon ***@***.***>
Subject: RE: [pluginsGLPI/formcreator] Plug-in update GLPI V10.0.0 RC1 (Issue #2575)

I put the file now in marketplace,

I still view the update icon over FormCreator ?

No form option in the GLPI Menu also

**Comment by grenona55** [comment] 2022-02-04 20:57
Forgot my last email

I uninstall and reinstall

Now it OK

Close case


From: Andre Grenon ***@***.***>
Sent: February 4, 2022 3:50 PM
To: Andre Grenon ***@***.***>; pluginsGLPI/formcreator ***@***.***>; pluginsGLPI/formcreator ***@***.***>
Cc: Author ***@***.***>; Andre Grenon ***@***.***>
Subject: RE: [pluginsGLPI/formcreator] Plug-in update GLPI V10.0.0 RC1 (Issue #2575)

Screenshot

***@***.***

After i click on update
***@***.***


From: Andre Grenon ***@***.******@***.***>>
Sent: February 4, 2022 3:42 PM
To: pluginsGLPI/formcreator ***@***.******@***.***>>; pluginsGLPI/formcreator ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>; Andre Grenon ***@***.******@***.***>>
Subject: RE: [pluginsGLPI/formcreator] Plug-in update GLPI V10.0.0 RC1 (Issue #2575)

I put the file now in marketplace,

I still view the update icon over FormCreator ?

No form option in the GLPI Menu also

**Comment by btry** [comment] 2022-02-07 07:05
Hi

thank you for your feedback.

**Closed by btry** 2022-02-07 07:05 UTC
