### ISSUE TITLE
Question type not displaying (support branch 2.10.0)

### ISSUE THREAD

**Issue by fralla2** [pluginsGLPI/formcreator#1752] opened 2020-05-07 14:15 UTC
**Describe the bug**
Hi all,
I've pulled the /support 2.10.0 branch this morning on my test environnement and when creating a new form, I can add questions sections but the questions types are not displaying.

It might be just me or a bug was introduced with one of the patch.....

**To Reproduce**
- Create a new form
- Create a new section
- Click on add a question and give it a title
- Can't choose a question type

**Expected behavior**
Being able to select a question type and enter the question as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/38400135/81304614-4a329f80-904b-11ea-8c70-f864c61ff119.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 80.0.4044.138

**Additional context**
GLPI version 9.4.5
FormCreator 2.10.0-beta.1 (pulled from support 2.10.0 branch this morning)

Thanks
Francois

**Comment by btry** [comment] 2020-05-07 17:55
Hi

Can you check the developer tools of your browser if you get an error 500 when you open the form to create a question ? If yes, please the logs.of your http server. Check also the logs in glpi (php-errors and sql-errors).

**Comment by fralla2** [comment] 2020-05-07 18:20
In the developper tools I only see those 2 errors on all glpi pages so it's probably not related : 
DevTools failed to load SourceMap: Could not load content for http://glpi05.cscv.qc.ca/glpi-test/lib/jqueryplugins/qtip2/jquery.qtip.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://glpi05.cscv.qc.ca/glpi-test/lib/leaflet/plugins/Leaflet.markercluster/leaflet.markercluster.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE


GLPI php-errors.log and sql-errors.log are empty today...

**I get this error in the /var/log/httpd/error_log file each time I click on the "addQuestion" link so it's probablys this :** 

[Thu May 07 14:14:12.384307 2020] [php7:error] [pid 1815] [client MYIP:PORT] PHP Fatal error:  Class PluginFormcreatorRequestTypeField contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (PluginFormcreatorFieldInterface::hasInput) in /var/www/html/glpi-test/plugins/formcreator/inc/fields/requesttypefield.class.php on line 0, referer: http://glpiSERVER/glpi-test/plugins/formcreator/front/form.form.php?id=1

**Comment by btry** [comment] 2020-05-07 18:27
The report in errors.log is relevant. This should be related to a commit I pushed this week and should be easy to fix. I'll submit a fix to you soon

**Comment by fralla2** [comment] 2020-05-07 18:48
Perfect. As soon as it's fixes I'll start back working on the feature request for the GLPI Object filters. I needed a test environment first and wanted to start with the more recent support pull ;)

**Comment by btry** [comment] 2020-05-08 07:38
Hi

I updated the branch with this commit 679c4d98, this should be fixed.

**Comment by fralla2** [comment] 2020-05-08 12:27
Your fix works :) The form nnow let me add questions again.

Don't know if this second error is related to the same commit problem but when displaying or previewing the forms, the questions appears breafly but all get hidden after about a second....

Logs shows the following errors : 

[2020-05-08 08:21:49] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi-test/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: show_rule
  Backtrace :
  plugins/formcreator/inc/fields.class.php:156
  plugins/formcreator/inc/fields.class.php:146       PluginFormcreatorFields::isVisible()
  plugins/formcreator/inc/fields.class.php:157       PluginFormcreatorFields::{closure}()
  plugins/formcreator/inc/fields.class.php:374       PluginFormcreatorFields::isVisible()
  plugins/formcreator/ajax/showfields.php:35         PluginFormcreatorFields::updateVisibility()
  {"user":"1151@glpi05"}
[2020-05-08 08:21:49] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi-test/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: show_rule
  Backtrace :
  plugins/formcreator/inc/fields.class.php:156
  plugins/formcreator/inc/fields.class.php:146       PluginFormcreatorFields::isVisible()
  plugins/formcreator/inc/fields.class.php:157       PluginFormcreatorFields::{closure}()
  plugins/formcreator/inc/fields.class.php:374       PluginFormcreatorFields::isVisible()
  plugins/formcreator/ajax/showfields.php:35         PluginFormcreatorFields::updateVisibility()
  {"user":"1151@glpi05","mem_usage":"0.001\", 3.45Mio)"}
[2020-05-08 08:21:49] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi-test/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: show_rule
  Backtrace :
  plugins/formcreator/inc/fields.class.php:156
  plugins/formcreator/inc/fields.class.php:381       PluginFormcreatorFields::isVisible()
  plugins/formcreator/ajax/showfields.php:35         PluginFormcreatorFields::updateVisibility()
  {"user":"1151@glpi05","mem_usage":"0.002\", 3.45Mio)"}
[2020-05-08 08:21:49] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi-test/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: show_rule
  Backtrace :
  plugins/formcreator/inc/fields.class.php:156
  plugins/formcreator/inc/fields.class.php:381       PluginFormcreatorFields::isVisible()
  plugins/formcreator/ajax/showfields.php:35         PluginFormcreatorFields::updateVisibility()
  {"user":"1151@glpi05","mem_usage":"0.001\", 3.45Mio)"}

**Comment by btry** [comment] 2020-05-08 18:06
I need to check the empty schema for this version. Maybe there is an upgrade problem from an older version. The column show_rule belongs to conditions and the key in arrays comes from the table.

**Comment by btry** [comment] 2020-05-12 10:06
Hi

Check in the table **glpi_plugin_formcreator_formanswers** that the column **show_rule** exists.

**Comment by fralla2** [comment] 2020-05-12 11:56
No it's not present.

![image](https://user-images.githubusercontent.com/38400135/81685363-00b8ca80-9426-11ea-9654-f168466456e7.png)

**Comment by btry** [comment] 2020-05-12 12:06
Oh, sorry !!

I did not pointed you to the good table !

The column must exist in the tables **glpi_plugin_formcreator_sections** and **glpi_plugin_formcreator_questions**

**Comment by fralla2** [comment] 2020-05-12 12:11
It's present on formcreator_questions but missing in the formcreator_sections

![image](https://user-images.githubusercontent.com/38400135/81688999-f13a8100-9427-11ea-88ca-06a4bca6071e.png)

![image](https://user-images.githubusercontent.com/38400135/81689212-14653080-9428-11ea-9dee-a128bb425ca5.png)

**Comment by btry** [comment] 2020-05-12 12:19
Ok,  then I guess your tables match the schema for the version 2.9.x

If you're **not** on a production environment you may try to upgrade the tables with the following command (from the formcreator folder)

php scripts/cliinstall.php --force-upgrade

**Comment by fralla2** [comment] 2020-05-12 12:33
[root@glpi formcreator]# php scripts/cliinstall.php --force-upgrade
Installing Plugin Id: 22 version 2.10.0-beta.1...
Done
Activating Plugin...
Activation Done
Loading Plugin...
Load Done...

Still missing the column....

![image](https://user-images.githubusercontent.com/38400135/81691650-285e6180-942b-11ea-8dd6-a966fa61d31c.png)

**Comment by fralla2** [comment] 2020-05-12 12:34
Should I start fresh (deleting the tables and plugins folder ?

**Comment by btry** [comment] 2020-05-12 12:44
Add manually the column and  don't forget to set the default to '1'.

I checked deeper; the column is added in version 2.9. That's why it was not added with the above command.

![image](https://user-images.githubusercontent.com/14139801/81692687-13032a80-945f-11ea-9e3a-cfcd2a8f1ec6.png)

**Comment by fralla2** [comment] 2020-05-12 13:11
Confirmed working.

Thanks again for your excellent work.

Might want to add a check for this column in the next migration script release... just in case other missed it ;)

**Comment by btry** [comment] 2020-05-12 13:39
The unit tests have checks for upgrade process starting from version 2.5.0. As the tests are successful, the upgrade process should be fine. Remains a risk of failure when upgrading the data from a schema to an other. When this occurs, I discover sometimes that the failure was not handled correctly by the admin and an human error led to a inconsistent DB with missing columns.

Instead of adding a potentially useless and messy check, it is better to investigate how the column may be missing before you upgraded to 2.10. The version 2.10 assumes that the column exists when upgrading from 2.9.0 and focuses only on changes between those 2 versions.

**Comment by fralla2** [comment] 2020-05-12 13:47
Ok no problem ;)

I think I might have been on 2.9 beta something before upgrading... maybe the but came from there. Anyway thanks again for your help. Really appreciated

**Comment by btry** [comment] 2020-05-12 13:50
You're welcome.

As the issue is solved, I can close it.

**Closed by btry** 2020-05-12 13:50 UTC
Labels: bug, need feedback
