### ISSUE TITLE
Cannot access ticket generate from a multiple targets form

### ISSUE THREAD

**Issue by dfper-tjpa** [pluginsGLPI/formcreator#2174] opened 2021-03-15 14:09 UTC
**Describe the bug**
When I answer a multiple targets form, it creates more than 1 ticket and send they to each group. But when I open the form and try to access the ticket, i recive a messege that this item not found

**To Reproduce**
1. With a Admin or other profile that can create a form, create a form with multiple targets (that create more than 1 ticket)
2. With a self service user, answer this form.
3. Go the the my requests lists and find this answer
4. Get the tickets list from this answer and try to open the tickets to get the error

**Expected behavior**
See the ticket generated from the form answered

**Screenshots**
![Screenshot_34](https://user-images.githubusercontent.com/80268312/111166434-d9b7b180-857e-11eb-8d01-2f266c73d087.jpg)
![Screenshot_35](https://user-images.githubusercontent.com/80268312/111166439-da504800-857e-11eb-9055-13b884633ae0.jpg)
![Screenshot_36](https://user-images.githubusercontent.com/80268312/111166440-dae8de80-857e-11eb-8e8e-e58cc894bef8.jpg)
![Screenshot_37](https://user-images.githubusercontent.com/80268312/111166442-dae8de80-857e-11eb-9f6c-3d7fb8f1f08e.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10, Windows 7]
 - Browser [Firefox E.S.R 68.11.0 Chrome 84.0 Edge 89.0.774.45]

GLPI Version 9.5.1, 9.5.3 and 9.5.4
Formcreator Version 2.11.0 and 2.11.2

**Comment by btry** [comment] 2021-03-26 20:22
Hi

I think you may be impacted by the bug fixed in the following commit: b7cad38c229f87c8cadf3a5ddddedc0d15e6dd70

But you say the bug ocurs with Formcreator 2.11.2, which contains the above fix. Please confirm again that you're impacted with Formcreator 2.11.2. If yes, use a testing environment to check if the bug still occurs with the latest revision of the branch support/2.11.0.

If the bug still occurs with the latest revision, please describe the entity tree if your instance, where are the form, the user and the generated tickets in this tree. Maybe is there an entity configuration problem.

**Comment by dfper-tjpa** [comment] 2021-04-16 16:56
Sorry for delay...

Yes, i am using now 2.11.2 version.
About entity tree, we using 2 entities just for publish a public form and doesn't show this for any user from the "main" entity.

**Comment by cgrzl** [comment] 2021-06-04 17:06
Hello, I am in the same situation. Whether in version 9.5.2 with the plugin 2.11.2 or with glpi 9.5.5 and the plugin 2.11.4, I have elements not found when I am with a "helpdesk" profile but with a "central" profile it works normally.

I am on a test version with basic GLPI, a single entity, the default profiles, ...

![image](https://user-images.githubusercontent.com/85362794/120838322-f8b75580-c567-11eb-8178-c40bf3f32da3.png)

**Comment by dfper** [comment] 2021-06-16 13:54
Hi, 

I'm going to check out the latest development version 2.12 as #2255 looks to be the same case and seems to have been resolved

**Comment by btry** [comment] 2021-06-16 14:25
Hi

You're right, this issue is very likely a duplicate of #2255.

To test a bugfix I recommend you to pick only the diff file representing the patch and apply it. It is less reliable to test a fix by using a different release.

**Comment by btry** [comment] 2021-09-08 13:37
Hi

Is your issue solved ?

**Comment by ladenree76000** [comment] 2021-12-15 08:57
HI,  
glpi9.5.5 + formcreator 2.12.2

one form with 2 target tickets :   only 1 line inserted in glpi_plugin_formcreator_issues table  ( f_xxx)  => unable to see tickets with simplified interface

when I run automatic action "SyncIssue"   2 lines are insterted into in glpi_plugin_formcreator_issues table  (t_xxx1 & t_xxx2)  then i can see tickets with simplified interface  

I hope this helps

**Comment by btry** [comment] 2021-12-15 09:11
hi  

> one form with 2 target tickets : only 1 line inserted in glpi_plugin_formcreator_issues table ( f_xxx) => unable to see tickets with simplified interface

If the requester clicks the assistance request, he will see a page with his own answers, and tabs on the left. One tab shows the list of generated tickets, and he cal click them

![image](https://user-images.githubusercontent.com/14139801/146156531-590e7f93-d042-4939-b8cd-0656a16eec44.png)

Having only one new row in the issues table is the expected behavior. the assistance requests are not tickets. 

> when I run automatic action "SyncIssue" 2 lines are insterted into in glpi_plugin_formcreator_issues table (t_xxx1 & t_xxx2) then i can see tickets with simplified interface

This is a known bug. There is a fix for this.

@ladenree76000 If you want to test the fixes, I recommend you use the latest revision of the branch support/2.12.0

**Comment by ladenree76000** [comment] 2021-12-15 10:52
"If the requester clicks the assistance request, he will see a page with his own answers, and tabs on the left. One tab shows the list of generated tickets, and he can click them"  
as the requester click on generated ticket list  he gets the messsage "you don't have rights" (upgraded to 2.12.3  same behaviour)

i'm looking for the fix

**Comment by btry** [comment] 2021-12-15 10:57
I don't remember well as it was a complicated bugfix. I did a fix in the sync issues SQL query that I recommend you to use (this required to run the sync after that, to fix possible inconsistencies in the issues table). There was also, if I remember well, a fix in the file inc/issue.class.php changinf some login in displayExtended() or displaySimplified() methods. Both are included in 2.12.3.  Do a blame on the file on github and you should locate the fix easily.

**Comment by btry** [comment] 2021-12-15 11:53
https://github.com/pluginsGLPI/formcreator/commit/c77be76f4db690388337db064a208d42e5713904

**Comment by btry** [comment] 2022-01-29 15:47
Hi 
Is the problem solved with the latest version ?

**Comment by btry** [comment] 2022-11-24 11:33
Hi

I think this problem should  be solved with Formcretor 2.13.3 (release in progress). As this version is very different, if the problem persists, open a new ticket. I close this one because it is obsolete.

**Closed by btry** 2022-11-24 11:33 UTC
Labels: need feedback
