### ISSUE TITLE
support 2.9.0 - duplicate crash

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1584] opened 2019-12-16 15:17 UTC
Hi,
I try to duplicate a form : 

Fatal error: Uncaught GlpiPlugin\Formcreator\Exception\ImportFailureException: failed to add or update the item in /var/www/html/glpi/plugins/formcreator/inc/question.class.php:974 Stack trace: 
0 /var/www/html/glpi/plugins/formcreator/inc/section.class.php(272): PluginFormcreatorQuestion::import(Object(PluginFormcreatorLinker), Array, 14) 
1 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(2007): PluginFormcreatorSection::import(Object(PluginFormcreatorLinker), Array, 10) 
2 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1502): PluginFormcreatorForm::import(Object(PluginFormcreatorLinker), Array) 
3 /var/www/html/glpi/plugins/formcreator/inc/form.class.php(1567): PluginFormcreatorForm->duplicate() 
4 /var/www/html/glpi/inc/massiveaction.class.php(990): PluginFormcreatorForm::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(PluginFormcreatorForm), Array) 
5 /var/www/html/glpi/inc/massiveaction.class.php(969): MassiveAction->processForSeveralItemtypes() 
6 /var/www/html/glpi/front/massi in /var/www/html/glpi/plugins/formcreator/inc/question.class.php on line 974

![image](https://user-images.githubusercontent.com/55535560/70918547-7eb3a980-201f-11ea-8f95-9cb8254a9d0c.png)

The form is very partially duplicated :-/

**Comment by btry** [comment] 2019-12-16 15:22
Hi

With a simple form, it works. I guess this is specific yo your form. Could you find a very simple form where you can reproduce the issue and send its export or describe how to build it ?

**Comment by mab18** [comment] 2019-12-17 08:50
Hi, 
I will do a retry, maybe it was link to the problem #1583

**Comment by mab18** [comment] 2019-12-17 09:11
Have you got a place to send the json ? E-Mail ?

**Comment by btry** [comment] 2019-12-17 09:47
Hi

You can put your attachment here.

**Comment by mab18** [comment] 2019-12-17 09:59
Hi,
Attachement is precedent post.
Some forms are ok to duplicate...
I have another problem with another form : message is not the same, I create another issue.

**Comment by mab18** [comment] 2019-12-17 10:30
I see a problem : I have a string of characters in a question of type "selection" of 97 char. (it's a comment in braquets because it have to be on the same line). Is I reduce the line, the duplication duplicate it and crash later on another thing. But I don't see what.

**Comment by btry** [comment] 2019-12-17 10:33
Hi

Brackets ? ok, i'm not sure yet, but this might be the cause of the bug. I'll have a try after i finish my current task.

**Comment by mab18** [comment] 2019-12-17 10:50
If I replace braquets by spaces, same thing. 
If I reduce the length it crash later, but no idea.

**Comment by btry** [comment] 2019-12-17 12:55
The file you shared works fine for me. I can duplicate the form without any issue.

If you try again, you wwill have an incomplete duplicate form. By editing it you will be able to identity the first question missing. look in the original form which is this questin, and give me a screenshot of its settings. The error should be related to its content.

**Comment by mab18** [comment] 2019-12-19 10:56
This issue is corrected by  #1585
Thank you @btry

**Comment by mab18** [comment] 2019-12-19 10:58
I have a question : Why I have the problem and not you ?

**Comment by btry** [comment] 2019-12-19 11:11
I don't know yet. Probably a difference between the data in your db compared to mine, despite the effort to have an accurate export / import code.

so, in this issue, remains a duplication bug with your select field of 97 chars, right ?

**Comment by mab18** [comment] 2019-12-19 13:27
Ok for maybe differences... not easy I think to have a dev environment AND a test one, AND a ref one... ;-)
Your are right about 97 chars, but, I didn't change the length, so 97 chars seems not to be a problem. I think I changed the test case in suppressing many of last ones by suppress les \' and \( and \) ;-)

**Comment by btry** [comment] 2019-12-19 13:31
If you have a backup of the DB before you changed the data, check if the question had a single quote in the columns values or default_values.

If you find one or more, then the fix I added today will very likely fix the bug.

I'm quite sure we can close this issue.

**Comment by mab18** [comment] 2019-12-19 15:34
I found the second problem : I have double quote in description !
But duplication is ok now. For me, now, there is no problem with quotes (simple or double) or parentheses, in my context.
Just when, duplicate, #1571 is again present.

**Comment by btry** [comment] 2019-12-19 15:52
Thanks, I close this one.

**Closed by btry** 2019-12-19 15:52 UTC
