### ISSUE TITLE
Filtrage des formulaires

### ISSUE THREAD

**Issue by eckorion** [pluginsGLPI/formcreator#2244] opened 2021-05-18 08:41 UTC
Hi

**Describe the solution you'd like**
Give the possibility to activate forms for goups and not only profils

**Additional context**
We have different kind of users in our organization and it could be a great improvement to give the possibility to access only few forms in some case to them.
We solved partialy this with the "entities" but the granularity is not enough efficient. So we use the profilq but it force the users to change it depending what they want to do while they already belong to groups.

Thanx for reading

**Comment by btry** [comment] 2021-05-18 12:56
Hi

This is a duplicate of #2132

**Comment by btry** [comment] 2021-05-18 13:02
If you have a subscription to GLPI Network you may ask a quote for this development.

**Closed** 2023-04-21 13:28 UTC
Labels: duplicate, feature
