### ISSUE TITLE
Correct Version for GLPI 10.0.0?

### ISSUE THREAD

**Issue by mriske** [pluginsGLPI/formcreator#2819] opened 2022-06-02 11:01 UTC
Hey, i just upgraded from 9.5.2 to 10.0.0 and wanted to also upgrade Formcreator.
I downloaded [v2.12.5](https://github.com/pluginsGLPI/formcreator/releases/tag/v2.12.5), which states
-  This version is compatible with GLPI 9.5.5 or later only

This doesn't seem to apply to version 10 (which is greater than 9.5.5), as i get following message on the GPLI plugins page:
![grafik](https://user-images.githubusercontent.com/56068250/171614250-702499fa-218a-46e1-9175-ef3c1592bab4.png)
It seems to only support v9.5 and up to v9.6 and not version 10.

So, which release version is the correct one? 

Thank you!

**Comment by btry** [comment] 2022-06-02 11:03
Hi

To use Formcreator with GLPI 10 you need the version 2.13.0. The latest version is 2.13.0-beta.2 and is not ready yet for production.

**Comment by btry** [comment] 2022-06-02 11:34
Duplicate of #2774

**Comment by alexmicontini** [comment] 2022-06-02 17:58
Hi,
When is there expected to be a stable version for GLPI 10?
It's been almost a month and a half since GLPI 10 stable came out and most important plugins, like Formcreator, are already supported. Many of us are waiting for a stable version of FormCreator to migrate to GLPI 10.
All the best

**Comment by alexmicontini** [comment] 2022-06-07 10:39
Hi @btry ,
thank you very much for answering.
ok, we will have to be patient.

**Closed** 2022-06-20 09:21 UTC
Labels: question
