### ISSUE TITLE
Associate items to the ticket after the opening

### ISSUE THREAD

**Issue by sidneim** [pluginsGLPI/formcreator#232] opened 2016-08-17 13:27 UTC
Hello,

We are struggling to find a way to associate items (Computer or Software) to the ticket after the opening of through ticket form. Has anyone experienced any similar situation? Is there a way perhaps to do by rules or configuration on the form?

Thank you so much,
Sidnei

**Comment by btry** [comment] 2016-08-18 07:22
Hi

I guess there is a question in your form allowing the user to choose a computer or a software, am I right ?

**Comment by sidneim** [comment] 2016-08-18 11:19
Oi btry,

Até coloquei uma questão configurada como Type = GLPI Object e Assets - Computers, mas esta informação quando selecionada e colocada apenas no Campo Descrição do Ticket que é aberto.

O que eu preciso é quando selecionar um Computer deve associar como um Item no Ticket.

Obrigado.

**Comment by sidneim** [comment] 2016-08-18 11:20
Hi Btry,

To put a question set as Type = GLPI Object and Assets - Computers, but this information when selected and placed only in the Field Description Ticket is open.

What I need is when selecting a Computer must associate as an item on the Ticket.

Thank you.

**Comment by btry** [comment] 2016-08-18 11:32
Thank you.

Ticket rules does not allow to find an item in the desrciption to add it in as an associated item. FormCreator does not create the association. 

I mark your ticket as a feature request.

**Comment by sidneim** [comment] 2016-08-18 11:52
Thank you,

Btry, another problem is that the set Question field the way you spent does not filter the computers the request of the User Group. I do not know if it is opening a new Issue to this.

**Comment by btry** [comment] 2016-08-18 13:20
It seems there is no filter on the computer to show only those in the group of the current user. This is by design.

I think this is possible to implement this too but there is a drawback : some users need to show all computers in the entity of the user.

I suggest you open an other feature request for better visibility and tracking.

**Comment by jfg-fimac** [comment] 2017-04-19 17:50
Hi !
Have you find the problem ?
Just for have a delay.
Thanks you ;)

**Comment by btry** [comment] 2017-04-19 17:57
This is more a feature request than a problem :). 

As this is a communautary request it is processed at best effort. To speedup this development you may consider contacting Teclib' : contact@teclib.com

**Comment by jfg-fimac** [comment] 2017-04-19 18:00
Hoo yes, escuse me !
I missed the ticket..

**Comment by btry** [comment] 2017-04-19 18:07
You're welcome.

**Comment by nqb** [comment] 2017-07-05 08:57
+1 for this feature. Have you plan to add this feature in recent release ?

**Comment by btry** [comment] 2017-07-05 13:22
Hi

No plan yet. If you want it quickly, you may consider sponsoring this enhancement. See the above comment: https://github.com/pluginsGLPI/formcreator/issues/232#issuecomment-295367620 .

New feature will be implemented in 2.6.0, and it I expect to release this version at the same time as GLPI 9.2.

**Comment by sidneim** [comment] 2017-09-29 18:56
Hi, has the implementation been released in version 2.6.0?
Thank you.

**Comment by btry** [comment] 2017-09-29 19:38
Hi

This feature is not implemented in 2.6.0-rc1. Being a new feature I must plan this for a new major version (X.Y.0). Versions 2.6.x are for maintenance. Again, community development is done at best effort, and I still have lot of work :
* code quality enhancement (unit tests, cleanup and refactor) to reduce regressions risks
* some new features may be sponsored soon and should be in the roadmap for 2.7.0

Again, consider sponsoring the feature, this is the only way to have a new feature within a reasonable and known delay. Feel free to contact us at contact@teclib.com .

**Comment by btry** [comment] 2018-10-28 16:05
Hi,

You need to look into the classes PluginFormcreatorTargetBase and PluginFormcreatorTargetTicket (which inherits from the first one). Look into PluginFormcreatorTargetTicket::save(). This method generates a target ticket from the form answers.

The method PluginFormcreatorTargetTicket::showForm() contains the form used by an admin to configure how the target ticket is generataed. I think that you need to add a new row with an input to choose a question of type GLPI Object and having one of the allowed helpdesk subypes. There is a global containing  that, in $_SESSION or $CFG_GLPI (more likely $_SESSION, check it with the debug mode).

Good luck, and please, consider adding unit tests for you new methods. I plan to work a lot on code coverage to have a descent ratio somewhere in 2019. This plugin becomes too much important to be poorly unit tested.

**Comment by btry** [comment] 2020-08-20 11:35
Hi

Target tickets now support associating items to the generated ticket
![image](https://user-images.githubusercontent.com/14139801/90765206-d3fc3500-e2e9-11ea-91b4-3904fe516744.png)

Also, an enhancement was done to restrict the items to those the user is allowed to see (un the profile, see items in my group, and similar).

then I think I can close this issue.

**Closed by btry** 2020-08-20 11:35 UTC
Labels: feature
