### ISSUE TITLE
Version 2.5.0: group not added to requesters

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#629] opened 2017-06-14 11:59 UTC
Hello

Thx for this great new version.

Is it possible to do the same thing for ticket title as category
![image](https://user-images.githubusercontent.com/15144026/27131113-95e0ea2e-5109-11e7-8052-dad3ac14c502.png)
replace title by content of title of incident fields of my form

My group is not created as well 

- It would be useful to have the possibility to sort form views for users, with glpi statistics we are able to know which request are the most used and put these forms firstly for users.

**Comment by btry** [comment] 2017-06-14 13:12
Hi

1st question:
Add a question answer tag in the title of the target ticket our taget change. It should work.

2nd question:
I'm not sure about your question. Do you mean sorting the forms in t he adminisration area of the plugin (where the admin designs forms) ?

**Comment by satyan01** [comment] 2017-06-14 13:44
1 - how can I add a tag in title ?
![image](https://user-images.githubusercontent.com/15144026/27135177-248008a6-5118-11e7-8b88-74a903f17d3b.png)

2 - I mean change in administration the view for users view

example in administration mode I put first - incident /  wifi access / folder right

users see : incident /  wifi access / folder right

**Comment by btry** [comment] 2017-06-14 15:00
1 
At the bottom of the  target ticket you have a list of tags for labels and answers. Simply use them in the title. See the screenshot below.

![image](https://user-images.githubusercontent.com/14139801/27139101-637ed1ea-5122-11e7-96e1-1f360245f752.png)

2 there is no feature for that now. Forms are displated to the user by popularity or alphabetically. The popularity of a form increases when a user answers it.

**Comment by satyan01** [comment] 2017-06-14 15:05
1 - thx it works
2 - ok it answers to my request
3 - issue with requester group
![image](https://user-images.githubusercontent.com/15144026/27139580-aafb18f2-5123-11e7-931e-617e3c9778d1.png)

**Comment by btry** [comment] 2017-06-14 15:09
Please show me the target ticket definition of this form, to see how groups shoudl be aded (from a question, a fixed group, ..)

**Comment by satyan01** [comment] 2017-06-15 07:01
![image](https://user-images.githubusercontent.com/15144026/27169222-361c5f7e-51a9-11e7-9d53-d2afb2bd9aac.png)

**Comment by btry** [comment] 2017-06-15 12:06
This screenshot shows the user filling the form is added to the target ticket. There is not any group to add as requester, then the plugin seems to behave as expected.

**Comment by satyan01** [comment] 2017-06-15 12:29
I have this setup for all my forms and the group is added automatically with the requester

**Comment by btry** [comment] 2017-06-15 12:31
Then the group comes from a ticket template.

In my opinion, if the template assigns actors, they should be added to those defined in the target item.

I need to determine if this is a regression.  did this worked with previous version of the plugin (2.4.x ) ?

**Comment by satyan01** [comment] 2017-06-15 12:38
nothing in my other templates and it was working with 2.4.0 but not for all forms, so I suppose it does not come from 2.5.0. How the requester is able to be added automatically with the associated requester ?

**Comment by btry** [comment] 2017-06-15 12:41
OK I mark this as bug for version 2.5.2 or later. (2.5.1 is planned for PHP 5.4 comaptibility )

**Comment by satyan01** [comment] 2017-06-15 12:51
ok thx

**Comment by nbriche** [comment] 2017-06-19 13:00
@satyan01 Maybe the group was added by the "Behaviors" plugin?

I'm also trying to get this to work (automatically adding the user's groups to requesters), but so far no luck. As long as I don't use a form, the groups add themselves correctly (using Behaviors), but if I use a form nothing happens.

**Comment by btry** [comment] 2017-06-19 13:05
Hi 

This might explain why the target ticket does not have any group. @satyan01 please confirm if you use the **Behaviors** plugin to add a group.

**Comment by nbriche** [comment] 2017-06-19 13:12
To be more precise: I'm currently using GLPI 9.1.3, Behaviors 1.3, FormCreator 2.4.2. (Although I just tested 2.5.1, and no change)

**Comment by satyan01** [comment] 2017-06-19 13:12
Hello yes I confirm to use Behavior plugin

**Comment by yllen** [comment] 2017-06-21 06:42
In Behaviors plugin, adding of group requester is done in pre_item_add to after have mechanism of the core.
In Formcreator plugin, adding a ticket is done directly so after rules of Behaviors plugin

**Comment by btry** [comment] 2017-06-21 07:27
Thank you @yllen for this information.

I think shall do the same in FormCreator, this way, both plugin can work together.

**Comment by satyan01** [comment] 2017-06-21 07:39
if it is not a big modification could you give me it in order to fix it now.

**Comment by btry** [comment] 2017-06-21 07:44
@satyan01 please try first to workaround by adding in your target  the groups which sould be added by Behaviors.

I think it will work. I think I have to redesign several parts of the plugin now to solve more complex issues, and plan to add tests on the UI of the plugin.

**Comment by satyan01** [comment] 2017-06-21 09:42
the group is different according to the requester, anyway, i will wait for your fix. Thank you

**Comment by satyan01** [comment] 2017-06-22 06:57
I confirm if I force group in the form it does not appear in the ticket

**Comment by btry** [comment] 2017-06-27 14:16
Hi

I think the fix needs to be in Behaviors, not FormCreator. 

To remove direct manipulation on tickets I contributed to GLPI 9.1.2 to let it handle arrays of users, groups and suppliers for all actor types (requester, observer, and assigned). 

Behaviors does not handle arrays for requesters,  then it fails with FormCreator. I tried a simple change in FormCreator but this is not sufficient to make Behaviors happy. If I go further, I will simply destroy the work I did a few months ago, and revert to the previous implementation. This old code was very hard to maintain, and is anyway incomaptible with Behaviors due to how it worked.

**Comment by btry** [comment] 2017-11-15 09:11
Hi

A contributor found a typo in the code preventing a requester group being added to the target ticket.  @satyan01 Can you see if this helps to solve your issue when Behaviors is enabled ?

**Comment by ladenree76000** [comment] 2017-11-15 13:07
workaround to dynamically add users group as requestergroup ( when behaviors plugin is activated)

class targetticket.class line 990   add these line : 

```
      } else {
/*** simulate plugin behaviors ***/
	$pluginbehaviors = new Plugin();


      if ($pluginbehaviors ->isInstalled('behaviors') && $pluginbehaviors ->isActivated('behaviors')) {
	 $config = PluginBehaviorsConfig::getInstance();
		switch ($config->getField('use_requester_user_group')){
			case '0' :
			break;
			case '1' : 
				$this->requesterGroups = array('_groups_id_requester'        => PluginBehaviorsUser::getRequesterGroup ($datas['entities_id'],$_SESSION['glpiID'], $first=true));      
		
			break;
			case '2' : 
			$this->requesterGroups = array('_groups_id_requester'        => PluginBehaviorsUser::getRequesterGroup ($datas['entities_id'],$_SESSION['glpiID'], $first=false));      
			break;

		}
}
/**** end simulate plugin behaviors ***/
         $datas = $this->requesters + $this->observers + $this->assigned + $this->assignedSuppliers + $datas;
         $datas = $this->requesterGroups + $this->observerGroups + $this->assignedGroups + $datas;
```

could be ehanced by managing when requester is not current user or managing multiples requesters

**Comment by ladenree76000** [comment] 2017-11-15 14:08
this workaround works for glpi 9.1.6, formcreator 2.5.2 and behaviors 1.5.0.

keep in mind that if a future version of behaviors manages tickets created with form creator, this workaround might generate duplicates requester groups.

note : form creator allows multi requester tickets creation; until now, behaviors manages single requester tickets. in thiis context requester managins seems a bit tricky...

**Comment by nbriche** [comment] 2017-12-07 13:33
For GLPI 9.2.1, FormCreator 2.6 and Behaviors 2.0, the same block of code can be pasted at line 1222 of inc/targetticket.class.php:

```      // Define urgency
      $data = $this->setTargetUrgency($data, $formanswer);

      $data = $this->setTargetCategory($data, $formanswer);

      $data = $this->setTargetLocation($data, $formanswer);

/*** simulate plugin behaviors ***/
        $pluginbehaviors = new Plugin();


      if ($pluginbehaviors ->isInstalled('behaviors') && $pluginbehaviors ->isActivated('behaviors')) {
         $config = PluginBehaviorsConfig::getInstance();
                switch ($config->getField('use_requester_user_group')){
                        case '0' :
                             //no group added;
                        break;
                        case '1' :
                             //first group added;       
                                $this->requesterGroups = array('_groups_id_requester'        => PluginBehaviorsUser::getRequesterGroup ($data['entities_id'],$_SESSION['glpiID'], $first=true));

                        break;
                        case '2' :
                           //all groups added;  
                        $this->requesterGroups = array('_groups_id_requester'        => PluginBehaviorsUser::getRequesterGroup ($data['entities_id'],$_SESSION['glpiID'], $first=false));
                        break;

                }
}
/**** end simulate plugin behaviors ***/


      $data = $this->requesters + $this->observers + $this->assigned + $this->assignedSuppliers + $data;
      $data = $this->requesterGroups + $this->observerGroups + $this->assignedGroups + $data;
```
Note that the variable `$datas` becomes `$data`. 

Also I suppose the array declaration really should be converted to new-style to comply with code style, but for a temporary hack it should be good enough? I guess?

This has _not_ be as thoroughly tested as I'd want it to be yet. But it seems to work well enough.

**Comment by btry** [comment] 2017-12-07 13:41
Hi

This issue seems duplicate to #767, @ladenree76000 found a fix.

**Comment by nbriche** [comment] 2017-12-07 13:51
I've seen that one and I manually corrected the typo in my 2.6 setup, but it didn't seem to make the groups work. Maybe I should just use the current dev tree; is there any issues I should be aware of when replacing a release version by a dev one? Any upgrade steps I have to do manually?

**Comment by btry** [comment] 2017-12-07 13:58
The dev branch is currently a 2.6.0 with bugfixes only. I advice you to check on a pre production environment first if no other issues are introduced.

I canceled my plans to release a 2.6.1 version to provide quickly a 2.7.0 version (code not published yet). I'm very busy for now, and work on 2.7.0 is getting late. This makes me reconsider my decision, and I think I'll provide a 2.6.1 release before the end of the year.

**Comment by nbriche** [comment] 2017-12-07 14:27
I confirm: no group added when using behaviors 2.0.0 with formcreator dev branch, glpi 9.2.1. Tested with both 'all group' and '1st group' in Behaviors.
(I just plopped a GIT clone in glpi/plugins and checked out the 'develop' branch)

**Comment by btry** [comment] 2017-12-07 14:29
See this comment

https://github.com/pluginsGLPI/formcreator/issues/629#issuecomment-311372153

**Comment by nbriche** [comment] 2017-12-08 09:09
So I'm trying to understand the design principles involved here, to see exactly what must be done to make both plugins happy with each other. (Because when all's said and done, in 4 weeks I'm supposed to make it work for a dozen sites, some of which don't have GLPI yet, and totaling about what, 8000 users? Yeah I'm a little stressed here.)

So if I understand correctly:

- FormCreator is the generator here. That's where the ticket is instanciated and from where all basic data are fed. That happens in `PluginFormcreatorTargetTicket::save()`. The function returns a Ticket object that is then injected into GLPI's core for further processing.

- Behaviors is then supposed to grab it in passing, apply its ~~witchery~~ magic to it, and reinject it afterwards. This is ultimately done in `PluginBehaviorsTicket::BeforeAdd()` (and siblings) (which somehow does not return the `$ticket`? The function's parameter is passed by reference here?).

Except that Behaviors somehow fumbles the ticket? This is where I'm lost.

**Comment by btry** [comment] 2017-12-08 09:28
> FormCreator is the generator here
Yes. 
> That happens in PluginFormcreatorTargetTicket::save()

However, the ticket returned by save() is onlmy for internal needs of Formcreator. Invoking add() method actually saves the ticket in the database, *and* triggers events for plugins, *and* triggers computation in GLPI core on data passed to the add() method. 

Behaviors is triggered in the process of the add() method.

**Comment by btry** [comment] 2017-12-08 09:33
I think Behaviors needs a patch to handle correctly an array of requesters. 

Currently, and if I remember correctly, it only handles a single requester passed as a scalar integer (an ID)

**Comment by btry** [comment] 2017-12-08 09:49
I guess you want to develop a patch to solve this issue. Please consider sharing it with the team in charge of Behaviors plugin. Then I mark this bug for 2.6.1. Also the bug is in Behaviors, but I keep  the bug label in this ticket anyway.

**Comment by btry** [comment] 2017-12-08 10:00
The method PluginBehaviorsTicket::BeforeAdd()

is called in the process of Ticket::add(), and before the ticket is actually saved in the database. Check the method CommonDBTM::add() which implement the high level actions of adding any item in the database, including tickets of course.

**Comment by nbriche** [comment] 2017-12-08 10:23
Behaviors is still on the old forge, which is not quite optimal for my workflow but yes, I'm going to request some dev time to my boss to work on this a little.

**Comment by nbriche** [comment] 2017-12-08 14:02
Okay I _think_ I've got it.

At [`behaviors/inc/ticket.class.php:344`](https://forge.glpi-project.org/projects/behaviors/repository/entry/tags/2.0.0/inc/ticket.class.php#L340), `PluginBehaviorsTicket::beforeAdd()` tests the incoming ticket's requesters. It only applies the configured policy if:
- `$ticket->input['_users_id_requester']` exists, and
- `$ticket->input['_users_id_requester']` is not zero, and
- `$ticket->input['_groups_id_requester']` doesn't exist, or is `<=0`.

Core 9.2.1 creates its 'vanilla' tickets with a `_groups_id_requester` set to zero if no group is added. Behaviors knows how to handle that. But FormCreator sends an empty array, and as you said [previously](https://github.com/pluginsGLPI/formcreator/issues/629#issuecomment-350217418), that's not a case this test is ready for.

If I complete the test as such: `&& (!isset($ticket->input['_groups_id_requester']) || $ticket->input['_groups_id_requester']<=0 || empty($ticket->input['_groups_id_requester']))`, Behaviors seems to understand what's going on and add the correct groups.

The thing is, I don't know if this is a problem with Behaviors for not checking `_groups_id_requester` as an empty array, or FormCreator for not declaring an empty `_groups_id_requester` the same way as Core.

**Comment by btry** [comment] 2017-12-09 16:53
Hi

> The thing is, I don't know if this is a problem with Behaviors for not checking _groups_id_requester as an empty array, or FormCreator for not declaring an empty _groups_id_requester the same way as Core.

I said I contributed to GLPI core to handle creation of ticket with several requesters. This contribution is intended to solve way too complex and unmaintainable code in Formcreator. Also, setting multiple observers or assignees was already possible. It makes sense to have same level of features for all actors. The user interface of GLPI still does not allows to set several requesters, this is the reason it does not sends an array of requesters.

Therefore, Behaviors is simply not up to date, and it needs a patch. Your investigation seems good, and you're close to a good patch to submit to  the community.

> Now that I think about it, unless there's a reason for _groups_id_requester to be negative, that entire test can be replaced by just the empty($ticket->input['_groups_id_requester'])) and we'll have support for both forms.

I believe I never saw a case when a group ID may be < 0. This needs investigation to determine if this code is still useful or is dead. I suggest you leave it as is to submit a patch which only solve your issue, and investigate (if you want) separately about this case.

**Comment by btry** [comment] 2018-01-29 15:49
Hi

@nbriche did you find time to build a patch for Behaviours plugin ? Or is the bug fixed by someone else ?

**Comment by nbriche** [comment] 2018-01-29 17:08
Hi,

Sorry; I've asked for the preferred patch submission method (since I have no access to the forge except as read-only, and there's no GitHub repo for Behaviors) but I've had no answer yet. I've used my test modification (manually edited) for about three weeks in production, I've had no issue.

**Comment by btry** [comment] 2018-01-29 17:11
If I remember correctly, I have access to submit patches or issues. You may send the diff here. I"ll review it, and submit it to the official maintainer.

**Comment by nbriche** [comment] 2018-02-07 13:40
Hi,

At long last I managed to find enough time to build a patch: [issue629_behaviors-v2.0.0.patch.txt](https://github.com/pluginsGLPI/formcreator/files/1703247/issue629_behaviors-v2.0.0.patch.txt)

It's built (as the name suggests) against 2.0.0. There's been a new release since, but the patch doesn't conflict.

**Comment by btry** [comment] 2018-02-07 13:45
Hi

Thnak you. I submitted the patch here

https://forge.glpi-project.org/issues/5548

**Comment by yllen** [comment] 2018-02-07 15:18
_groups_id_requester is always set.
If empty it set to 0 in the core.
Test for <=0 is for ticket creation from webservices (a mistake can be set in value passed)

If Formcreator doesn't define value as request in the core it's not a Behaviors error.
But if it can solve users issue, i added this control.

**Comment by btry** [comment] 2018-02-07 15:24
Hi

OK, I'll update the plugin to always set _groups_id_requester.

**Comment by nqb** [comment] 2018-02-26 10:11
Hello,

With : 
* GLPI 9.2.2
* Behaviors 2.0.2 (option "Use the requester's group" = "First")
* FormCreator 2.6.2,

First requester group is assign on ticket created through formcreator.

**Comment by btry** [comment] 2018-04-05 07:36
Hi

@yllen please have a look on the following PR. I think the problem you identified will be properly solved with it.

https://github.com/pluginsGLPI/formcreator/pull/927

**Closed** 2018-04-30 09:40 UTC
Labels: bug
