### ISSUE TITLE
Undefined offset /  Uncaught Exception Error: Call to a member function getID

### ISSUE THREAD

**Issue by dleick** [pluginsGLPI/formcreator#2268] opened 2021-06-17 09:11 UTC
**Describe the bug**
After I click on send the formular I have this message :

```
PHP Notice (8): Undefined offset: 9 in C:\xampp\htdocs\glpi\marketplace\formcreator\inc\composite.class.php at line 92
Uncaught Exception Error: Call to a member function getID() on null in C:\xampp\htdocs\glpi\marketplace\formcreator\inc\composite.class.php at line 96
```

All ticket (6) are correctly created but the relation child/parent of the tiket is broken after the second ticket

**Screenshots**
![image](https://user-images.githubusercontent.com/73337261/122367289-980f1c00-cf5c-11eb-8c59-0917efda8d42.png)
![image](https://user-images.githubusercontent.com/73337261/122366608-fdaed880-cf5b-11eb-922e-ae81f98b757b.png)
![image](https://user-images.githubusercontent.com/73337261/122366696-11f2d580-cf5c-11eb-833c-e7d5359dcafc.png)
![image](https://user-images.githubusercontent.com/73337261/122366947-51212680-cf5c-11eb-95b2-b86605506a3f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 last update (21h1)
 - Browser New Edge
 - Version last one

**Additional context**
i'm using the last stable release of Formcreator and the last stable release of GLPI core

**Comment by btry** [comment] 2021-06-17 09:13
Hi

Please tell the version of GLPI and the version of the plugin.

**Comment by dleick** [comment] 2021-06-17 09:15
> Hi
> 
> Please tell the version of GLPI and the version of the plugin.

Hi, as i say at the end of the post :  Additional context
i'm using the last stable release of Formcreator and the last stable release of GLPI core

So GLPI : 9.5.5
FORMCREATOR : 2.11.4

**Comment by btry** [comment] 2021-06-17 09:28
Sorry, I searched fr numbers... And I think the bug report template needs an update, by the way.

Can you search in php-errors.log the backtrace associated to the message you got in debug mode ? It may be useful.

I'll try to reproduce next week, if I have some time to investigate.

**Comment by dleick** [comment] 2021-06-17 09:39
Hi,

here is the différent try i've done this morning : 
[apache log.log](https://github.com/pluginsGLPI/formcreator/files/6669109/apache.log.log)

thanks

**Comment by btry** [comment] 2021-06-17 10:06
The backtrace is not in this file. You will find it in the logs of GLPI : /.../glpi/files/_logs/php-errors.log

**Comment by dleick** [comment] 2021-06-17 10:11
> The backtrace is not in this file. You will find it in the logs of GLPI : /.../glpi/files/_logs/php-errors.log

oops, sorry. Here it is ;) 
[php-errors-.log](https://github.com/pluginsGLPI/formcreator/files/6669287/php-errors-.log)

**Comment by dleick** [comment] 2021-06-21 07:28
Hi, Any update ?

**Comment by btry** [comment] 2021-06-21 07:30
Hi

Not yet : I'm busy for now.

**Comment by dleick** [comment] 2021-06-21 12:40
@btry 
Hi,

I think I have a idea of what going one.

If you check the screenshot, i've add a relation parent/child for the target "[Vehicule]". But this target is created only if an awnser is set to "YES" in the formular. So maybe it's when the system want to link the uncreated ticket there is a problem.

What do you think ?

**Comment by dleick** [comment] 2021-06-28 10:08
Hi, any update ? I'm still stuck in my process with thie bug  :(

**Comment by btry** [comment] 2021-06-28 11:29
Hi

Try to apply the following patch, and check if you still can reproduce

```diff
diff --git a/inc/composite.class.php b/inc/composite.class.php
index f4978fb8..674d9b4b 100644
--- a/inc/composite.class.php
+++ b/inc/composite.class.php
@@ -90,6 +90,9 @@ class PluginFormcreatorComposite
 
                   case 'PluginFormcreatorTargetTicket':
                      $ticket = $this->targets['PluginFormcreatorTargetTicket'][$row['items_id']];
+                     if ($ticket === null) {
+                        continue;
+                     }
                      $this->ticket_ticket->add([
                         'link' => $row['link'],
                         'tickets_id_1' => $generatedObject->getID(),

```

**Comment by dleick** [comment] 2021-06-28 12:52
> Hi
> 
> Try to apply the following patch, and check if you still can reproduce
> 
> ```diff
> diff --git a/inc/composite.class.php b/inc/composite.class.php
> index f4978fb8..674d9b4b 100644
> --- a/inc/composite.class.php
> +++ b/inc/composite.class.php
> @@ -90,6 +90,9 @@ class PluginFormcreatorComposite
>  
>                    case 'PluginFormcreatorTargetTicket':
>                       $ticket = $this->targets['PluginFormcreatorTargetTicket'][$row['items_id']];
> +                     if ($ticket === null) {
> +                        continue;
> +                     }
>                       $this->ticket_ticket->add([
>                          'link' => $row['link'],
>                          'tickets_id_1' => $generatedObject->getID(),
> ```

Hi, 
I tried this few minutes ago and it's seems to be all good :)
Thanks a lot !

**Comment by btry** [comment] 2021-06-28 13:09
I'm unsure yet, the root cause may be a relation with a non existing ticket in the DB. Can you investigate in your database, table glpi_plugin_formcreator_items_targettickets ?

I believe that you have a row with itemtype='Ticket' ans items_id referring to a deleted ticket.

**Comment by dleick** [comment] 2021-06-28 13:49
> I'm unsure yet, the root cause may be a relation with a non existing ticket in the DB. Can you investigate in your database, table glpi_plugin_formcreator_items_targettickets ?
> 
> I believe that you have a row with itemtype='Ticket' ans items_id referring to a deleted ticket.

This is what I have in my DB :  
![image](https://user-images.githubusercontent.com/73337261/123647545-764d4900-d828-11eb-82fd-5c3c29be18a4.png)

**Comment by btry** [comment] 2021-07-06 06:23
Hi

Can you check in the table glpi_tickets if you have rows having ID between 6 to 17 (both included), except ID 12 ?

**Comment by btry** [comment] 2022-06-24 09:45
Hi

Having no feedback, I close this issue.

**Closed by btry** 2022-06-24 09:45 UTC
Labels: bug
