### ISSUE TITLE
No attachment when creating the form since the update to 2.13.5

### ISSUE THREAD

**Issue by Samirsncf** [pluginsGLPI/formcreator#3283] opened 2023-05-26 13:49 UTC
When creating a form with attachments the file in attachment is not saved
iI am currently in glpi 10.0.7, we also migrated from a version of GLPI in 9.5 to a version in 10.0.7
the file does not appear in the server

**Comment by Samirsncf** [comment] 2023-05-26 13:53
[
![MicrosoftTeams-image (16)](https://github.com/pluginsGLPI/formcreator/assets/105794103/4f4c604c-5710-433d-b22f-482628fd3bf8)
![MicrosoftTeams-image (15)](https://github.com/pluginsGLPI/formcreator/assets/105794103/634c4b1f-1c11-47ef-bd11-193ccd37f419)
](url)
I'm not in public

**Comment by btry** [comment] 2023-05-26 13:55
Ok, I understand. You have a question of type File. you need to add a tag ##answer_xx## which matched the file question.

**Comment by Samirsncf** [comment] 2023-05-26 13:59
This is what I added, ##answer_7## which corresponds, but the PJ does not appear when creating the form.
Or maybe I misunderstood.

**Comment by btry** [comment] 2023-05-26 14:37
I did a check, seems working (with the version 2.13.6, to be released soon)

**Comment by Samirsncf** [comment] 2023-06-12 06:42
Good morning,
After doing some test. It looks like the problem is not with Forms.
Indeed, I have uploaded files on tickets not linked to forms and I have the same behavior.
Some files work like .txt, others don't.
XSLM and XSLX not working? do you have an idea ?

**Comment by Samirsncf** [comment] 2023-06-13 06:16
Hi, 
No more than 1 mo
No more than 1 month
I also checked the rights of the files folder, the rights are correct, I really can't find where the problem can come from.

**Comment by Samirsncf** [comment] 2023-06-13 06:22
When an attachment works, I have the message directory creation, file moved successfully.
When that doesn't work, I get the message File moved successfully only.

**Comment by Samirsncf** [comment] 2023-06-14 06:36
hi,

owner and group are www-data (apache) from GLPI\files
With the same GLPI Users who have the rights, PJs work like for example .txt or .csv and some work 1 time out of 4 like XLSX or XLSM.
I checked the rights with the old server which was in version 9.5 and the rights are identical.

**Comment by Samirsncf** [comment] 2023-07-03 11:01
Hi,
I still have the problem and still haven't found a solution, it's not just about forms but all the tickets created, there is a problem with the extentiosn in xlsx and xlsm which works 1 time out of 8 but when a file doesn't work it won't work even if you try 20 times.

I checked the document types, I even recreated the xlsx and xlsm document type, nothing changed, checked the rights in the files folder identical to the other file types which work like PDFs for example, j Destroyed and rebuilt the form, same problem.
Do you have any other leads please?
THANKS.

**Comment by btry** [comment] 2023-07-03 11:53
Hi

> it's not just about forms but all the tickets created

Then the problem might be in GLPI, without any relation with Formcreator. So far, there are not enough evidences to determine if there is a bug.

**Comment by Samirsncf** [comment] 2023-07-03 12:38
I am the only one to have reported this type of problem with GLPI? I am on version 10.0.7

**Comment by Samirsncf** [comment] 2023-07-03 13:22
in the PHP LOGS I found:

[2023-07-03 12:50:54] glpiphplog.WARNING: *** PHP User Warning (512): Document ID is mandatory in /Applis/glpi-info/src/Document_Item.php at line 106
  Backtrace:
  src/Document_Item.php:106 trigger_error()
  src/CommonDBTM.php:1272 Document_Item->prepareInputForAdd()
  ...place/formcreator/inc/formanswer.class.php:1216 CommonDBTM->add()
  src/CommonDBTM.php:1318 PluginFormcreatorFormAnswer->post_addItem()
  marketplace/formcreator/ajax/formanswer.php:60 CommonDBTM->add()
  public/index.php:73 require()

**Comment by btry** [comment] 2023-07-03 13:28
Very good.

You said the problem also occurs when you create a ticket without the plugin. Can you check if you have a similar error in php-errors.log ? Don't forget to show it's backtrace.

**Comment by Samirsncf** [comment] 2023-07-03 13:38
I recreated a file by inserting the PJ which did not work, ticket created well but without PJ and it didn't log me anything in the php-errors.
I also have an error on the SQL-errors
  Error: Data too long for column 'mime' at row 1
  Backtrace :
  src/DBmysql.php:1320
  src/CommonDBTM.php:722                             DBmysql->insert()
  src/CommonDBTM.php:1317                            CommonDBTM->addToDB()
  src/CommonDBTM.php:5525                            CommonDBTM->add()
  src/CommonITILObject.php:2640                      CommonDBTM->addFiles()
  src/Ticket.php:2196                                CommonITILObject->post_addItem()
  src/CommonDBTM.php:1318                            Ticket->post_addItem()
  front/ticket.form.php:74                           CommonDBTM->add()
  public/index.php:73                                require()
  {"user":"1470@Gainsar"}

**Comment by Samirsncf** [comment] 2023-07-03 14:22
I think I found the problem, you have to add 255 in vaarchar on the mime column of Document, the mime was in varchaar 30.

**Comment by Samirsncf** [comment] 2023-07-03 14:33
I confirm, it fixed my problem, Thanks again ^^

**Comment by btry** [comment] 2023-07-05 16:20
Hi

For now, I think this is a workaround. With the change you did, what is the MIME value of the (successfully) added document ?

If this is a legitimate value, then you should check in the empty.sql file of GLPI if the column is varchar(30). If yes, then report the problem to GLPI, arguing that a MIME value may overvlow a varchar(30) column.

**Comment by btry** [comment] 2023-07-05 16:21
As the issue is in GLPI I close it. By the way, nice job.

**Closed by btry** 2023-07-05 16:21 UTC
