### ISSUE TITLE
Paste from clipboard picture does not works

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1514] opened 2019-10-03 13:19 UTC
**Describe the bug**
When copying from clipboard a picture (from part of screenshot for example), the picture is on the form, but when SEND, the picture is broken in ticket, we juste can see an icon, no picture.
This procedure works in a direct ticket.
Quand on copie du presse-papier une image (provenant d'une capture de l'écran par exemple), l'image apparait dans le formulaire, mais juste un icone apparait une fois transformé en ticket GLPI, sans l'image. Cette manipulation fonctionne en ticket direct.

**To Reproduce**
- Copy a picture in clipboard
- Go to a form, in a description field, 
- Paste clipboard, the picture appears in the field
- Validate the form and go in the ticket
- Only one icon of an image remains, without the image.

- Copier une image dans le presse-papier
- Aller dans une formulaire, dans un champ description
- Coller le presse-papier, l'image apparait dans le champ
- Valider le formulaire, et aller dans le ticket 
- Il reste seulement un icône dans la description, il n'y a plus d'image.

**Expected behavior**
The picture should be transferred in the GLPI ticket.
L'image devrait être transférée dans la description du ticket GLPI

**Screenshots**
See screenshots

**Desktop (please complete the following information):**
Firefox and IE
GLPI 9.4.3 / 9.4.4 and Formcreator 2.8.5
What you see in the form 
![plugin Formcreator - bug presse papier d'image 01](https://user-images.githubusercontent.com/55535560/66129911-1db83000-e5f1-11e9-9d50-2ecb366eb5e1.png)
What you see in the GLPI ticket :
![plugin Formcreator - bug presse papier d'image 02](https://user-images.githubusercontent.com/55535560/66129914-1e50c680-e5f1-11e9-99f5-0a833d13dc3c.png)

**Comment by btry** [comment] 2019-10-03 13:21
Hi

Please try the solution found in this issue : https://github.com/pluginsGLPI/formcreator/issues/1455

The fix will be published in 2.9.0

**Comment by mab18** [comment] 2019-10-03 13:44
Thank for your so speed answer !
BUT :
I do a 
ALTER TABLE `glpi_plugin_formcreator_answers` CHANGE `answer` `answer` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL;
so, I have the good type in my table, and it _doesn't_ correct the problem :
![image](https://user-images.githubusercontent.com/55535560/66131809-5c031e80-e5f4-11e9-825e-04f91071e28b.png)
Problem is strictly the same. Is there any other file to modify ? Can I download 2.9.0 to try ?

**Comment by btry** [comment] 2019-10-03 13:49
The problem is related to a unexpected truncation of the content, this occurs when we upload an image.

Once you raised the size limit of the field, the subsequent uploads should be fine. PRevious ones will not be fixed (the loss of data already occured for these olduploads).

Did you checked that after the change in the DB you can upload a picture and view it as expeceted ?

I released a few minutes ago the version 2.9.0 beta 1. You may t ry it, but I strongly recommend you try it on a testing environment only.

**Comment by mab18** [comment] 2019-10-03 14:06
Yes, I made a complete re-attempt. 
My picture is little, just the GLPI version.
Question, to be sure : What kind of field should be "Description" ? Mine is "Text zone" ("zone de texte" in FR).

**Comment by btry** [comment] 2019-10-03 14:13
Just to be sure : the description you're talking about is a question with the type description, right ?

**Comment by mab18** [comment] 2019-10-03 14:18
Yes, it is, see parts of my form :
![image](https://user-images.githubusercontent.com/55535560/66134873-52c88080-e5f9-11e9-90d3-c4eccebf7e7f.png)
![image](https://user-images.githubusercontent.com/55535560/66134881-56f49e00-e5f9-11e9-8fbc-c4b084d145ad.png)
![image](https://user-images.githubusercontent.com/55535560/66134891-5b20bb80-e5f9-11e9-853c-391596d05571.png)

**Comment by mab18** [comment] 2019-10-03 14:51
I "see" the picture in the table :

`&lt;p&gt;image ci_dessous&lt;/p&gt;&lt;p&gt;&lt;img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUUAAAAyCAYAAADLJMmQAAAHKUlEQVR4nO2bPW4rOwyFZ0PxArIQO/AqXBpIbp/e7YMxCwhSpXAVJECKIFVWcAHfLbzivU63mD+KIinOeDx27FN8QGBrJIqkjiiNU/z/378BAABARXFqAwAA4JyAKAIAAAGiCAAABIgiAAAQIIoAAECAKAIAAKH4s/8dAAAAVEAUAQCAAFEEAAACRBEAAAgQRQAAIEAUAQCAAFEEAAACRBEAAAgQRQAAIEAUAQCAAFEEAAACRBFcLuU8FEUR7sohz7+GX7MiFMU8lGa7bbgrilDM7sP7qef7E9FipH3+dh9mxU349XY8GyCKU/N2H2ZFEQrCXdl9Pnt4Zc/Ui45SL8D3h5u0HzZeuSDPLbZ5u6zFnWtTJ1dDOpcRqccyx1BF0SF45TwUfPFp86v9Iosvix+JgRWb6jtqX5oHxx0vlzuNDzm5TcSIEY0pRPFKEETl/eHGJ4pNUnIxMKqhSjTrBDKrJrKQVFHMtGnm1tj5dh/ujimKHg4QxXLB5pmZX9Ke+q1+ptnEqAAkf0eiJoiitbGNOJ4/d2pfDq2U+1aK+2246yu8PW2AKE5IlGj8e68o8nZGwka7v9p/3W5xbyZ3ro0+N1ZRNM+yqquxs7K56ad+drFtF/hsdlP1Ec07rVqiymN2Ey96PnYyn8rn1Fdm7NrvM4uV2Bz1J8QmWyl6ROiA8by5o4liVGW237E4Lba6WGux0+AnMJZnaT9KzuwhipMiHVF4UL2VYiuC3kpR67+c1wlk7PiONtrcVBuo3cLns4fX6FjaiqKwGahVjXAcq57PVYqVz6lPzdi19ljHunjMWGTTKtAcj8wlukKJ4nLYeK7coeOw04/0rLix5ESR5IH3OkaqkHkOWJUwRHFCaCBoMve9U4zaeI/FbDeMF4N8Z9mnjVZJxYuNLEbpCLfYhqQ6ZPen0mYQjeFZZANEMVcp5kSRi3r/SpHgEInDx/PeYaaiKObLYivPKROvND+09aXYq+SAmjN7iOK08DtFrVqSgq0lhPMNq5UEYnJ72khzY3duvSvFfbeAZzP+mSyKuUoxFcVc5Zcen3N3itbxOalyuX8FXyf2lXPXlclo42m5k5CpFBO7+lWK9tpw5LeSA6gUz4nM2+e0GtNFMfv2OeozXmCjiyJ5hle04v2Sda/X2s2Pc9q1Qb8qIbFVuw7gnyvzU9sr8W5iKb/dtecinhaOMZ6WOwmOO8WkQic2ZATMipGVe/kc0CthiCI4DZ5jf/ZNa0oingfZ5/zph/mTHPDTgCiC05B9QdRDZHh1NEBMU/Dj7WsFoggAAASIIgD777BZbcLtnLHahc+T2wamBqIIrpyPsJ5vwnL7nXz3uS3D7fwpPJ/cRjAlEEVw1Tw/bsLt40doxLGpEhuR7L4/va1gGiCK4Px5eQq3801Yv+Ta0mNwGTZfufYfYd22+wibplqk433twvLaqkW3vy+T/qL4tQtLfvfSdyetnS4dWXJUR5pu7GkC1yy24y2O50enPxv/97zvqvq37fe0ycWUV1qj4F2kL09MDDNx+9qFpehHeqSmwpm2kWJmxVLysS/2E453iChegD4MFsVRk74vk+9kxxXFKpD1wjPnRhaGsJjlox5dTJr9njb5nGjH/tqF9QlEMb0DPLIo1vNtFuL6hdka2a34WG1/nPFcuTaCKP5kfRhPFIXgdEnFdo3IaPbmr0nSpo9VaSeS0bbaEbvj0Zos3Gi3zI3JqqCqvWx3k7DLVRluV7vwT2RD/Yy1mxtJVYnerurDLYrCGApDK8VooUXf2bHtkOJFfMXibcVOyjP9bbJ1fK4/9xyfiX2RL4RYch/n2o89nivXXOtJzuVL0IdRjs/L7bc6aXHBeIJKHcfLaW3SynPd3dDQMdOKQ+ujFUVm63L7HdmgioqVVFSM2wXu+znJoaIYHUucfef8TOOS+Jz6yikCaa7lK3ztRUskwObxLx4jtiHeiLOiSNrr/h5xvJwokjiY8bkwfTh+pcicxI2Jg0aCqu4s+qTTtt1uRo9WUaWh7VAZUdTsjo42NImb74zjGrWHJ5tosyROZ1QpumIbLWTFV0m+CLEbKIqH/iSHb4LHrhQPHc+Ta73jc2H6MMHxmSXoahc+e+wEh02663+5siqKfD/eZE5FUbbBJUzi3QivFAeKotD34Bctyp1i70pR85WWLw5x9s1p2I+3k1OBkkOmj913iiONZ+WE1KcnPhemDyO+aEl3ICoSFfIFr3VHJJfbbJezHNTuRNJi8ZX41LHURsluSRQ7G4wL/9YWW7gsUZRRKgP1Ul6pHnIob59d9390LpKvrHzRqibJrjH/Q8V4yyq/3dV97Hr7PNZ4Wq4ZsczG58L0Ab9TnIT0rueqyb1lha/OmMuPD0RxAsTq8ZoxRBG+Om+uIT4QRQAAIEAUAQCAAFEEAAACRBEAAAgQRQAAIEAUAQCAAFEEAAACRBEAAAh/AX0+t0jSfEyTAAAAAElFTkSuQmCC" /&gt;&lt;/p&gt;&lt;p&gt;image ci_dessus&lt;/p&gt;`
It's seemly not truncated, because I can see the second text, after my picture : "image ci_dessus".
But it's not on screen, just an icon.

**Comment by btry** [comment] 2019-10-03 15:40
indeed; but I tryed to reproduce without success with version 2.9. I'll have a look on 2.8 branch, with the longtext type in the database.

**Comment by mab18** [comment] 2019-10-03 16:02
Thanks 4 all,
Tomorow, I'll take a snapshot of my system, and I 'll try the 2.9... Is the upgrade functionnal ?

**Comment by btry** [comment] 2019-10-03 16:05
The upgrade *should* be functional. I think  that the bugs might be some regressions : the biggest effort was on code refactor to raise code quality (export / import for example)

**Comment by mab18** [comment] 2019-10-04 08:03
Hi !
I make test : upgrade to 2.9.0-beta.1 on a VM snapshot : 
no change :-(
screenshot when fill in the form : 
![2019-10-04 09_50_33-GLPI - Formcreator - 01 - formulaire creation - bug - github](https://user-images.githubusercontent.com/55535560/66190910-66bdc200-e68d-11e9-99df-524d6260260c.png)
screenshot of the glpi ticket created : 
![Uploading 2019-10-04 09_50_33-GLPI - Formcreator - 02 - ticket glpi - bug - github.png…]()
screenshot of the form created : 
![2019-10-04 09_50_33-GLPI - Formcreator - 01 - formulaire cree - bug - github](https://user-images.githubusercontent.com/55535560/66190994-8fde5280-e68d-11e9-8ab0-4723fa5ec3bc.png)
and what I have in the glpi_plugin_formcreator_answer in "answer" in longtext format : 
`&lt;p&gt;image-ci-dessous :&lt;/p&gt;&lt;p&gt;&lt;img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALMAAAAYCAYAAACxz8zeAAACkklEQVR4nO2YP46rMBCHfSF8gByEoJxiy0jJ9unpkQ8QpUqRKkokilWqPcFK+y4yrwATe/Bgg4LeC/oVX2MN/oM/jwfUn98fAmAJqH89AQBeBWQGiwEyg8UAmcFigMxgMUBmsBggM1gMkBn8X5iclFJUmPHPQuYUbjvSSpFyKMyzXe+v7JmKChav9I7uvz9032f9fth4Zu08t67i82r7nhTTymPpr+WFtGMNjiHKfKVPrUipnIzwLGSOEZDhvs/SZLYi8k0cyD6N7Bl93objvAMjyhyJsWuz87ztqJhT5hQg83x4cgkyRGXmcQOSNlm53TCx/zZuvWs2WJA5FiOvzYrDDgLL4naezZxtP+2z66q7hbTOmj68dbMxbLs9+DrzxuiN3VtPBZljeHJNlZnLm5qZpf5N3m7mVZY5IUZamzgHd96Bdr2/du2FeZZUoUMs3kBuX96NFsvMkDmK+9LdendszezFpJYPQl3t1dRCpkqJkTKzL7lzML15uweWZWP2fRA6xN4YAZl7YkPmF8BrZik7hYSUPt4Sv9jFDe9iWNZNiQmtjdXMozOzczC05m1hmWOZuS9z5JaEzCOFFv5m9LOfLHP0b4bXp7Nxc8jsPMNvEC+zSzWz22c37+ech2QWb6ABmb3xA+uBzCCdlPJo6FeiQE/6iUBmkE70w3WEkPxWm3AIOJAZLAbIDN6Ubyo/SlrlTyAzeENq2uYlbapvrx0yg7fjdChpdajJSo3MDOblfKRVXtL2HIt1ywVD5SMWX9O2i6uptNn5fBwhczs5ntpT+KqMV9vEF/gK7Es60mmmMU4Hp2Y71HLs40KbvKTVx4W+Rvc/PP+UmNieWqbsbazv6F6fj0ziyL49LrQJvsea/gLiM5KS5xoaEQAAAABJRU5ErkJggg==" /&gt;&lt;/p&gt;&lt;p&gt;image cidessus&lt;/p&gt;`

**Comment by mab18** [comment] 2019-10-04 08:17
Nota : 
in the table glpi_plugin_formcreator_issues, the "comment" column is in text format (I think it's not good, and should be longtext too) and contains all the answers including the picture, but in my case, the picture is little and doesn't make truncation.

**Comment by btry** [comment] 2019-10-04 14:50
Yes, you're right.

But if the image is small enough (which seems to be true in your demonstration), the problem should not occur. Could you check if there us a truncated data in the issues table ?

**Comment by btry** [comment] 2019-10-04 14:58
Please test the fix #1518 

You can upgrade the plugin with the CLI tool and passing the argument --force-upgrade

```php scripts/cliinstall.php -force-upgrade```

This will run the upgrade process from the last version on itself.

**Comment by mab18** [comment] 2019-10-08 09:26
In the comment collumn of glpi_plugin_formcreator_issue, I see no truncation :

> &lt;div&gt;&lt;h1&gt;Donn&eacute;es du formulaire&lt;/h1&gt;&lt;h2&gt;(...)&lt;/b&gt;Clipboard picture try #001&lt;/div&gt;&lt;div&gt;&lt;b&gt;8) Définition de la demande : &lt;/b&gt;&lt;p&gt;Here the picture below :&lt;/p&gt;&lt;p&gt;&lt;img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAAyCAYAAADm1uYqAAAEIUlEQVR4nO3aPW7bMBjGcV7IOkAOIhk9RcYCdvbs3gUdoMjcybCBDBlzggLuFTo0GzvoI/wmZTty3uY//IDAlkxKpB69oqLe/v7RACCBunUHAKAUgQVADAILgBgEFgAxCCwAYhBYAMQgsACIQWABEIPAAiAGgQVADAILgBgEFgAxCCwAYhBYAMQgsACIQWABEIPAAiAGgQVADAILgBgEFgAxCCwAYhBYAMQgsACIQWABEEP9Pv3SACABgQVADAILgBgEFgAxCCwAYhBYAMQgsACIQWABEIPAAiAGgQVADAILgBgEFv5PXa2VUnrdnbP/Xj9USitV6y65XavXSmlVbfTx1scrUWyMYp8fNgTWog4bXSmllWHdvX9ebffOPsMFYRoujuN25f+O017XGPs1bb5fqQsvt80wyUb+sVzR0FayjWhgFYRRV2ulVvrhUHB8w3kJB6MzfsYYpMam/87snz8PPra93NwZz6ErF/CJMTLHlMD6BAIX/HG7KgusccK4F2qiiugDbbjoktWGMcmjgZXZZjy2sZ+HjV5/ZGCVuCCwusY5zszxedub523YZ7zBmBen97cVOIHASt10rthe+dwZzuW5FebcCuvUElhLsSaB+31pYLnbJSaTddeM/v6wXbNJTrzcNvFjc+7E475OtTL2s+/z+DvDvk07XXxVtep/wzpu/25v3bGrlX1Bum17x9Ofc/NcJcdu+j5TXRh9tn4vMDbZCqskIC5or3TuxALLqs6m75xxatp4kMbG7sQa1mJCZfdkZoU1BVRphRX7/a4eJlTiTlmwTezYon0w+x34vNrurUetKbACQR2tBgKPGP3+uQqrP+fmOU2O3dSfeKC5bdoB6FdPyfaMY7GWBaxxuay9orljtuM8NYT2DYZ+LrCMeTC2T2AtxBwwc6LNXcOytil91Iuse1h3wsjdu2SbWAViXwjGhRJ6LGla7VVVznpdKKitNkougDMCK1dh5QLLDdz5FZYhGSDXaq90zcwPrOB8adrwMWXGy58fBNZy3DWsWJVh7ZdZuyh8Exa9qGMTr2Sb0LE5azyzK6zT+8VVVe5n4cDKVVh+YOUqJv+RMLeGlXok9KpD9/wGzrXXv64uWga4WnuxuePJVFhev+ZVWKH5QWAtKfOW0K9i4oGVfUto/aY9+a8eWMY+biUYXM9IrSNN/XYfUWKPwpFqIBFYVvuxR1z388Rb0Oiie2hch7EMv4VLH0uwyv6I9mJzx1OwhuVVtuVrWKExIrCwvJJH2ewbMZ8XbBf1L7UmZUj+WwOujcDC8rIvC2YEgFtVnBF0Pv5x9LMisACIQWDhi3vVu/udvqsd9z/1y837BheBhS/sWX+vd/pb++p999J2+q7+oZ9u3keYCCx8WU+PO333+KzH4BqrqzHA3r+/fV/R+wdG/cZcW1GNOwAAAABJRU5ErkJggg==" /&gt;&lt;/p&gt;&lt;p&gt;above picture&lt;/p&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;9) Pièce jointe : &lt;/b&gt;Pas de document rattaché&lt;/div&gt;&lt;/div&gt;

We can see easily "above picture" after the paste picture.
Is any other correction/patch to make this to work ?

**Comment by btry** [comment] 2019-10-08 09:29
No patch yet. This issue needs more investigation.

**Comment by mab18** [comment] 2019-10-08 15:23
I did a test : 
Create a ticket with diredtly a picture from clipboard, here is what I get in glpi_tickets.content  column : 
&lt;p&gt;image ci-dessous&lt;/p&gt;&lt;p&gt;&lt;a href="http://my_ip_server/glpi/front/document.send.php?docid=426&amp;tickets_id=8938" target="_blank" rel="noopener"&gt;&lt;img src="http://my_ip_server/glpi/front/document.send.php?docid=426&amp;tickets_id=8938" alt="4055b03b-d9d62df8-5d9c80af31aac3.34643243" width="145" /&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;image ci-dessus&lt;/p&gt;

We can see a very different way to store the picture. In GLPI ticket, the clipboard picture is stored in a file, as a attachement. Instead of Form, which stores the image in the column.

Is pictures can be seen by this way ? Is it possible to see a picture without store it to a file ?
Have you got an example of picture stored by this way I could test in my installation ?

**Comment by btry** [comment] 2019-10-08 15:30
Hi

I already looked into that and I did not find a way to re-use this feature of GLPI in Formcreator. I'll focus instead on why the inline image is lost. Thank you for your investigations, this will probably be useful to find a fix.

**Comment by mab18** [comment] 2019-10-08 15:46
You're welcome ;-)
Do you mean that you can not reuse the piece of code behind this functionality introduced in https://glpi-project.org/glpi-9-2-available/ at "Paste images in rich text editor" ?
It's too bad. I'm too sad not to know how to code that and not understand the code behind it.

**Comment by mab18** [comment] 2019-11-18 15:45
@btry 
This ticket is the same problem as the number #1568

**Comment by btry** [comment] 2019-11-25 09:46
Hi 

could you try the branch of the above patch (in a testing environment) ? I think this should work fine.

**Comment by mab18** [comment] 2019-12-05 10:37
@btry : I have too much work this week :-( 
I have to create a context, I do my best to test as soon as I can.

**Comment by mab18** [comment] 2019-12-16 15:30
Hi,
Tests made for  #1568 : same test

**Comment by btry** [comment] 2020-01-10 12:56
Hi

As this issue is similar to #1568 I close this thread.

**Comment by btry** [comment] 2020-02-07 17:26
Hi 

I reopen this issue as I reproduced today, and found a fix.

https://github.com/pluginsGLPI/formcreator/pull/1672/commits/f93aa7dd5e61d47b23d4c26d769409ea83847700

Here is how I reproduced :

- create a form with a textarea field.
- load the list of forms in the admin side
- open the form then open the preview tab
- paste a picture with Ctrl+V 

If I reload the page, the paste shortcut works.

**Comment by btry** [comment] 2020-03-03 08:16
An other version of the fix was merged. Closing.

**Closed by btry** 2020-03-03 08:16 UTC
Labels: bug

**Comment by mab18** [comment] 2020-03-03 09:27
Hi,
@btry : please, can I apply this fix to my 2.9.1 ?
from wich bug this patch apply ? how can I test it ?

**Comment by btry** [comment] 2020-03-03 09:29
Hi, 

yes, you can !

**Comment by mab18** [comment] 2020-03-03 09:32
our message are crossed... Can I take the entire file or must just modify the code ? Because end of file is different, I think others fix change rest of code.

**Comment by mab18** [comment] 2020-03-03 09:36
Correcting the code is perfect.
