### ISSUE TITLE
Error when duplicating a form : duplication fails

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/formcreator#263] opened 2016-09-23 20:04 UTC
version 0.85-1.2.3 & 0.90-1.3.4
Duplicate a form, a simple one (one section, one question) -> it fails and generate the following sql error.
Note that in Destination tab, field 'Due date' is empty

  **\* MySQL query error:
  SQL: INSERT INTO `glpi_plugin_formcreator_targettickets` SET
                               `name`               = \"Destination 1\",
                               `tickettemplates_id` = 0,
                               `comment`            = \"##FULLFORM##\",
                               `due_date_rule`      = \"\",
                               `due_date_question`  = 0,
                               `due_date_value`     = 0,
                               `due_date_period`    = \"\"
  Error: Data truncated for column 'due_date_rule' at row 1
  Backtrace :
  plugins/formcreator/inc/form.class.php:1192  
  plugins/formcreator/inc/form.class.php:1227        PluginFormcreatorForm->Duplicate()
  inc/massiveaction.class.php:987                    PluginFormcreatorForm::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:966                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:58                         MassiveAction->process()

**Comment by btry** [comment] 2016-09-25 20:17
Hi

I could not reproduce yet, but I noticed several things

- your copy of the plugin is probably not up to date against the master branch : the line 1192 does not match the SQL query (I guess it is now line 1292)
- the database model has been updated but some code didn't.
- To reproduce I guess the form also needs to have at least 1 destination.

Anyway, I found something wrong in the source code, and I created a patch in my fork. Please test it and feedback.

I also noticed the setting to set the policy for the created tickets is not duplicated (see screenshot below). I fixed it. 

![image](https://cloud.githubusercontent.com/assets/14139801/18817970/acb3dac8-836d-11e6-993f-b648fe0fe0fe.png)

Direct link to download the plugin with the fix : https://github.com/btry/formcreator/archive/fix_263.zip

**Comment by blerohellec** [comment] 2016-09-27 21:17
Indeed, the form must have at least 1 destination, to get the error.
And the error occurs only when due_date is different from -- (not null)

**Comment by blerohellec** [comment] 2016-09-28 20:58
Still same error, when due_date is null !

  *** MySQL query error:
  SQL: INSERT INTO `glpi_plugin_formcreator_targettickets` SET
                               `name`               = \'Destination 1 x\',
                               `tickettemplates_id` = 0,
                               `comment`            = \'<p>##FULLFORM##</p>\',
                               `due_date_rule`      = \'\',
                               `due_date_question`  = 0,
                               `due_date_value`     = -30,
                               `due_date_period`    = \'minute\',
                               `destination_entity` = \'requester\'
  Error: Data truncated for column 'due_date_rule' at row 1
  Backtrace :
  plugins/formcreator/inc/form.class.php:1297        
  plugins/formcreator/inc/form.class.php:1363        PluginFormcreatorForm->Duplicate()
  inc/massiveaction.class.php:991                    PluginFormcreatorForm::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:970                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:64                         MassiveAction->process()

**Comment by btry** [comment] 2016-10-03 07:51
Hi

I don't reproduce with the current master branch. I think we may close this issue.

**Comment by btry** [comment] 2017-04-03 16:06
Closing due to lack of feedback.

**Closed by btry** 2017-04-03 16:06 UTC
Labels: bug, need feedback
