### ISSUE TITLE
Fill-in failed using Type field (GLPI Object) in Plugin Form

### ISSUE THREAD

**Issue by joesrangel** [pluginsGLPI/formcreator#1145] opened 2018-10-16 20:38 UTC
###  Fill-in failed using Type field (GLPI Object) in Plugin Form 

I noticed in my environment that after migrating from version 9.2.3 to version 9.3.1, all my forms with the field called (Applicant Group) of Type (Object GLPI) are functional in the (Preview) option under Administration> > Forms >> Select Forms >> Preview.

However, when accessing the same form through: Assistance >> Forms >> >> Select Forms >> ... When filling out the form the Type field (Object GLPI) is not displayed.

### Expected behavior
Preview and Fill successfully.

###  Screenshots 
The Type field (GLPI Object) works perfectly with the Display option in the Form Administration.

![image](https://user-images.githubusercontent.com/6306697/47044654-25c05b00-d167-11e8-8b2d-e60ee011adcf.png)

But the same form, accessing: Assistance >> Forms >> Select Forms >> When filling out the form the Type field (Object GLPI) is not displayed.

![image](https://user-images.githubusercontent.com/6306697/47045080-52c13d80-d168-11e8-8118-9818998c8d81.png)

** Desktop (fill in the following information): **
  - OS: [Windows 10]
  - Browser [Chrome, FireFox]
  - Version [68.0.3440.75 (64-bit), 62.0.3 (64-bit)]

###  Additional Context 

![image](https://user-images.githubusercontent.com/6306697/47045436-2f4ac280-d169-11e8-9fd3-7f94deb1e0e4.png)

Environmental Data.
GLPI version (9.3.1)
Plug-ins and versions installed in the environment
Additional fields (1.8.2).
Behavioral (2.1.1).
Scheduling (2.3.2).
Forms (2.6.4).
FusionInventory (9.3 + 1.1).
Object Management (2.6.2).
GLPI Modifications (1.2.2).
Print in PDF (1.4.0).
More Reports (1.5.2).
Browser notification (1.1.9).
OS Remix (0.2).
Panel (0.9.3).
Reports (1.11.3).

**Comment by mauriciolamego** [comment] 2018-10-17 10:01
I have several forms and I have this same problem. In my case, not only does the REQUESTING GROUP present problems, but when I insert the GLPI OBJECT observers and CALL CATEGORY.
It has a lot of impact.
Look out for us :)

**Comment by joesrangel** [comment] 2018-10-23 19:08
Hello good afternoon.
Firstly, I want to thank you for the attention and availability in the case you have proposed.

I validated and worked the solution correctly.
By removing and including the aforementioned line, the observer field that was previously represented by a dashed line now appears perfectly both in the preview and when requesting the form.

I would like to take the opportunity as you mentioned I wish to release version 2.6.5 quickly.

I detected another flaw in forms too.

When using a field called "Observer" of the Type "Object GLPI"

![image](https://user-images.githubusercontent.com/6306697/47384244-f5d00500-d6dc-11e8-8417-5edf76309e96.png)

When you select a particular one as an Observer in the Type field "Object GLPI"
As in the example, I selected the user (Alan da Silva Lima), the same is not included in the Observer field in the call, only in the description / body of the call.

![image](https://user-images.githubusercontent.com/6306697/47384444-94f4fc80-d6dd-11e8-820d-55b52f002574.png)

See that the destination is correct.
Observer >>> Actors of the question "Observers"

**Comment by btry** [comment] 2018-10-24 07:43
Hi

Do you use a ticket template in the target ticket? Do this template set any actor (requester, observer or assigned)?

**Comment by joesrangel** [comment] 2018-10-24 12:14
For this case No.
I do not use any calling template on the target.

I just set the parameter (Observers) in the Question Authors option.

I have already reviewed all my environment after updating to 9.3.1, I realized that this assignment is not working for (Observer) and (Requester Group).

**Comment by btry** [comment] 2018-10-25 09:55
Hi

I think you initially created your question with the type actors, then configured your target ticket, then finaly changed the question to GLPI Object / User type.

In such case the target ticket is not updated. Remove the OBserver entry, and add it again using the entry "Person from the question". AS I don't speak your language, I don't know how to translate it.

**Comment by joesrangel** [comment] 2018-10-29 12:55
Hello,
Once again I want to thank you for posting.

I apologize for the delay in responding.

The tips and answers posted here actually solved my problems.

However, the only thing that changed was the formalization.

Before using the field called "Observers" of the "Author" type ... and in the (Ticket Authors) set up as (Actors of the Question "Observers") ... It was possible to add several observers in a single field.

But using as (Question Person) and with Type field (Object GLPI), we are limited to a single user at a time.


But after all, we have been able to reshape the idea and purpose of the form in our environment.

Thankful.

**Comment by btry** [comment] 2018-10-29 15:40
Hi

> I apologize for the delay in responding.

Were you not in week end ? :D 

The actors field was designed to add several people in a single field, giving more power than a question of type Object GLPI + User. You should be able to use both types of questions. 

The issue is actually when you updae a question from the type Actors to GLPI Object + User or the reverse. I think that the best would be to merge the 2 settings "Person from the question" and Actors from the question" into a single choice. 

![image](https://user-images.githubusercontent.com/14139801/47661425-50fc6e80-db99-11e8-8332-13f03d162cd9.png)

**Comment by btry** [comment] 2018-10-30 15:19
Hi,

I think we can close this issue now. If possible I'll merge the 2 options in my previous comment and linked to the other ticket before releasing 2.7.0.

**Closed by btry** 2018-10-30 15:19 UTC
Labels: bug, need feedback
