### ISSUE TITLE
Problem on « Assiocated elements »

### ISSUE THREAD

**Issue by dgsn** [pluginsGLPI/formcreator#1649] opened 2020-01-31 14:55 UTC
See attached file :
[Problem on Assiocated elements.pdf](https://github.com/pluginsGLPI/formcreator/files/4139981/Problem.on.Assiocated.elements.pdf)

Server
Windows Server 2012 R2 Standard Edition
Apache/2.4.16 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.1p PHP/5.6.11 (Apache/2.4.16 (Win32) mod_authnz_sspi/0.1.0
OpenSSL/1.0.1p PHP/5.6.11 Server at
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36
Additional context
GLPI 9.4.5
formcreator Name: Form Creator Version: 2.9.1 State: Enabled

**Comment by btry** [comment] 2020-07-30 16:40
Hi

I fixed several problems when editing a target ticket. Can you confirm the problem is solved with the latest release ?

**Comment by btry** [comment] 2020-08-20 09:57
Hi

 Having no fedback, I close this ticket. Feel free to open a new one if issues occurs with the latest version.

**Closed by btry** 2020-08-20 09:57 UTC
Labels: bug
