### ISSUE TITLE
Show field with conditions not working

### ISSUE THREAD

**Issue by boscorelly** [pluginsGLPI/formcreator#423] opened 2017-01-11 16:17 UTC
Hi,

i use a field to ask for user email or not.
If yes, a field must appear. But it doesn't.

Any idea ?

**Comment by btry** [comment] 2017-01-11 16:22
Hi

Please tell the version of FormCreator and the version of GLPI.

Please show the details about the fields, and the question conditions on them.

**Comment by boscorelly** [comment] 2017-01-11 22:34
Hi,

Formulaires	0.90-1.4-beta7

I updated to this version to test if it's working or not, but with the last release, i have the same issue.

**Comment by btry** [comment] 2017-01-12 06:26
OK then if there is a bug the fix will go un this version.

I need to build a form with the same setup for the fields having the issue. Please show me how to create the questions ans their conditions.

**Comment by boscorelly** [comment] 2017-01-12 12:18
![formcreator_1](https://cloud.githubusercontent.com/assets/3873787/21889522/9b833800-d8c9-11e6-9110-42db1f8c8cba.PNG)
![formcreator_2](https://cloud.githubusercontent.com/assets/3873787/21889521/9b82d4dc-d8c9-11e6-91ff-f4d62877d360.PNG)

**Comment by matth974** [comment] 2017-02-08 06:17
I have the same problem... i've describe it on issue #442 .
With FormCreator 2-4-0.

Best regards.

**Comment by btry** [comment] 2017-02-08 07:01
Hi

 I found yesterday an error in the upgrade code. It affects the conditions. Can you check php-errors.log, sql-errors.log and show me the result of the following query ?

Show create table glpi_plugin_formcreator_questions_conditions;

**Comment by matth974** [comment] 2017-02-08 07:17
Thank for your reply.

Like my post on #442, sql-errors.log contain 0 errors about formCreator.
php-errors.log display 1 error:

`  *** PHP Warning(2): json_decode() expects parameter 1 to be string, array given
  Backtrace :
  :                                                  
  plugins/formcreator/inc/fields.class.php:173       json_decode()
  plugins/formcreator/ajax/showfields.php:23         PluginFormcreatorFields::isVisible()
2017-02-08 10:50:30 [520@BICHIQUES-TEST]
  *** PHP Warning(2): json_decode() expects parameter 1 to be string, array given
  Backtrace :
  :                                                  
  plugins/formcreator/inc/fields.class.php:173       json_decode()
  plugins/formcreator/ajax/showfields.php:23         PluginFormcreatorFields::isVisible()`

Here is the result of the show create table query:

> 	
CREATE TABLE `glpi_plugin_formcreator_questions_conditions` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `plugin_formcreator_questions_id` int(11) NOT NULL,
 `show_field` int(11) DEFAULT NULL,
 `show_condition` enum('==','!=','<','>','<=','>=') COLLATE utf8_unicode_ci DEFAULT NULL,
 `show_value` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
 `show_logic` enum('AND','OR','XOR') COLLATE utf8_unicode_ci DEFAULT NULL,
 `uuid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=52 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

>

**Comment by boscorelly** [comment] 2017-02-08 11:55
| glpi_plugin_formcreator_questions_conditions | CREATE TABLE `glpi_plugin_formcreator_questions_conditions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plugin_formcreator_questions_id` int(11) NOT NULL,
  `show_field` int(11) DEFAULT NULL,
  `show_condition` enum('==','!=','<','>','<=','>=') COLLATE utf8_unicode_ci DEFAULT NULL,
  `show_value` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `show_logic` enum('AND','OR','XOR') COLLATE utf8_unicode_ci DEFAULT NULL,
  `uuid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=41 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |

No errors in php-log

**Comment by btry** [comment] 2017-02-13 15:05
@boscorelly 
Your table is OK,  you're not impacted by the bug I found. 

I'll try to reproduce the warning found by @matth974 to see if  there is a relation with the bug.

**Comment by btry** [comment] 2017-02-13 17:11
I think I found the issue. It seems this si an upgrade problem when conditions already exist

@boscorelly can you run this query and show the result ?

SELECT id, show_logic from glpi_plugin_formcreator_questions_conditions where order=1

It the values in the column show_logic are not **null** then I'm in the right way.

**Comment by matth974** [comment] 2017-02-14 04:16
Hi @btry ,

For answer your post in #442, I have the following result:

id	show_logic	
1	NULL
2	NULL
3	NULL
4	NULL
5	NULL
6	NULL
7	NULL
8	NULL
9	NULL
10	NULL
11	NULL
12	NULL
13	NULL
14	NULL
15	NULL
16	NULL
17	NULL
18	NULL
19	NULL
20	NULL
21	NULL
22	NULL
23	NULL
24	NULL
25	NULL
26	NULL
27	NULL
28	NULL
29	NULL
30	NULL
31	NULL
32	NULL
33	NULL
34	NULL
35	NULL
36	NULL
37	NULL
38	NULL
39	NULL
40	NULL
41	NULL
42	NULL
43	NULL
44	NULL
45	NULL
46	NULL
47	NULL
48	NULL
49	NULL
50	NULL
51	NULL

**Comment by btry** [comment] 2017-02-14 06:00
@matth974 : Thank you. Unfortunately, I was expecting an operator AND OR or XOR. Your data is fine and this is something else which cause you trouble.

**Comment by matth974** [comment] 2017-02-14 07:19
@btry: perhaps my last comment here [https://github.com/pluginsGLPI/formcreator/issues/442#issuecomment-279445379](url) will help you.

**Comment by btry** [comment] 2017-02-14 08:44
When a user fills a form, he triggers HTTP requests to the plugin with the current values of the fields. The plugin sends back data to tell if fields shall show or hide. Maybe there is an HTTP 500 error in the process of these requests.

Can you open your browser's developer tools (Ctrl+Shift+I) , view the network activity then play with a form to see these requests and their status ?

Here is an example with Chrome

![image](https://cloud.githubusercontent.com/assets/14139801/22921441/067c7420-f29a-11e6-882c-7e0890398f3d.png)

**Comment by matth974** [comment] 2017-02-14 09:26
![networkflux](https://cloud.githubusercontent.com/assets/10028344/22923013/3ce4af90-f2b9-11e6-8f52-92286fcefd9e.PNG)

**Comment by btry** [comment] 2017-02-14 09:44
I don't see any call to showfields.php. 

Two cases seems possible : 
- you did not clicked on the checkbox **Autres** at least once,
- you clicked on **Autres** but no request fired.

If you are in the second case then the bug seems to be in the JS code.

**Comment by matth974** [comment] 2017-02-14 10:49
After apply the fix you told me in #442 it's ok.
Thank you.

**Comment by btry** [comment] 2017-02-14 11:43
@boscorelly : can you apply the patch un #442 and see if it works for you as well ?

**Comment by matth974** [comment] 2017-02-15 11:04
Hi,

@btry : Do you know when FC 2.4.1 will be available ? 
I hesitate to upgrade my production environment in 2-4-0 and then apply this patch.....

**Comment by btry** [comment] 2017-02-15 11:39
2.4.1 is a bugfix release only. Expect a release in a few weeks. It depends on the bug reported here (quantity and severity).

I cannot tell enough that users should stick to releases when using a plugin in production. If the issue prevents you to use the plugin, wait until the release 2.4.1 is out. If you can use a few forms without being impacted by the bug, feel free to install 2.4.0. You may disable forms impacted by the issue and wait for 2.4.1 to test them and enable them.

**Comment by matth974** [comment] 2017-02-16 04:09
Thank you.

**Comment by btry** [comment] 2017-02-20 08:28
fix in #442 solved this issue. Closing

**Comment by boscorelly** [comment] 2017-03-22 15:33
Not working for me, same problem :/

My conf is :
- hidden field
- shown if previous field = yes
- default is = no

**Closed** 2017-04-03 08:15 UTC
Labels: bug
