### ISSUE TITLE
"Adding question" display empty panel

### ISSUE THREAD

**Issue by CCoruble** [pluginsGLPI/formcreator#540] opened 2017-03-17 10:48 UTC
Actually on GLPI 9.1.2 and form creator 2.4.0.
When using formcreator everything goes fine except adding a question on a section.
Clicking on "add a question" display a white empty panel.
![2017-03-17 11_48_51-glpi - forms - 1](https://cloud.githubusercontent.com/assets/24699373/24040071/c15b8cc4-0b07-11e7-8be7-cf6445441ad8.png)

Tried with mutiples form with different parameters but still ain't working.

Thx to read this / fix it.

**Comment by btry** [comment] 2017-03-17 10:57
Hi

If you upgraded the plugin or GLPI, maybe you're facing a cache issue. Clear the cache of your browser first.

IF the bug persists, please open the developer tools of your browser and open the panel. Check there is no HTTP 500 error. If there is such error, check the HTTP server's logs and show the backtrace.

**Comment by CCoruble** [comment] 2017-03-17 11:38
I deleted the cache but still got the same result.

I tried opening the developer tools but it seems there is no HTTP 500 error.
_PS: To be honest I'm not sure there is no error, I tried "searching" all possibles words on the html code._

Also I noticed something, when you click on another "add something" for exemple "add a destination" on the "Destinations". If you close the panel and then go back to "Questions" click on "Add a question" will now show the "add a destination" panel. 
![2017-03-17 12_35_16-glpi - forms - 5](https://cloud.githubusercontent.com/assets/24699373/24041584/813371dc-0b0e-11e7-967e-dc7473a9d3e9.png)

**Comment by btry** [comment] 2017-03-17 18:19
A HTTP 500 error is a code returned by the server mostly when there is a fatal error in PHP. It does not appears in the HTML of the page.

Let's do more simple : reproduce the bug then view the server's error log. 

About your screenshot, i can't tell much. I need more information about this.

**Comment by CCoruble** [comment] 2017-03-21 11:13
Hi,
Sorry to make you wait, had things to fix.
I entered the debug mode and here is the error when I click on add question :

_Fatal error: Cannot make non static method PluginFormcreatorField::show() static in class userField in /var/www/html/glpi/plugins/formcreator/inc/fields/user-field.class.php on line 0_

![2017-03-21 12_12_20-glpi - formulaires - 2](https://cloud.githubusercontent.com/assets/24699373/24145009/b47005aa-0e2f-11e7-9878-6a269f08c133.png)

**Comment by CCoruble** [comment] 2017-03-21 11:31
Also, I don't know if there is a link between this and the error.
But there is a warning message on the home page of glpi (when I entered debug mode)

![2017-03-21 12_31_23-glpi - standard interface](https://cloud.githubusercontent.com/assets/24699373/24145630/53a05808-0e32-11e7-8011-d0df927115ac.png)

**Comment by btry** [comment] 2017-03-21 15:05
Hi

There is something wrong with your copy of the plugin : in the version 2.4.0 there is no file inc/fields/user-field.class.php. I also checked 0.90-1.3.4 by the way, and the file still does not exists.

About the warning you show in your latest message, don't worry, it is intended for developers. It is not related to FormCreator.

**Comment by CCoruble** [comment] 2017-03-21 15:21
Here is how I installed formcreator :
Download the file on your github
![2017_03_21_16_10_09_releases_pluginsglpi_formcreator](https://cloud.githubusercontent.com/assets/24699373/24154311/18534ade-0e51-11e7-9778-b732f9abe47e.png)

(I'm using GLPI on a VM so I used winscp to copy paste the file from my PC to the ubuntu server 16.04)
un-bz2 the file (uncompress), then un-tar (uncompress) the file to glpi/plugins/

Restart apache2, connect as super-admin glpi, go to plugins.
![2017-03-21 16_20_05-glpi - setup](https://cloud.githubusercontent.com/assets/24699373/24154754/5af94cfc-0e52-11e7-95f0-d30492357c3f.png)

Click upgrade 
This seems to be an error
![2017-03-21 16_21_06-glpi - setup](https://cloud.githubusercontent.com/assets/24699373/24154782/6dadd886-0e52-11e7-9389-c51f6716108b.png)

Then click "Enable"

**Comment by btry** [comment] 2017-03-21 15:33
Your procedure is correct (except it is useless to restart Apache). Anyway I also checked the .tar.gz file and I don't see user-field.class.php

![image](https://cloud.githubusercontent.com/assets/14139801/24155182/626f0c6e-0e53-11e7-9220-c873191231ce.png)

I guess you had a previous version of the plugin with this file, and you did not notice the file does no longer exist when you uplaoded the version 2.4.0.

I suggest you move the folder glpi/plugins/formcreator outside of GLPI, then recreate it from the archive. 

About the red warnings, this is a know issue, fixed in incoming 2.4.1 version.

**Comment by CCoruble** [comment] 2017-03-22 07:55
Hi,
Thanks for you answer.
I already tried deleting the entier file and starting from 0.
But somehow it worked this time after doing this for the third time.
Maybe my delete wasn't entierly done or some files stayed.
This works now, thanks you for everything !
One last question : Do you know (approximately) when the 2.4.1v will be released ?

**Comment by btry** [comment] 2017-03-22 08:14
I don't have a release date for the version 2.4.1 yet. It depends on the severity of latest bug reports.

**Closed by btry** 2017-03-22 08:14 UTC
