### ISSUE TITLE
Does not appear all of the entities

### ISSUE THREAD

**Issue by SYLWAD** [pluginsGLPI/formcreator#2667] opened 2022-03-30 15:34 UTC
Hello,

Since formcreator plugin 2.12.5, Does not appear all of the entities.
![image](https://user-images.githubusercontent.com/21087262/160873592-9cea94d6-f110-4761-985b-d4c36d06c9ca.png)

But when creating the form all the entities appear well
![image](https://user-images.githubusercontent.com/21087262/160873954-3d55cdbf-e36d-4b7a-89bb-73076df0edda.png)

**Comment by SYLWAD** [comment] 2022-03-30 15:51
Hi,
however before the update it worked fine

**Comment by btry** [comment] 2022-03-30 15:54
Which version you had before the upgrade ?

**Comment by SYLWAD** [comment] 2022-03-30 15:59
Even changing the settings does not change.

**Comment by btry** [comment] 2022-03-31 15:25
Hi

Not for now. A lot of work for to do for the next release, for glpi 10.

Community support is at best effort.

**Comment by btry** [comment] 2022-04-04 06:40
Hi

Try to reproduce with a super admin account with debug mode enabled. If you suceed to reproduce, open the debug panel on the right bottom corner of the page.

Choose th session tab in the debug panel then seatch wih Ctrl+F for "glpicondition". The browser should find a result

![image](https://user-images.githubusercontent.com/14139801/161486401-bd1186fd-d0dd-495f-a3de-5375dff641bb.png)

Click the double arrow to develop this entry. You will find a set of MD5 hash sub entries. One of them should contain a key glpi_entities.id close to this one (in my example it is truncated due to the limited size of the debug panel, chech carefully how is your result)
![image](https://user-images.githubusercontent.com/14139801/161486928-0f0542d4-496b-40dc-aa8d-4a5b3307c3cd.png)

Show the entry, and check carefully that you take the whole data (if truncated on screen). It represents the filter conditions of your entities dropdown.

**Comment by SYLWAD** [comment] 2022-04-04 15:23
I have many line with glpi_entites.id for information

![image](https://user-images.githubusercontent.com/21087262/161577368-2cfb6ffd-d840-40d5-addd-05f76d63f3b5.png)
![image](https://user-images.githubusercontent.com/21087262/161577437-67919612-2b09-471e-86f8-e6d16147f86f.png)


Thx

**Comment by SYLWAD** [comment] 2022-04-05 08:37
hello this is the good one:
![image](https://user-images.githubusercontent.com/21087262/161713639-41a4b1be-1473-442b-9c09-3a75c2dcf03f.png)


0	=>	0
179	=>	179
262	=>	262
163	=>	163
243	=>	243
88	=>	88
248	=>	248
260	=>	260
273	=>	273
211	=>	211
178	=>	178
331	=>	331
332	=>	332
81	=>	81
114	=>	114
182	=>	182
125	=>	125
200	=>	200
221	=>	221
28	=>	28
77	=>	77
101	=>	101
171	=>	171
219	=>	219
29	=>	29
82	=>	82
339	=>	339
69	=>	69
1	=>	1
274	=>	274
254	=>	254
327	=>	327
278	=>	278
319	=>	319
336	=>	336
275	=>	275
158	=>	158
123	=>	123
305	=>	305
162	=>	162
197	=>	197
299	=>	299
208	=>	208
191	=>	191
64	=>	64
261	=>	261
300	=>	300
188	=>	188
238	=>	238
166	=>	166
167	=>	167
118	=>	118
116	=>	116
170	=>	170
271	=>	271
291	=>	291
85	=>	85
214	=>	214
340	=>	340
130	=>	130
75	=>	75
244	=>	244
343	=>	343
150	=>	150
209	=>	209
227	=>	227
222	=>	222
252	=>	252
206	=>	206
106	=>	106
216	=>	216
127	=>	127
2	=>	2
320	=>	320
245	=>	245
14	=>	14
192	=>	192
294	=>	294
232	=>	232
80	=>	80
312	=>	312
107	=>	107
348	=>	348
24	=>	24
281	=>	281
355	=>	355
102	=>	102
151	=>	151
263	=>	263
323	=>	323
234	=>	234
255	=>	255
198	=>	198
276	=>	276
297	=>	297
239	=>	239
338	=>	338
295	=>	295
225	=>	225
104	=>	104
78	=>	78
71	=>	71
4	=>	4
67	=>	67
5	=>	5
315	=>	315
229	=>	229
124	=>	124
251	=>	251
164	=>	164
109	=>	109
6	=>	6
7	=>	7
250	=>	250
62	=>	62
8	=>	8
298	=>	298
212	=>	212
73	=>	73
93	=>	93
72	=>	72
259	=>	259
193	=>	193
89	=>	89
159	=>	159
207	=>	207
26	=>	26
97	=>	97
117	=>	117
318	=>	318
90	=>	90
272	=>	272
30	=>	30
148	=>	148
342	=>	342
204	=>	204
9	=>	9
135	=>	135
61	=>	61
65	=>	65
308	=>	308
258	=>	258
279	=>	279
306	=>	306
186	=>	186
277	=>	277
236	=>	236
270	=>	270
309	=>	309
196	=>	196
138	=>	138
346	=>	346
329	=>	329
293	=>	293
190	=>	190
213	=>	213
22	=>	22
98	=>	98
326	=>	326
345	=>	345
242	=>	242
249	=>	249
110	=>	110
317	=>	317
280	=>	280
359	=>	359
79	=>	79
321	=>	321
86	=>	86
215	=>	215
333	=>	333
168	=>	168
155	=>	155
237	=>	237
103	=>	103
12	=>	12
269	=>	269
328	=>	328
268	=>	268
95	=>	95
184	=>	184
350	=>	350
265	=>	265
325	=>	325
267	=>	267
112	=>	112
113	=>	113
119	=>	119
165	=>	165
147	=>	147
181	=>	181
134	=>	134
99	=>	99
347	=>	347
304	=>	304
76	=>	76
122	=>	122
307	=>	307
311	=>	311
301	=>	301
296	=>	296
205	=>	205
136	=>	136
111	=>	111
149	=>	149
316	=>	316
180	=>	180
10	=>	10
91	=>	91
11	=>	11
313	=>	313
137	=>	137
330	=>	330
105	=>	105
228	=>	228
253	=>	253
231	=>	231
115	=>	115
169	=>	169
247	=>	247
310	=>	310
289	=>	289
233	=>	233
203	=>	203
121	=>	121
132	=>	132
246	=>	246
154	=>	154
337	=>	337
3	=>	3
322	=>	322
358	=>	358
354	=>	354
264	=>	264
129	=>	129
25	=>	25
324	=>	324
353	=>	353
133	=>	133
220	=>	220
357	=>	357
290	=>	290
235	=>	235
210	=>	210
63	=>	63
17	=>	17
16	=>	16
199	=>	199
266	=>	266
161	=>	161
344	=>	344
94	=>	94
15	=>	15
189	=>	189
314	=>	314
292	=>	292
68	=>	68
349	=>	349
57	=>	57
58	=>	58
341	=>	341
18	=>	18
19	=>	19
56	=>	56
128	=>	128
157	=>	157
202	=>	202
223	=>	223
224	=>	224
51	=>	51
87	=>	87
96	=>	96
152	=>	152
195	=>	195
52	=>	52
53	=>	53
70	=>	70
108	=>	108
194	=>	194
20	=>	20
139	=>	139
226	=>	226
240	=>	240
241	=>	241
230	=>	230
351	=>	351
352	=>	352
356	=>	356
23	=>	23
31	=>	31
32	=>	32
33	=>	33
34	=>	34
36	=>	36
37	=>	37
38	=>	38
39	=>	39
40	=>	40
41	=>	41
59	=>	59
175	=>	175
187	=>	187
256	=>	256
283	=>	283
284	=>	284
287	=>	287
334	=>	334
303	=>	303
141	=>	141
142	=>	142
143	=>	143
144	=>	144
145	=>	145
146	=>	146
156	=>	156
160	=>	160
172	=>	172
173	=>	173
174	=>	174
176	=>	176
177	=>	177
183	=>	183
185	=>	185
217	=>	217
218	=>	218
257	=>	257
282	=>	282
285	=>	285
286	=>	286
288	=>	288
302	=>	302
335	=>	335
54	=>	54
55	=>	55
42	=>	42
43	=>	43
44	=>	44
45	=>	45
46	=>	46
201	=>	201
360	=>	360
361	=>	361
362	=>	362
363	=>	363
364	=>	364
365	=>	365
366	=>	366
367	=>	367
368	=>	368
369	=>	369
370	=>	370

**Comment by btry** [comment] 2022-04-05 09:59
Hi

Try the following fix 154a353194aae49b630351f1117ed552054067ae

**Comment by Dead-Red** [comment] 2022-04-06 09:20
Hello,

I have the same problem and your solution solves it.

Thank's !

**Comment by btry** [comment] 2022-04-06 10:07
Hi

The fix already existed, and added after the release 2.12.5. it is then validated. I think I can close this issue.

@SYLWAD the fix should also work for you. Feel free to reopen if the bug persists with the patch.

**Comment by SYLWAD** [comment] 2022-04-07 14:43
reopen

**Comment by SYLWAD** [comment] 2022-04-07 14:49
@btry how to reopen the issue ?

**Comment by btry** [comment] 2022-04-07 16:22
Hi

You should not overwrite the whole files to apply a patch. This may cause problems, potentially breaking your glpi  instance

**Comment by SYLWAD** [comment] 2022-04-08 12:16
hi,

how should it be done?

**Comment by CIVIER-C** [comment] 2022-04-08 13:15
I have the same problem with Fomcreator V2.12.5.
Fix 154a353 is not referenced in V2.12.5 https://github.com/pluginsGLPI/formcreator/releases/tag/v2.12.5

**Comment by btry** [comment] 2022-04-08 16:15
Hi

Indeed this fix has been created for a bug report done a few days after the release 2.12.5. that's why we need you, community users or subscription users, to test beta versions !

I think that 2.12.5 will be the last maintenance version. Please prepare to switch to glpi 10 thanks to the release candidate versions available.

**Comment by btry** [comment] 2022-04-12 05:49
Hi

This problem is solved (twice), then I close

Duplicate: https://github.com/pluginsGLPI/formcreator/issues/2641

**Closed by btry** 2022-04-12 05:49 UTC
Labels: bug, need feedback

**Comment by SYLWAD** [comment] 2022-04-12 10:11
open: #2667

**Comment by SYLWAD** [comment] 2022-04-12 10:15
Hello @btry ,

Soory but is not function with the last patch: https://github.com/pluginsGLPI/formcreator/commit/154a353194aae49b630351f1117ed552054067ae.patch

![image](https://user-images.githubusercontent.com/21087262/162938213-f4a4958c-19fa-410a-b99e-50914752fcbc.png)

This my php file
[dropdownfield.class.txt](https://github.com/pluginsGLPI/formcreator/files/8471974/dropdownfield.class.txt)

thanks a lot for your return

**Comment by btry** [comment] 2022-04-12 10:25
To download the patch try to append .diff to the URL instead of .patch

**Comment by SYLWAD** [comment] 2022-04-12 11:12
same
![image](https://user-images.githubusercontent.com/21087262/162947685-4f0812cb-30f7-478a-ab16-6cc25cb43b87.png)
For information my directry is "fields" and not "field"

**Comment by SYLWAD** [comment] 2022-04-12 11:13
mypatch.diff:
diff --git a/inc/fields/dropdownfield.class.php b/inc/fields/dropdownfield.class.php
index 4ebf521d2..407be8dbc 100644
--- a/inc/fields/dropdownfield.class.php
+++ b/inc/fields/dropdownfield.class.php
@@ -249,6 +249,7 @@ public function buildParams($rand = null) {
          case Entity::class:
          case Document::class:
             unset($dparams['entity']);
+            break;
 
          case User::class:
             $dparams['right'] = 'all';

**Comment by btry** [comment] 2022-04-12 11:16
In both versions you have an error which says the diff or patch is incomplete. This maybe cause by a mess with line ending. This is a single line, then add it by hands, then generate a patch. Test your patch by reverting it and applying it again with the patch tool. Finally keep it until you upgrade to 2.13.0
