### ISSUE TITLE
Form categories are not filtered by entities

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1825] opened 2020-06-18 14:31 UTC
The error happened after updating the form to version v292

Error: When navigating between entities, the list of categories on the forms are not displayed according to the selected entity.

Expected situation: The categories of the form should be presented only to the forms visible to the respective entity.

The attached image is the environment with the forms filtered by entity (V.2.8.6)

![image](https://user-images.githubusercontent.com/35368369/84581681-4583a880-adba-11ea-86cc-abc54945eaee.png)

The image below is the same environment, after upgrading to v292. Note that there is no category filter.

![image](https://user-images.githubusercontent.com/35368369/84581732-d65a8400-adba-11ea-8e8e-8754cbd7e135.png)

_Originally posted by @phamorais in https://github.com/pluginsGLPI/formcreator/issues/1811#issuecomment-643699091_

Formcreator v292
GLPI 9.4.6

**Comment by btry** [comment] 2020-06-18 15:41
Hi

I don't understand the reason of this issue, as it is a duplicate of #1811. Can you clarify ?

**Comment by phamorais** [comment] 2020-06-18 15:55
Hello @btry 

It was my fault. The problem was resolved in the issue https://github.com/pluginsGLPI/formcreator/issues/1811

You can close this issue

**Comment by btry** [comment] 2020-06-18 15:56
Thanks !

**Closed by btry** 2020-06-18 15:56 UTC
Labels: bug, duplicate
