### ISSUE TITLE
Pb with dropdowns and conditions between fields

### ISSUE THREAD

**Issue by blerohellec** [pluginsGLPI/formcreator#259] opened 2016-09-19 21:27 UTC
version 0.85-1.2.3 and 0.90-1.3.4
Create a form : 1 section, 2 questions
question1 : typed dropdown 'user titles'. Dropdown 'User titles' contains 2 lines : title 1, title 2. No default value
question2 : typed text. Hidden unless 1st question = title 1
Execute the form. Question1, choose 'title 1' -> nothing happens, question2 isn't displayed !

Add to question1 a default value = title 1. Execute the form : question1 is positionned on 'title 1' (OK) and question2 is displayed (OK). Change question1 to 'title 2' (question2 disappears -> OK). Go back to title 1 -> nothing happens, question2 isn't displayed !

With version 0.85-1.2.3 : same behaviour and additional php-error
 *** PHP Warning(2): in_array() expects parameter 2 to be array, integer given 
  Backtrace : 
  :                                                  
  plugins/formcreator/inc/fields.class.php:160       in_array() 
  plugins/formcreator/ajax/showfields.php:22         PluginFormcreatorFields::isVisible()

**Comment by btry** [comment] 2016-09-20 09:07
Hi

I tried to reproduce. It appears  the bug appears because "title 1" is already selected when the form is displayed. Opening the dropdown and clicking on "title 1" does not changes the selected value then question 2 does not show.

**Comment by btry** [comment] 2016-09-20 11:58
I got a

**Comment by btry** [comment] 2016-10-03 13:29
Hi

I merged this fix too. You may check it with the master branch

**Comment by btry** [comment] 2016-10-12 13:54
Hi

My tests shows the issue is solved. Closing. Feel  free to reopen if needed.

**Closed by btry** 2016-10-12 13:54 UTC
Labels: bug, need feedback
