### ISSUE TITLE
Form category presentation for incorrect simplified interface - 2.13.0-beta.2

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2783] opened 2022-05-18 23:23 UTC
**Describe the bug**
In the "2.13.0-beta.2" version, I noticed that due to the simplified interface the system is hiding the category name if it is too big

**Screenshots**

Formcreator 2.12.5

![image](https://user-images.githubusercontent.com/35368369/169170766-0a9c2fe4-df8b-4c43-b124-5cfcc5b4bd5b.png)

Formcreator 2.13.0-beta.2

![image](https://user-images.githubusercontent.com/35368369/169170843-c86bde4d-cb12-4604-bb7d-b6c1951d20ad.png)

**GLPI / Plugins (please complete the following information):**
- GLPI 10.0.0
- No plugins activated

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Google Chrome
 - Version: 101.0.4951.67

**Comment by btry** [comment] 2022-05-19 06:54
Hi

Apply the above patch and recompile the CSS of the plugin with the following cmmand, located in the GLPI directory.

```bin/console glpi:plugin:formcreator:scss```

Finally, check it the problem is solved. A long category name should use only one line. A tooltip must show whan hovering the category.

**Comment by btry** [comment] 2022-05-19 07:40
duplicatd #2759

**Comment by phamorais** [comment] 2022-05-23 17:48
@btry Hi!

Hi!
After applying the path, the categories 'disappeared'

styles.scss

![image](https://user-images.githubusercontent.com/35368369/169876897-964a2ea1-4e21-42b1-9d7f-b77e0b500e32.png)
![image](https://user-images.githubusercontent.com/35368369/169877157-c79c3a13-4f70-48a2-b05a-a05b3ef1f0c4.png)


scripts.js

![image](https://user-images.githubusercontent.com/35368369/169876965-ab1cb57c-4e67-444a-bc6c-7ba5c2d41dcb.png)

Recompile scss
![image](https://user-images.githubusercontent.com/35368369/169877408-2092c9c0-db6b-4b6a-935b-5c8fb51d862c.png)


GLPI after update

![image](https://user-images.githubusercontent.com/35368369/169877215-c3eb2cbb-322a-4580-ab6f-3cc367bd7c8a.png)

**Comment by btry** [comment] 2022-05-23 17:53
Hi

I already merged the patch and I don't have such problems. Did you use the patch tool or did you edit the files manually ?

**Comment by btry** [comment] 2022-05-24 09:19
Hi

It apears you have a valid subscription. Please submit a ticket for this issue, to let me send a documentation to guide you to apply a patch properly. this will be more reliable to validate the fix provided here.

**Comment by phamorais** [comment] 2022-05-24 11:08
Hi @btry 

I will submit the ticket in the support area :)

**Comment by bolivarf** [comment] 2022-05-27 18:48
It also has the upside down icon forms have the question icon and FAQs have the form icon

**Comment by btry** [comment] 2022-05-28 08:40
Hi @bolivarf 

Your issue is very likely not related to this one. Here we are talking about categories with long text, not icons.

**Comment by bolivarf** [comment] 2022-05-28 13:42
hi @btry 
It doesn't show me the form categories but I see on all the screenshots that the question and form icons are swapped but no one seems to notice and I think it's not just the icon but part of the code that shows the FAQ and the forms.

**Comment by btry** [comment] 2022-05-28 14:06
Open a new issue, show the configuration of a form and a screenshot where we can see this form and a faq item.

**Closed** 2022-06-24 09:04 UTC
Labels: duplicate, need feedback
