### ISSUE TITLE
 Does not attach file to ticket - Version 2.6.3

### ISSUE THREAD

**Issue by JulioAugustoS** [pluginsGLPI/formcreator#1097] opened 2018-09-04 20:04 UTC
See the errors bellow.

To Reproduce

1. Switch to user profile
2. Fill in ticket information
3. Select a file to attach to the ticket
4. Click on open ticket

When opening a ticket with a file attachment, you are not inserting the attachment in the database, the file is moved normally, but not inserted in the database.

Desktop:
 - OS: Windows 7 and Windows 10
 - Browser:  Google Chrome and Mozilla Firefox

**Comment by btry** [comment] 2018-09-05 07:43
Hi

Can you try the version 2.6.4 please ?

**Comment by JulioAugustoS** [comment] 2018-09-05 11:01
I did the test in version 2.6.4 and the same thing happens

**Comment by btry** [comment] 2018-09-05 11:29
Is it important to switch to a user profile to reproduce ?

**Comment by btry** [comment] 2018-09-05 11:30
Also check the SQL errors log and php errors log. Maybe there is something helpful

**Comment by JulioAugustoS** [comment] 2018-09-05 11:53
Yes, it has to be in the user profile. Okay, you're going to check the logs and I'll let you know.

**Comment by btry** [comment] 2018-10-15 13:53
Hi

Do you have feedback with this issue ? IS there something related in the logs when you reproduce the issue ?

**Comment by imanou10** [comment] 2018-10-31 08:41
Hi
I have the same problem can you help me. thanks

**Comment by btry** [comment] 2018-10-31 08:45
Hi @imanou10 

Can you check the logs of glpi ? I could not reproduce yet. By the way, I did a check on file field recently, and you must put only one file in the field. If several files are added, the plugin is unable to process them (fixed in 2.7.0).

**Comment by btry** [comment] 2018-10-31 09:34
I think I understand !

A change was done in the version 2.6.0 when processing file fields. Please read the readme of this version.

https://github.com/pluginsGLPI/formcreator/blob/2.6.0/README.md#upgrade-to-260

You must specify the answer of the file field to tell Formcreator that the file must be linked to the target ticket.  I think your problem is simply here.

@JulioAugustoS Do this information solve your problem ?

**Comment by btry** [comment] 2022-06-09 12:12
Hi

Having no feedback, I close.

**Closed by btry** 2022-06-09 12:12 UTC
Labels: need feedback
