### ISSUE TITLE
Hide answers after Form creation 

### ISSUE THREAD

**Issue by BradacKamil** [pluginsGLPI/formcreator#920] opened 2018-02-23 13:36 UTC
GLPI 9.2.1
Form 2.6.2

After filing form, filed questions with Condition are hide and invisible for Approver 

![during form filling](https://user-images.githubusercontent.com/36759517/36596564-06ae8fde-189e-11e8-94da-9dad8fd1dee9.JPG)

Created form

![created form](https://user-images.githubusercontent.com/36759517/36596730-9176fc28-189e-11e8-9b67-95e30eac9d31.JPG)

Thanks for help

**Comment by btry** [comment] 2018-02-23 13:38
Hi

In this form do you have 2 fields with conditions, or more ?

**Comment by BradacKamil** [comment] 2018-02-23 13:46
Hi 

+- 8 fields with conditions, if I filing form all working well but after creation all fields with conditions are hide

**Comment by btry** [comment] 2018-02-23 13:47
Ok, then they all fail. Thank you.

**Comment by BradacKamil** [comment] 2018-02-23 14:10
Do you have any idea why?

**Comment by btry** [comment] 2018-02-23 14:26
Yes I got one. I'm curently working on something else. I'll investigate in 10 days. Earlier if I got free time.

**Comment by btry** [comment] 2018-03-26 12:32
Hi

I reproduce with version 2.6.2, but no longer with develop branch (some fixes done on conditions).

Please use your testing environment to validate the development version and feedback.

**Comment by btry** [comment] 2018-03-26 15:09
Seems to be a duplicate of #918

**Comment by btry** [comment] 2018-04-23 11:58
Hi

No feedback, I assume the issue is solved.

**Closed by btry** 2018-04-23 11:58 UTC
Labels: bug, duplicate, need feedback
