### ISSUE TITLE
Can link the object of dropdown menu

### ISSUE THREAD

**Issue by orom3ro** [pluginsGLPI/formcreator#2583] opened 2022-02-09 16:22 UTC
When I create a question and select the type as dropdown menu or glpi object, it does not appear visible in the form or it does not let me select any object.

![Screen Shot 2022-02-09 at 12 16 39 PM](https://user-images.githubusercontent.com/71388071/153242660-dfb08a44-3638-4e13-a383-e29e5f50a610.png)

![Screen Shot 2022-02-09 at 12 17 57 PM](https://user-images.githubusercontent.com/71388071/153242929-abe54b24-1659-467c-83f1-635d22113dec.png)

![Screen Shot 2022-02-09 at 12 18 14 PM](https://user-images.githubusercontent.com/71388071/153242995-4bade589-fffa-4478-aa06-95f8bd1d732e.png)
![Screen Shot 2022-02-09 at 12 18 25 PM](https://user-images.githubusercontent.com/71388071/153243034-55d59b63-d9da-4ee9-8234-065a933946bd.png)
![Screen Shot 2022-02-09 at 12 18 36 PM](https://user-images.githubusercontent.com/71388071/153243066-d3d27574-9fdd-4f9f-a82f-fecbd9cda64d.png)

<details><summary>Información sobre la instalación y configuración del sistema</summary><pre>GLPI 10.0.0-rc1 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:es_VE

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64
PHP 8.1.1 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi.dumit.local Port 80
)
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:96.0) Gecko/20100101 Firefox/96.0
Server Software: (Ubuntu)
	Server Version: 8.0.28-0ubuntu0.20.04.3
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.1) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (8.0.28) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.0-rc1
GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/html/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.3 State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0-rc4  State: Enabled
	geninventorynumber   Name: Inventory number generation    Version: 2.6.0-rc2  State: Enabled
	livechat             Name: Livechat                       Version: 1.0.4      State: Enabled
	metademands          Name: Meta-Demands                   Version: 3.0.0-rc2  State: Enabled
	mydashboard          Name: My Dashboard                   Version: 2.0.0-rc3  State: Not installed
	genericobject        Name: Objects management             Version: 2.12.0-rc2 State: Enabled
	tasklists            Name: Tasks list                     Version: 2.0.0-rc2  State: Enabled
	telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Enabled
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.0-rc1 State: Enabled
	typology             Name: Typologies                     Version: 3.0.0-rc1  State: Enabled
	useditemsexport      Name: Used items export              Version: 2.5.0-rc2  State: Enabled

</pre></details>

**Comment by btry** [comment] 2022-02-16 07:36
Hi

Could you please check if the issue still occurs with the latest revision of the branch support/2.13.0 ?

**Comment by orom3ro** [comment] 2022-02-17 12:15
Hi!

I'm Using the version 2.13.0-alpha.3

<img width="323" alt="Screen Shot 2022-02-17 at 8 13 40 AM" src="https://user-images.githubusercontent.com/71388071/154479609-c73b3814-224e-4f7b-8e78-5bca568e21e4.png">

I attach a video

https://user-images.githubusercontent.com/71388071/154479345-a47107bd-b436-4162-b902-ef5650a93e7d.mp4

**Comment by btry** [comment] 2022-02-17 12:19
Hi

Since the tag 2.13.0-alpha.3 many commits were added; then I need to know if you're using the 2.13.0-alpha.3 as is or with the latest changes (which is better to verify if  the problem is not already fixed).

**Comment by orom3ro** [comment] 2022-02-17 12:41
I'm using the latest version.

Php-error.log

![Screen Shot 2022-02-17 at 8 41 02 AM](https://user-images.githubusercontent.com/71388071/154483869-bcc35558-8094-41e7-948d-78621d1a901e.png)

**Comment by btry** [comment] 2022-02-17 13:10
You're using the latest version, yes, but not the latest  revision. This bug is already fixed.

Apply this fix, then feedback. I'm confident that the preview will work after that.

https://github.com/pluginsGLPI/formcreator/pull/2585

Also, next  time consider pasting the log sample aas  text instead of an image. It may be faster for me to investigate if I can copy / paste some data from the log.

**Comment by orom3ro** [comment] 2022-02-17 13:42
I unistall and install the version:  " formcreator          Name: Form Creator                   Version: 2.13.0-alpha.3"

Log Files 

[2022-02-17 09:27:19] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/plugins/formcreator/ajax/dropdown_values.php at line 48
[2022-02-17 09:27:40] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/plugins/formcreator/ajax/dropdown_values.php at line 48
[2022-02-17 09:27:50] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method PluginFormcreatorForm::getFromDBByQuestion() in /var/www/html/glpi/plugins/formcreator/inc/field/dropdownfield.class.php at line 218
  Backtrace :
  ...rmcreator/inc/field/dropdownfield.class.php:481 GlpiPlugin\Formcreator\Field\DropdownField->buildParams()
  ...ins/formcreator/inc/abstractfield.class.php:102 GlpiPlugin\Formcreator\Field\DropdownField->getRenderedHtml()
  plugins/formcreator/inc/question.class.php:300     PluginFormcreatorAbstractField->show()
  .../twig/twig/src/Extension/CoreExtension.php:1597 PluginFormcreatorQuestion->getRenderedHtml()
  ...tes/6a/6ac159fdcc385e94cf868de1652e065b.php:200 twig_get_attribute()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_e5ff7f1d620cd8d87965bc09fff8533f->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  plugins/formcreator/inc/form.class.php:1036        Glpi\Application\View\TemplateRenderer->display()
  plugins/formcreator/inc/form.class.php:548         PluginFormcreatorForm->displayUserForm()
  src/CommonGLPI.php:687                             PluginFormcreatorForm::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

[2022-02-17 09:28:21] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method PluginFormcreatorForm::getFromDBByQuestion() in /var/www/html/glpi/plugins/formcreator/inc/field/dropdownfield.class.php at line 218
  Backtrace :
  ...rmcreator/inc/field/dropdownfield.class.php:481 GlpiPlugin\Formcreator\Field\DropdownField->buildParams()
  ...ins/formcreator/inc/abstractfield.class.php:102 GlpiPlugin\Formcreator\Field\DropdownField->getRenderedHtml()
  plugins/formcreator/inc/question.class.php:300     PluginFormcreatorAbstractField->show()
  .../twig/twig/src/Extension/CoreExtension.php:1597 PluginFormcreatorQuestion->getRenderedHtml()
  ...tes/6a/6ac159fdcc385e94cf868de1652e065b.php:200 twig_get_attribute()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_e5ff7f1d620cd8d87965bc09fff8533f->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  plugins/formcreator/inc/form.class.php:1036        Glpi\Application\View\TemplateRenderer->display()
  plugins/formcreator/inc/form.class.php:548         PluginFormcreatorForm->displayUserForm()
  src/CommonGLPI.php:687                             PluginFormcreatorForm::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

[2022-02-17 09:28:30] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "telegram_username" in /var/www/html/glpi/plugins/telegrambot/inc/user.class.php at line 67
  Backtrace :
  src/Plugin.php:1438                                PluginTelegrambotUser::item_update_user()
  src/CommonDBTM.php:1505                            Plugin::doHook()
  ajax/search.php:53                                 CommonDBTM->update()

[2022-02-17 09:28:45] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Undefined constant GuzzleHttp\ClientInterface::MAJOR_VERSION in /var/www/html/glpi/vendor/guzzlehttp/guzzle/src/Utils.php at line 113
  Backtrace :
  vendor/guzzlehttp/guzzle/src/functions.php:71      GuzzleHttp\Utils::defaultUserAgent()
  ...bot/vendor/guzzlehttp/guzzle/src/Client.php:194 GuzzleHttp\default_user_agent()
  ...mbot/vendor/guzzlehttp/guzzle/src/Client.php:75 GuzzleHttp\Client->configureDefaults()
  ...vendor/longman/telegram-bot/src/Request.php:215 GuzzleHttp\Client->__construct()
  ...endor/longman/telegram-bot/src/Telegram.php:167 Longman\TelegramBot\Request::initialize()
  plugins/telegrambot/inc/bot.class.php:91           Longman\TelegramBot\Telegram->__construct()
  plugins/telegrambot/inc/bot.class.php:52           PluginTelegrambotBot::getTelegramInstance()
  plugins/telegrambot/inc/cron.class.php:45          PluginTelegrambotBot::getUpdates()
  src/CronTask.php:1016                              PluginTelegrambotCron::cronMessageListener()
  front/cron.php:62                                  CronTask::launch()

[2022-02-17 09:28:55] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method PluginFormcreatorForm::getFromDBByQuestion() in /var/www/html/glpi/plugins/formcreator/inc/field/dropdownfield.class.php at line 218
  Backtrace :
  ...rmcreator/inc/field/dropdownfield.class.php:481 GlpiPlugin\Formcreator\Field\DropdownField->buildParams()
  ...ins/formcreator/inc/abstractfield.class.php:102 GlpiPlugin\Formcreator\Field\DropdownField->getRenderedHtml()
  plugins/formcreator/inc/question.class.php:300     PluginFormcreatorAbstractField->show()
  .../twig/twig/src/Extension/CoreExtension.php:1597 PluginFormcreatorQuestion->getRenderedHtml()
  ...tes/6a/6ac159fdcc385e94cf868de1652e065b.php:200 twig_get_attribute()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_e5ff7f1d620cd8d87965bc09fff8533f->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  plugins/formcreator/inc/form.class.php:1036        Glpi\Application\View\TemplateRenderer->display()
  plugins/formcreator/inc/form.class.php:548         PluginFormcreatorForm->displayUserForm()
  src/CommonGLPI.php:687                             PluginFormcreatorForm::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

**Comment by btry** [comment] 2022-02-17 13:47
Hi

Did you applied the fix I mentioned above ?

**Comment by orom3ro** [comment] 2022-02-17 13:57
> Hi
> 
> Did you applied the fix I mentioned above ?

Sorry. Already aplied the fix and now is working fine. Thank you.

**Comment by btry** [comment] 2022-02-17 14:09
Great, then i close this issue. Thank you for your feedback.

**Closed by btry** 2022-02-17 14:09 UTC
Labels: bug, duplicate
